### ISSUE TITLE
DONE file created in the current, not target directory

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#105]
if directory to upload is specified, the DONE file is created and uploaded from the current, not from the target directory.
it has been stated previously that having DONE in the image (success) directory is useful, as that shows whether the sequence has been finalised.

**Comment by ybkuang** [comment]
Good find. Will work on a fix for it.

**Comment by richlv** [comment]
i actually have a patch for it, just gotta test it :)

**Comment by Blackbird27** [comment]
Is this why I get `OS error: [Error 183] Cannot create a file when that file already exists on DONE` when I submitting a sequence (pressing "y") when using upload_with_authentication.py script? the message appears couple of times and eventually I get `Done uploading.` message.

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). The logging has been improved, so users have more insight over the progress of process and upload.
Hopefully usage will be smoother now, if not please let us know
