### ISSUE TITLE
--auto_done not working

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#110]
When executing with **--auto_done** no images are uploaded, and I get the following message (directory with ~430 correctly geotagged files, uploaded with no problem without --auto_done)
```
# ./mapillary_tools/python/upload_with_authentication.py --auto_done VIRB/20160301235623/
No images in the folder or all images have all ready been uploaded to Mapillary
Note: If upload fails mid-sequence due to connection failure or similar, you should manually push the images to the server at http://www.mapillary.com/map/upload/im/ and pressing "push to Mapillary".
```

**Comment by ybkuang** [comment]
@Skippern can you try ```./mapillary_tools/python/upload_with_authentication.py VIRB/20160301235623/ --auto_done``` instead? It assumes the path_to_images is the first input parameter.

**Comment by Skippern** [comment]
Thanks @ybkuang that worked, though it is contrary to what the help option says

```
# ./mapillary_tools/python/upload_with_authentication.py -h
usage: upload_with_authentication.py [-h] [--upload_subfolders] [--auto_done]
                                     path
```

**Comment by ybkuang** [comment]
@Skippern It should work better now! Sorry for the inconvenience.
