### ISSUE TITLE
Not Enough Data from Remove Duplicates

### ISSUE THREAD

**Issue by JulieMay** [mapillary/mapillary_tools#112]
The image source was the Mapillary for Android App. 

I wanted to clean up the tour, adjust the brightness and saturation a bit, and upload the images.

When I tried the remove duplicates command this is the traceback. I have both PIL and pillow installed as an earlier error indicated PIL was being called instead of pillow.

The Readme for dependencies doesn't even mention pillow, by the way.

c:\wamp\www\mapillary_tools\mapillary_tools\python>python remove_duplicates.py -
d 2 C:\Users\Julie\Pictures\2016-Mapillary-Banff\2016_03_17_15_11_23_659___Mapil
lary C:\Users\Julie\Pictures\2016-Mapillary-Banff\Temp_Duplicates
Traceback (most recent call last):
  File "remove_duplicates.py", line 417, in <module>
    image_remover.do_magic()
  File "remove_duplicates.py", line 262, in do_magic
    capturetime, files = self._sort_file_list(files)
  File "remove_duplicates.py", line 251, in _sort_file_list
    capture_times = [self._read_capture_time(filepath) for filepath in file_list
]
  File "remove_duplicates.py", line 244, in _read_capture_time
    reader = PILExifReader(filepath)
  File "c:\wamp\www\mapillary_tools\mapillary_tools\python\lib\exif_pil.py", lin
e 23, in __init__
    self._exif = self.get_exif_data(image)
  File "c:\wamp\www\mapillary_tools\mapillary_tools\python\lib\exif_pil.py", lin
e 31, in get_exif_data
    info = image._getexif()
  File "C:\users\julie\appdata\local\enthought\canopy\user\lib\site-packages\PIL
\JpegImagePlugin.py", line 381, in _getexif
    info.load(file)
  File "C:\users\julie\appdata\local\enthought\canopy\user\lib\site-packages\PIL
\TiffImagePlugin.py", line 382, in load
    raise IOError, "not enough data"
IOError: not enough data

c:\wamp\www\mapillary_tools\mapillary_tools\python>

**Comment by JulieMay** [comment]
Nevermind, figured out that although this project never specifies what version of Python needs to be installed pyexiv2 failed install because it only works with python 2.6 or lower and I'm running a 2.7.

The project really needs to state what version of Python it is using somewhere. 
In the meantime, the bug really should be 
"Deprecation warning

pyexiv2 is now deprecated in favour of GExiv2, a GObject-based wrapper around libexiv2. Thanks to GObject Introspection support, GExiv2 supports Python 2 and 3.

If your application uses pyexiv2, you might want to consider porting it over to GExiv2."

**Comment by ybkuang** [comment]
@JulieMay We will remove the dependency of pyexiv2 later. Thanks for reporting this!
