### ISSUE TITLE
Incorrect EXIF subsecond handling

### ISSUE THREAD

**Issue by MichaelVL** [mapillary/mapillary_tools#117]
In extract_capture_time() the sub-second timestamp is added to the DateTime value with:

+ datetime.timedelta(seconds=float(sub_sec)/1e6)

However, the EXIF standard states this field is ASCII and recording fraction of seconds, continuing with an example where fraction '0.130' is stored as the string '130'

Thus I would suggest that in extract_subsec() where the return value is:

  sub_sec = int(sub_sec)

is changed to something like:

  sub_sec = float('0.'+sub_sec)

and the division by 1e6 in extract_capture_time() to be removed.

**Comment by ybkuang** [comment]
@MichaelVL Thanks for reporting this. @kertase's pull request fixed this https://github.com/mapillary/mapillary_tools/pull/131.
