### ISSUE TITLE
sequence_split.py do not split in more sequences but only in subfolders

### ISSUE THREAD

**Issue by sorcrosc** [mapillary/mapillary_tools#120]
I expect this script to modify the SequenceUUID attribute to really split sequences but seems it only divide images in subfolders.
Maybe this the same request as #54

**Comment by mprins** [comment]
it's not supposed to be used with "app" images.

Not sure why you would want to change the SequenceUUID as the apps do this automatically?

**Comment by sorcrosc** [comment]
I use to review sequences in my computer to delete bad images. Sometimes there are several close each other so i would like to split the sequence to avoid having a big gap between two images. Like this here:
http://www.mapillary.com/map/search/43.679232363771604/12.74386418290058/14

What do you mean with "the apps do this automatically"? What app?

**Comment by sorcrosc** [comment]
Well, I'm closing this but I think a script to change sequence uuid in subfolders is useful.
In the meantime I put together this bash script. 
```
#!/bin/bash

exifkey=Exif.Image.ImageDescription
exiftag=MAPSequenceUUID


if [ -d "$1" ]; then
	seqdir=$1
else
        # DIRECTORY is the subdir containing jpgs
	echo "usage: ${0##*/} DIRECTORY"
	exit 1
fi

newhash=$(uuidgen)

for i in $seqdir/*.jpg; do
	[ -f "$i" ] && \
	exiv2 -M"set $exifkey $(exiv2 -g $exifkey -Pt $i | sed -r s/\"$exiftag\":\"[^\"]+\"/\"$exiftag\":\"$newhash\"/)" "$i"
done
```
