### ISSUE TITLE
Throttle upload speed

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_tools#122]
upload_with_authentication.py can saturate upstream bandwidth easily, causing problems with other programs. It would be good to have an option for maximum bandwidth.

**Comment by Skippern** [comment]
Also command line option for number of threads.

**Comment by andrewharvey** [comment]
could this be left to the user with something like `trickle`? https://linux.die.net/man/1/trickle

**Comment by jernejaMislej** [comment]
hi, sorry for the late reply here.
we are currently not planning to implement anything to support this in the tools directly, @andrewharvey suggestions seems as a good enough solution, therefore closing this for now
