### ISSUE TITLE
OS error: [Error 183] Cannot create a file when that file already exists on DONE

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_tools#123]
Hi,
I've just uploaded about 1600 photos using upload_with_authentication.py. Toward the end mycomputer went into sleep but as I woke it up the upload continued.

Once all was uploaded the below error was shown after I selected 'y'

Is my upload correct and 'closed'?

`[============================================================] 100.0% ... 0 imag===left.
Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.
Finalize upload? [y/n]: y
Upload a DONE file seb1204/f66a93ef-972d-4790-8ad3-b71b0c00dbee/ to indicate the  sequence is all uploaded and ready to submit.
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE
OS error: [Error 183] Cannot create a file when that file already exists on DONE

Traceback (most recent call last):
  File "C:\Python27\Scripts\mapillary_tools-master\python\upload_with_authentication.py", line 122, in <module>
    finalize_upload(params, auto_done=auto_done)`

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). If the DONE file exist, it will not attempt to create it again, so you should not have any more issues.
Hopefully usage will be smoother now, if not please let us know
