### ISSUE TITLE
Normalize and pre-set compass offset

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#127]
There should be an option to do the '''normalize sequence''' and '''set offset''' sequence edit options when uploading, a simple --normalize_sequence and --offset=nn would do greatly.

**Comment by utack** [comment]
This would be really useful  
My device has a compass that is a random number generator, and normalizing compass in the online editor plus waiting for approval is painfully complicated and slow

**Comment by ybkuang** [comment]
One can now use this script https://github.com/mapillary/mapillary_tools/blob/master/python/upload_with_preprocessing.py
```
python upload_with_preprocessing.py path_to_photos --interpolate_directions --offset_angle [angle_in_degree]
```
