### ISSUE TITLE
Consider the gpsTrack Exif Attribute when interpolating direction

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_tools#128]
While poking around with Garmin photo metadata over on [another issue](https://github.com/mapillary/mapillary_issues/issues/2114), I observed that Garmin Virb XEs pack an EXIF attribute called `gpsTrack`. I've written some documentation on the attribute and how it could be used in the photo interpolation procedure for Mapillary's python scripts.
### gpsTrack

This attribute, according to the [Exif RDF Schema](https://www.w3.org/2003/12/exif/) is

> The direction of GPS receiver movement. The range of values is from 0.00 to 359.99.

Here is that attribute on one of my photos:

![image](https://cloud.githubusercontent.com/assets/1827881/17236767/6403cac2-5519-11e6-8027-14cdaca35ce2.png)
### gpsImgDirection

The [interpolate_direction.py](https://github.com/mapillary/mapillary_tools/blob/master/python/interpolate_direction.py) script writes the related but notably different EXIF attribute, `gpsImgDirection`, which is

> The direction **of the image** when it was captured. The range of values is from 0.00 to 359.99.
### Experiment

I compared the interpolated direction from the script to the `gpsTrack` value for a right-side view photo that I took with a Garmin Virb XE. The difference between the interpolation and track direction is less than 1°, so not particularly significant in this _n=1_ experiment.

![image](https://cloud.githubusercontent.com/assets/1827881/17237109/83541f46-551c-11e6-948e-8a870d9fde5d.png)
### Conclusions

I would not suggest using the `gpsTrack` attribute directly, since the `gpsImgDirection` attribute considers the image direction, rather than just the GPS direction. This is important for cases where the camera is not facing the direction of movement, or if the camera is moving very slowly, as these would not yield the proper direction tag for Mapillary.

However, I do suggest that the [interpolate_direction.py](https://github.com/mapillary/mapillary_tools/blob/master/python/interpolate_direction.py) first check for this `gpsTrack` attribute, and then use the angle variable that the user enters to make the translation to `gpsImgDirection`. This way, the camera data is controlling the direction, rather then an assumption that the next photo location in a sequence is the direction in which the previous photo was facing.

**Comment by millenbop** [comment]
Just wanted to chime in on how it works in the iOS app. We use the `track` from the Garmins for direction, but we offset it by the direction set by the user (+45, +90 etc).

**Comment by bhousel** [comment]
Cool, looks related to https://github.com/mapillary/mapillary_issues/issues/2016
I think Mapillary is planning to support these exif tags in their server-side processing.  In that situation, doesn't running `interpolate_direction.py` become unnecessary?

**Comment by talllguy** [comment]
Thanks for sharing those comments from @ybkuang, that does sounds like an important update. The only thing about server-side processing these, is that the direction the camera is facing is unrelated to the track direction. If there was a way the user could just specify the angle on the UI, I think that would solve it.

#2129 relevant

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
