### ISSUE TITLE
Constant position offset.

### ISSUE THREAD

**Issue by golserma** [mapillary/mapillary_tools#138]
My camera is mounted at the end of mi bicycle the GPS Unit is mounted in Front of the bicycle.
There should be a feature to alter the position by the distance of the units. 

Example:

Distance between GPS Device and Camera is 0.8 meters. offset bearing is 180° calculate the angle and move the point 0.8 meters.

**Comment by ybkuang** [comment]
@golserma We can add the option of offsetting the positions in meters. But we need to bear in mind that most of the GPS units have larger errors than 1 meter.

**Comment by ptpt** [comment]
Users can update the coodinates in the image description file (in JSON) before uploading https://github.com/mapillary/mapillary_tools#image-description
