### ISSUE TITLE
upload.py unable to handle connection closed

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_tools#14]
While uploading a huge batch of images, there is a problem with the connection to amazon and it closes(possible timeout on amazon's part?) but the script crashes and fails to resume the upload
![capture](https://cloud.githubusercontent.com/assets/498547/3861507/de6e7c0c-1f2f-11e4-84c3-6f628ff509dd.PNG)

also get this error:
![capture2](https://cloud.githubusercontent.com/assets/498547/3865759/80084174-1fa8-11e4-8f66-14882cde0492.PNG)

**Comment by Skippern** [comment]
I also get this when I get "Connection reset by peer", I think it throws and exception that should be handled as "failed upload".

**Comment by jesolem** [comment]
We added a few more checks since this. Closing.
