### ISSUE TITLE
Check `--duplicate-distance` param on `upload_with_preprocessing.py`

### ISSUE THREAD

**Issue by bhousel** [mapillary/mapillary_tools#145]
Sorry I don't have more information yet, but just flagging here for me to check the `--duplicate-distance` culling that happens in `upload_with_preprocessing.py`, because I'm fairly sure there is a subtle bug in there that is causing points to be culled incorrectly based on their calculated distance.  I'm definitely seeing a lot of gaps in my traces that don't make much sense.

For example, I usually run with `--duplicate-distance 4` to exclude points when stopped but keep most of the ones when driving.  It's probably excluding points that are too close to the "previous" point, but it should instead exclude points that are too close to the "last kept" point.

<img width="315" alt="screenshot 2016-11-04 13 03 33" src="https://cloud.githubusercontent.com/assets/38784/20014902/6c9831f0-a28f-11e6-8e78-9ef33c80c896.png">

[link to above sequence](https://www.mapillary.com/app/user/bhousel?lat=37.54905601365388&lng=-122.26211815349532&z=18.98040110042474&pKey=LX8WD8fDq5RCIhhyNH7m4w&focus=photo)

**Comment by ybkuang** [comment]
@bhousel What the capture interval between the photos? It looks like it is 1 image/second? I can see that you have gaps in your sequences. And I looked at some of them, the two consecutive images usually have gap with 1 second. For instance here https://www.mapillary.com/app/user/bhousel?lat=37.55129305555556&lng=-122.2613397222222&z=17&pKey=ECI1rqT4e-xhwPqnVX5SAg&focus=photo. So the gap might not be caused by the duplicate removal.

**Comment by bhousel** [comment]
Hey @ybkuang I did some more analysis and it does look like the gaps are caused by something our cameras are doing, not something the script is doing..

Not the same sequence as above, but a different one:
```
...
1478882307000:  front/DSC04380.JPG  left/DSC07823.JPG  right/DSC06347.JPG  back/DSC00492.JPG
1478882308000:  front/DSC04381.JPG  left/DSC07824.JPG  right/DSC06348.JPG  back/DSC00493.JPG
1478882309000:                      left/DSC07825.JPG                      back/DSC00494.JPG
1478882310000:                      left/DSC07826.JPG                      back/DSC00495.JPG
1478882311000:  front/DSC04382.JPG  left/DSC07827.JPG  right/DSC06349.JPG  back/DSC00496.JPG
1478882312000:  front/DSC04383.JPG  left/DSC07828.JPG  right/DSC06350.JPG  back/DSC00497.JPG
...
```
