### ISSUE TITLE
geotag_video with NMEA log: local variable 'date' referenced before assignment

### ISSUE THREAD

**Issue by JanisE** [mapillary/mapillary_tools#156]
When running `geotag_video.py`, if using an NMEA log, I get the following error. If I convert the log to GPX (`gpsbabel -i nmea -f ./17051303.LOG.nmea -o gpx -F ./17051303.LOG.gpx`), then the geo-tagged images are generated all right.

```
$ python geotag_video.py --image_path here_be_pictures --sample_interval 3 --gps_trace 17051303.LOG.nmea MAH01163.MP4
Traceback (most recent call last):
  File "geotag_video.py", line 92, in <module>
    points = parse_gps_trace(gps_trace_file, local_time)
  File "geotag_video.py", line 51, in parse_gps_trace
    points = get_lat_lon_time_from_nmea(gps_trace_file, local_time)
  File "/home/janis/Projekti/mapillary/mapillary_tools/python/lib/gps_parser.py", line 71, in get_lat_lon_time_from_nmea
    timestamp = datetime.datetime.combine(date, data.timestamp)
UnboundLocalError: local variable 'date' referenced before assignment
```

The NMEA log: [17051303.LOG.nmea.txt](https://github.com/mapillary/mapillary_tools/files/998873/17051303.LOG.nmea.txt)

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
