### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by yarazi** [mapillary/mapillary_tools#157]
Hello all,

Is there a mnaual that shows how to install, config and run the mapillary_tools.

Thanks
yaniv

@ybkuang

**Comment by pbb72** [comment]
There is an old tutorial on https://forum.mapillary.com/t/running-the-python-scripts/130, but I agree that the readme.md should be updated to include more thorough instructions.

**Comment by ybkuang** [comment]
@yarazi We will work on refining the documentation of the tools. 

@pbb72 Thanks for helping with the pointing to the tutorial.

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
