### ISSUE TITLE
Pyexiv2 not found in Windows

### ISSUE THREAD

**Issue by cbeddow** [mapillary/mapillary_tools#158]
### Basic information
* Platform: `window 10 64 bit`
* Version: Inline image 1
* System/Python: Python 2.7.13

### Steps to reproduce behavior

1. Install python 2.7 ( pip, if not install )
2. pip install -r requirements.txt
3. move to D:\yaniv\mapillary\mapillary_tools-master\python
4. run python geotag_from_gpx.py

### Expected behavior
A mapillary message of some kind, regarding user no specified or anything

### Actual behavior

D:\yaniv\mapillary\mapillary_tools-master\python>python geotag_from_gpx.py
Traceback (most recent call last):
  File "geotag_from_gpx.py", line 6, in <module>
    import pyexiv2
ImportError: No module named pyexiv2

D:\yaniv\mapillary\mapillary_tools-master\python>

**Comment by pbb72** [comment]
Sorry, maybe a very ignorant question from me, but did you install pyexiv2 (http://tilloy.net/dev/pyexiv2/download.html)?

**Comment by cbeddow** [comment]
Yes, this was installed by the user doing this (not me reporting the issue
for myself). Tried the bindings, pip, but seems to end up as some sort of
issue with a DLL. We put him on the non-pyexiv2 version and it's working.
This may be a not enough information bug.

**Comment by jernejaMislej** [comment]
closing this since pyexiv2 is not used anymore
