### ISSUE TITLE
Mention required Python version

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_tools#159]
The README.md file in the Python directory nicely lists the dependencies for these scripts. However, it does not say a word about which Python version is required.

There's two major versions of Python, version 2 (first release 17 years ago, that's ancient history in the digital world) and version 3 (first release 7 years ago, also a good time ago).

The Python website speaks almost exclusively of version 3, but offers version 2 as an "old version" download.

Speaking to people who know Python, it also takes them effort to find out which Python version is required by a certain script. The general advice is to just install both versions of Python, and see in which version the script doesn't crash.

This, of course, is not something you want to advice to Mapillary users who want to use the scripts.

After lots of studying, I find out that the required `pyexiv2` library only supports Python 2.

It should not have been this difficult. Just mention Python 2 on top of the list of requirements! (This may be deadly obvious for Python experts of Mac/Linux users, but it took a lot of time for this Windows Python noob to figure out...)

**Comment by Lwnzhn** [comment]
PLEASE, port it to python3 instead/on top of that. Modern distros abondonend python2 completly, it's a dead end. That would also be a reason for some refactoringing to object oriented and more reuse between those tools. Glad to help if you decide that way.

**Comment by SanderH** [comment]
[py3exiv2](https://pypi.python.org/pypi/py3exiv2/0.1.0) seems availble.
So in theory it shouldn't be too difficult to switch to Python 3 using this instead of pyexiv2.

**Comment by pbb72** [comment]
Still, just mentioning one single line in README.md about the Python requirement, should be even easier to implement.

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). Python requirement is now stated in the README and we are planning to support Python3 in the next releases.
Hopefully usage will be smoother now, if not please let us know

**Comment by pbb72** [comment]
The readme states "python>2.7". This does not help much!

Firstly, 3.0 is clearly greater than 2.7. Maybe this is obvious for Python buffs, but noobs like me will read this as "3.0 is supported".
Secondly, it says "greater than", not "greater than or equal to". Is 2.7.15 greater than 2.7? Not very clear, but 2.7.0 is definitely NOT greater than 2.7.

(And as we're nitpicking, "Python" is a proper name and should be capitalised...)

**Comment by jernejaMislej** [comment]
yes, sorry about that, I will fix it. Thank you for the feedback.

**Comment by richlv** [comment]
It now says Python version must be "=" to 2.7 - I overlooked that at first. An explicit line in the requirements would have been useful.

As for the instructions, on any non-obsolete distribution the "pip" commands likely have to be "pip2", as otherwise you'll end up with stuff installed for the wrong Python version.
