### ISSUE TITLE
add_mapillary_tag_from_exif.py: SyntaxError

### ISSUE THREAD

**Issue by scaidermern** [mapillary/mapillary_tools#161]
add_mapillary_tag_from_exif.py broke during commit 4c09e432d84b3bdbb943f7d5c62f4a6ff04f1f91:

```
  File "./add_mapillary_tag_from_exif.py", line 54
    Fetch authetication info from env
                      ^
SyntaxError: invalid syntax
```

Fix is at https://github.com/mapillary/mapillary_tools/pull/160.

**Comment by ybkuang** [comment]
Thanks @scaidermern for the fix. Closing this.
