### ISSUE TITLE
remove_duplicates.py --min_duplicates has no effect

### ISSUE THREAD

**Issue by wladich** [mapillary/mapillary_tools#162]
Value assigned to var min_duplicates in lines 308 and 388  is never used.

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md).
Hopefully usage will be smoother now, if not please let us know
