### ISSUE TITLE
upload.py: UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by scaidermern** [mapillary/mapillary_tools#164]
During upload I experienced a network error. upload.py wasn't able to handle it correctly:

```
URL error: <urlopen error [Errno 104] Connection reset by peer> on greatest_photo_ever.jpg
ExceptionNow  in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/dtrump/mapillary_tools/python/lib/uploader.py", line 53, in run
    upload_file(filepath, **self.params)
  File "/home/dtrump/mapillary_tools/python/lib/uploader.py", line 292, in upload_file
    if response is not None:
UnboundLocalError: local variable 'response' referenced before assignment
```

Now upload.py just hangs and doesn't finish. Looks like `response` should have been declared as `None` before calling `urllib2.Request()`?

**Comment by andrewharvey** [comment]
I've run into this issue exactly. As a user it's confusing what it means and what I should do about it.

**Comment by ybkuang** [comment]
https://github.com/mapillary/mapillary_tools/commit/ae8cb4bfad12cdba4810b4639b3cf610ac982be6 should fix this. Thanks for reporting.
