### ISSUE TITLE
geotag_from_gpx.py division by zero

### ISSUE THREAD

**Issue by zzptichka** [mapillary/mapillary_tools#165]
Whenever you have several photos shot while GPS was auto-paused you get this:

> Warning: Time t not in scope of gpx file by 1.0 seconds, extrapolating...
Traceback (most recent call last):
  File "geotag_from_gpx.py", line 182, in <module>
    add_exif_using_timestamp(filepath, filetime, gpx, args.time_offset, args.bearing_offset)
  File "geotag_from_gpx.py", line 45, in add_exif_using_timestamp
    lat, lon, bearing, elevation = interpolate_lat_lon(points, t)
  File "geo.py", line 195, in interpolate_lat_lon
    lat = (before[1]*dt_after + after[1]*dt_before) / (dt_before + dt_after)
ZeroDivisionError: float division by zero

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
