### ISSUE TITLE
support webp uploads

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#166]
A quick scan of the uploader code https://github.com/mapillary/mapillary_tools/blob/master/python/lib/sequence.py#L67 it seems only .jpg images are supported.

It could be nice to support webp ulpoads. Although it takes more CPU time on the client to create them, for me they are about 1/5th the size for the same quality and would make uploading much faster on slow connections.

I'm using this to keep the exif tags `cwebp -metadata all -q 80 image.jpg -o image.webp`

Question, are webp uploads accepted on the server? Or is this just a limitation in the uploader?

https://github.com/ianare/exif-py/issues/71 might need to be done to support this in the current scripts?

**Comment by ybkuang** [comment]
@andrewharvey Thanks for the suggestion. We will need to check if our server is supporting webp or not. On the other hand, we will prefer keeping the format consistent in our system. Otherwise, it will take considerable amount of time for us to maintain the system.

**Comment by jernejaMislej** [comment]
hi, thank you for the suggestion, currently we are not planning to implement support for webp images in the near future. We will notify you when we decide to support this.
