### ISSUE TITLE
remove_duplicates.py: Silent fail when EXIF orientation not set

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_tools#167]
I noticed that `remove_duplicates.py` silently fails when the EXIF tag for orientation is not set. Even with the verbose option `-v` the repeated message

    , No orientation => False

didn't make it clear for me at first.

After some digging I discovered that the used library is not able to read some (all?) EXIF tags if the orientation is not given, which might be a bug in the library (`PILExifReader`).

I see different ways how to handle this and spare the frustration for future users:

1. Print an understandable error message which describes the problem. (Even if `-v` was not set.) As a remedy recommend something like https://github.com/ltog/photomapping-utils/blob/master/mapillary/set_default_orientation.sh

2. If it's a bug in `PILExifReader`, ask the author(s) to fix it. (Maybe it's already fixed but I haven't got the newest version.)

3. Use another library to read the EXIF data. Here is another way to do it, which works for pictures without the orientation tag:

```python
#!/usr/bin/python

from PIL import Image
from PIL.ExifTags import TAGS
 
ret = {}
i = Image.open("/path/to/picture.jpg")
info = i._getexif()
for tag, value in info.items():
    decoded = TAGS.get(tag, tag)
    ret[decoded] = value

print(ret)
```

Furthermore, I had problems uploading pictures without orientation before when using `upload_with_authentication.py` so there might be other scripts which need checking. I didn't write a bug report for that case.

**Comment by ybkuang** [comment]
Thanks for reporting. We will see if we can reuse another exif library for this. @ltog

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have replaced the EXIF editing library which is now more robust.
We have also released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md).
Not having image orientation set should not be a problem anymore.
Hopefully usage will be smoother now, if not please let us know
