### ISSUE TITLE
geotag_from_gpx.py: AttributeError: 'str' object has no attribute 'as_tuple'

### ISSUE THREAD

**Issue by sorcrosc** [mapillary/mapillary_tools#173]
I'm trying to geotag images taken from Mapillary app in my phone to upload them with upload_with_authentication.py. See my comment in https://github.com/mapillary/mapillary_tools/issues/153#issuecomment-317284691
Here below is what i get. This also causes the first image in the directory to be erased (4 bites long)

```
$ python2 ~/script/mapillary_tools/python/geotag_from_gpx.py 2017_07_09_16_48_18_468 2017_07_09_16_48_18_468/CAMERA2_0_2017_07_09_16_48_18_473.gpx
Your local timezone is 2017-07-29 23:23:10 CEST, if this is not correct, your geotags will be wrong.
===
Starting geotagging of 11 images using 2017_07_09_16_48_18_468/CAMERA2_0_2017_07_09_16_48_18_473.gpx.
===
Traceback (most recent call last):
  File "/home/lo/script/mapillary_tools/python/geotag_from_gpx.py", line 140, in <module>
    add_exif_using_timestamp(filepath, filetime, gpx, args.time_offset, args.bearing_offset)
  File "/home/lo/script/mapillary_tools/python/geotag_from_gpx.py", line 48, in add_exif_using_timestamp
    metadata.write()
  File "/home/lo/script/mapillary_tools/python/lib/exifedit.py", line 199, in write
    self.ef.writeFile(filename)
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 1036, in writeFile
    self.writeFd(output)
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 1042, in writeFd
    segment.write(output)
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 139, in write
    data = self.get_data()
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 876, in get_data
    ifd == self.ifds[-1])
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 448, in getdata
    sub_data, next_offset = the_data.getdata(e, data_offset, 1)
  File "/home/lo/script/mapillary_tools/python/lib/pexif.py", line 482, in getdata
    actual_data += pack(e + t, *the_data[i].as_tuple())
AttributeError: 'str' object has no attribute 'as_tuple'
```

**Comment by ybkuang** [comment]
@sorcrosc can you forward one of the images in the folder to yubin [at] mapillary [dot] com? Thanks.

**Comment by sorcrosc** [comment]
Done

**Comment by peterneubauer** [comment]
I have the same problem, attaching 2 images and the GPX.
![20170811_190038](https://user-images.githubusercontent.com/11977/29233848-aaecb232-7ef3-11e7-8ee0-a2907df4857c.jpg)
![20170811_190040](https://user-images.githubusercontent.com/11977/29233849-ab184fe6-7ef3-11e7-9203-97a2c774246e.jpg)
[2017-08-11_19-00_Fri.gpx.zip](https://github.com/mapillary/mapillary_tools/files/1219208/2017-08-11_19-00_Fri.gpx.zip)

**Comment by peterneubauer** [comment]
Here is another one - from the Google Nexus 5X with the corresponding GPX, guess all the files are like that

[CAMERA2_0_2017_08_12_15_57_55_411_+0200.gpx.zip](https://github.com/mapillary/mapillary_tools/files/1219912/CAMERA2_0_2017_08_12_15_57_55_411_.0200.gpx.zip)
![2017_08_12_15_59_01_766_ 0200](https://user-images.githubusercontent.com/11977/29242471-1bee6378-7f8e-11e7-9d45-72f8fcf66e03.jpg)
![2017_08_12_15_59_02_764_ 0200](https://user-images.githubusercontent.com/11977/29242472-1bf262ca-7f8e-11e7-879f-925bfb78f419.jpg)

**Comment by peterneubauer** [comment]
After some debugging, at least in my case somewhere there is type of the tag is `Rational`, but instead of a Rational number, the actual data in https://github.com/mapillary/mapillary_tools/blob/master/python/lib/pexif.py#L482 is of type string, and is `\x00`.

The question is if the data is wrongly read from the EXIF tags, since `exiftool` and other image viewers don't have problems with these images? @ybkuang do you know? We probably need to debug what tag that is?

**Comment by peterneubauer** [comment]
So, after some investigation, it turns out that the LG and some phones are writing the `GPSAltitudeRef` as Rational or String `\x00` instead of `0` byte, see http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf. For images created with the Android app, this is now corrected to overwrite the AltitudeRef always with a byte=0, however for the LG we need to robustify the parsing in the python lib, will see what I can do.

**Comment by sorcrosc** [comment]
@peterneubauer thanks!
My phone is an LG G4

**Comment by sp4rkie** [comment]
I just tried to import the data of  https://github.com/mapillary/mapillary_tools/issues/173#issuecomment-321992118 with josm and geotagged images. There were no unexpected results. Obviously they got the issue  already fixed :-)

**Comment by peterneubauer** [comment]
So, for the images that are not ok, the best way I have found to fix this is to simply remove the offending taga with `exiftool` which is a bit more fogiving:


    exiftool -GPSAltitudeRef= -d "OUTUT_FOLDER" "-directory<datetimeoriginal" PATH_TO_THE_IMAGES/*  

After that, the script should work.

**Comment by ybkuang** [comment]
Thanks for investigating @peterneubauer. Indeed, the pexif lib is handling that well with unexpected bytes. We will see how we can fix that (or use another exif edit lib)

**Comment by peterneubauer** [comment]
We could use the same technique as in we now do in Android - before doing any writing, we remove the tag with some means, maybe `exiftool` or so in order to make the data clean?

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have replaced the EXIF editing library which is now able to handle these cases, ie it will automatically skip any EXIF tags that do not have the right type.
We have also released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md).
Hopefully it will make usage more smoother, if not please let us know
