### ISSUE TITLE
allow to tag app images on the computer

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#174]
background : had a lot of of images taken, needed space on the phone - transferred them to the computer without adding the tags. then transferred them back to the phone, tagged. copied to the computer again - but the tags were missing for most of them (~ 7k), only a few hundred images had the tags.
copied images to the phone again, but the upload from the phone just deleted the images.

not sure what exactly was the cause for this, but it would be much safer (and faster) if there was a script to tag the images on the computer - it would be much faster and less likely to destroy that many images.

**Comment by ybkuang** [comment]
@richlv Are you using Android or iOS? 

Making scripts for upload images is on our to-do list.

**Comment by richlv** [comment]
primarily ios, although having that for android would be useful every now and then, too.
of course, if the capture process can be modified to include all the needed tags right away without writing the image twice, that would mostly eliminate the need for the tagging script.

**Comment by ybkuang** [comment]
@richlv Thanks for the feedback. 

So the issue of image being deleted after you copied them back to the phone is related to iOS?

**Comment by richlv** [comment]
yep. there were at least two large batches (around 7000 and around 10000 images) that i added exif tags and copied them to the computer - but there were no tags on the images. copying them back to the phone did not help, as apparently the info to tag them had already been removed.

**Comment by ybkuang** [comment]
@richlv there are json files with meta data which are stored along side with the images. When you first transferred imags out to your computer, did you also delete the images on the phone?

**Comment by richlv** [comment]
i was aware of the json files, so i did not touch them at any point.
but when i transferred the images, i did delete them from the phone - although i did that through itunes, not from the app

**Comment by jernejaMislej** [comment]
closing this since no longer active
