### ISSUE TITLE
sequence_split.py arguments reversed in README

### ISSUE THREAD

**Issue by sorcrosc** [mapillary/mapillary_tools#180]
README says sequence_split.py command is:

`python sequence_split.py path-to-images/ cutoff_distance [cutoff_time]`

but `cutoff_distance` and `cutoff_time` are in reversed order

**Comment by jernejaMislej** [comment]
hi, we have released a new version of the tools with improved instructions and usage examples, more information in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md)
Hopefully usage will be easier now, if not, please let us know
