### ISSUE TITLE
port to py3

### ISSUE THREAD

**Issue by Lwnzhn** [mapillary/mapillary_tools#181]
It's the better language, it's the future. Py2 is eol.

**Comment by ybkuang** [comment]
@Lwnzhn Thanks for the suggestion. We will take a look into this.

**Comment by jernejaMislej** [comment]
hi, just letting you know we have released a new version of the tools and are planning to support python3 in the next releases. Please try to use the new tools, the instructions and details are in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md) and let me know if you have any more suggestions
