### ISSUE TITLE
Errno 10054

### ISSUE THREAD

**Issue by Lwnzhn** [mapillary/mapillary_tools#182]
I get an error timout for every file I upload.py:
Uploading 202 images with valid mapillary tags (Skipping 0)
URL error: <urlopen error [Errno 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen> on 2017_08_13_13_03_31_832.jpg

alternatively:
URL error: <urlopen error [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen> on 2017_08_13_13_03_49_193.jpg

**Comment by jernejaMislej** [comment]
hi, sorry for not getting back to you on this.
This seem like a Windows specific network error, are you still having issues with this?

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
