### ISSUE TITLE
iOS postprocessing leads to deletion at upload of all pics

### ISSUE THREAD

**Issue by Lwnzhn** [mapillary/mapillary_tools#183]
1. take a sequence
2. forget to press postprocessing in app
3. move folder and 'camera' folder to PC
4. postprocessing, delete 50 bad images(but not coressponding files in camera, because srsly?)
4a. try uploading using these scripts for some nights
5. move folder from PC back to iOS
6. push postprocessing button ->runs happily as expected
7. push upload -> finished in 30secs, says OK, but nothing uploaded.. all pics deleted

**Comment by ybkuang** [comment]
@millenbop can you help take a look at this?

**Comment by Lwnzhn** [comment]
You are lightning fast, respect.
:Daniel

17. Aug 2017 23:42 von notifications@github.com:

**Comment by millenbop** [comment]
Ouch that doesn't sound good at all. I'll look into it today. Thanks for reporting.

**Comment by millenbop** [comment]
Ok fixed now. So sorry about this! Uploading update to Apple now.

**Comment by Lwnzhn** [comment]
HERO!!
tx,
Daniel



18. Aug. 2017, 14:06 von notifications@github.com:
