### ISSUE TITLE
interpolate_direction.py writes unreadable EXIF data (test data included)

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_tools#184]
# Summary

The latest version of `interpolate_direction.py` writes EXIF data that is not readable by other applications (JOSM in my case).

# Details

For the attached test data, when processed with `interpolate_direction.py`, `exiftool` prints one of the two warnings for every processed image:

Variant A:

    Warning                         : GPS pointer references previous InteropIFD directory

Variant B:

    Warning                         : Bad InteropIFD directory

# Impact

Variant A: JOSM can *not* read GPS position but can display the image.

Variant B: JOSM can read GPS position and display the image, but the warning from exiftool still indicates the presence of a problem.

# Reproduction

    python interpolate_direction.py --offset_angle 270 /path/to/files

Test data: [interpolate_direction_testdata.zip](https://github.com/mapillary/mapillary_tools/files/1236991/interpolate_direction_testdata.zip)

**Comment by ybkuang** [comment]
@ltog Thanks for reporting. I will take a look and seems that it is related to the exif library we are using. Will look for a fix for that.

**Comment by jernejaMislej** [comment]
@ltog hi, sorry for not getting back to you on this issue.
we have replaced the exif library, which is now able to handle images like yours, so hopefully you will not experience any more issues.

note that the `interpolate_direction.py` script is becoming obsolete and it is not maintained. 
we are working on an improved version of the mapillary import tools, where direction interpolation will be available through sequence processing 

if you have any more problems with your imports please get back to us, otherwise I will close this issue

**Comment by ltog** [comment]
@jernejaMislej : Thanks for getting back to me.

If I reconstruct correctly, my mentioned problem occurred AFTER you changed the exif library: I created the issue on August 2017, but the exif library was changed on July 2017 according to https://github.com/mapillary/mapillary_tools/commits/master/python/interpolate_direction.py

Where will we find the new version of the Mapillary import tools?

**Comment by jernejaMislej** [comment]
@ltog hi,
there was another exif lib change done a few months ago, the changes for that are already available on the master branch

as for the new version of the Mapillary import tools, it will be most likely be available here. 
We will provide more information when it is released.

**Comment by ltog** [comment]
@jernejaMislej : 

> there was another exif lib change done a few months ago, the changes for that are already available on the master branch

Ok, but shouldn't a change for this be visible in https://github.com/mapillary/mapillary_tools/commits/master/python/interpolate_direction.py ?

**Comment by jernejaMislej** [comment]
@ltog 
the changes were made to the exifedit lib which is imported in the `interpolate_direction.py`, therefore no direct changes were made to that script

**Comment by ltog** [comment]
@jernejaMislej : Ok, now I'm getting it. Thanks for the update. I think the issue can be closed.
