### ISSUE TITLE
--orientation not working

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_tools#186]
Uploaded sequence `1P5M5aCXzwkcWWw5nGKReQ` with the script using `--orientation 180` but in map is still wrongly rotated.

**Comment by ybkuang** [comment]
@Alessandro-Barbieri The orientation value has to be in `[1, 3, 6, 8]` see more details [here](http://sylvana.net/jpegcrop/exif_orientation.html). To rotate the image 180 degree, the corresponding orientation tag should be 3. 

I will add better documentation or use more human readable value for the option. Sorry about the confusion.

**Comment by Alessandro-Barbieri** [comment]
https://github.com/mapillary/mapillary_tools/blob/master/python/update_tags.py#L48 is this wrong then?

**Comment by ybkuang** [comment]
Yes. It has to be 1, 3, 6, 8 accordingly.

**Comment by Alessandro-Barbieri** [comment]
What's the purpose of this https://github.com/mapillary/mapillary_tools/blob/master/python/update_tags.py#L62 then?

**Comment by ybkuang** [comment]
@Alessandro-Barbieri will fix that. sorry for the inconveniences.

**Comment by Alessandro-Barbieri** [comment]
Exif metadata of a processed image:
`Caption {"MAPCameraRotation": "90", "MAPOrientation": 6}`
Are they correct?

**Comment by Alessandro-Barbieri** [comment]
Tomorrow I want to upload 10 GiB of images, having this fixed would help me not to manually search sequences after upload and the requesting rotation with the Google form

**Comment by ybkuang** [comment]
@Alessandro-Barbieri 
Sorry for getting back to you late. Which script were you using to upload the photos? Is it `upload_with_preprocessing.py`? As far as I can see, the update_tags.py is correct given #L62.

**Comment by Alessandro-Barbieri** [comment]
🤔 I re tried with upload_with_preprocessing.py and it's working ...

**Comment by ybkuang** [comment]
@Alessandro-Barbieri can you share one of the latest sequence with me? I would like to double check.

**Comment by Alessandro-Barbieri** [comment]
https://www.mapillary.com/map/im/ejRAoeTpevwdmqKP6JmnDw latest sequence, still not working

**Comment by ybkuang** [comment]
@Alessandro-Barbieri can you tell me the script you use to upload? If you are using upload_with_preprocessing.py it will not recognize the tag --orientation 180 properly. I thought that you were using update_tags.py.

**Comment by Alessandro-Barbieri** [comment]
I always used upload_with_preprocessing.py, worked only for this sequence https://www.mapillary.com/map/im/K9Bp7jazxzZXU4smG18Qxg . What can I do to fix the script?

**Comment by ybkuang** [comment]
working on a fix for you. sorry for the inconveniences. @Alessandro-Barbieri

**Comment by ybkuang** [comment]
@Alessandro-Barbieri I updated the script now. you can try again.

**Comment by ybkuang** [comment]
@Alessandro-Barbieri is it still failing for you (per you comments on the `update_tags.py`)?

**Comment by Alessandro-Barbieri** [comment]
I had a bunch of images rotated to right, run the script with `--orientation 270` but the images are now rotated to the left

**Comment by ybkuang** [comment]
@Alessandro-Barbieri OK. Thanks for the information.  It is related to this issue https://github.com/mapillary/mapillary_tools/issues/202. We will try to prioritize working on a fix for it.  

BTW, Are your images captured with a phone or an action camera?

**Comment by Alessandro-Barbieri** [comment]
With a phone: Samsung duos GT-S6106 with android 2.3.6 rooted using the app Tina Time Lapse

**Comment by jernejaMislej** [comment]
hi @Alessandro-Barbieri , sorry for not getting back earlier. is this issue still open for you? (for those particular images)

**Comment by jernejaMislej** [comment]
hi please install the latest version of mapillary tools and open a new issue if any problems. I am closing this one...
