### ISSUE TITLE
Error in pexif

### ISSUE THREAD

**Issue by ybkuang** [mapillary/mapillary_tools#189]
Traceback (most recent call last):
File "C:\Python27\Scripts\mapillary_tools-master\python\add_mapillary_tag_from
_exif.py", line 67, in 
MAPILLARY_USERNAME, MAPILLARY_EMAIL, None, upload_token, sequence_uuid)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\exifedit.py", line
102, in create_mapillary_description
metadata = ExifEdit(filename)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\exifedit.py", line
164, in init
self.ef = JpegFile.fromFile(filename)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 95
4, in fromFile
return JpegFile(f, filename=filename, mode=mode)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 10
17, in init
attempt = segment_class(mark, input, data, self.mode)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 81
0, in init
DefaultSegment.init(self, marker, fd, data, mode)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 12
5, in init
self.parse_data(data)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 85
6, in parse_data
ifd = IfdThumbnail(self.e, offset, self, self.mode, tiff_data)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 42
7, in init
self.ifd_handler(data)
File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 78
1, in ifd_handler
raise JpegFile.InvalidFile("Thumbnail doesn't have an offset "
lib.pexif.InvalidFile: Thumbnail doesn't have an offset and/or size

https://github.com/mapillary/mapillary_issues/issues/2704#issuecomment-328048499

**Comment by ybkuang** [comment]
@kaitu does it happen to all folders or only one particular folder of images?

**Comment by kaitu** [comment]
To all of the folders I tried since the error emerged.

**Comment by ybkuang** [comment]
@kaitu are there any thumbnail images in the folder?

**Comment by kaitu** [comment]
I don't think so, nothing which appears in the folder file list anyway.  I'm on windows 7, and I haven't changed anything in my system since the script started giving errors (but updating the mapillary tools to latest version, when I the errors had already started to appear).

**Comment by ybkuang** [comment]
@kaitu Thanks for the details. I will do a test here as well to check.

**Comment by kaitu** [comment]
Only the images taken with the smartphone started to give problems. Here is a sample:
![img_20170827_133932](https://user-images.githubusercontent.com/5104672/30216306-deb92e04-94b2-11e7-804e-d802f70ce3ee.jpg)

The images shooted with the 360 camera are still processed flawlessly.

**Comment by ulikoehler** [comment]
I have encountered somewhat similar error messages, when at least one of the images in the folder was damaged (i.e. "corrupt"). I've solved this issue by  manually looking through the images and deleting the one or two corrupted files. You can identify them as a large portion of the image is displayed in gray.

However, in this case it seems unlikely to be the case as it occurs for multiple folders, if I understood correctly.

**Comment by kaitu** [comment]
Yes, it seems a problem with the script, not with the images. I tried to process old photos which I know I had already processed successfully with the add_mapillary_tag_from_exif.py, and now I get the same error.

**Comment by ybkuang** [comment]
Thanks @kaitu for the extra information and data. I will take a look.

**Comment by ybkuang** [comment]
@kaitu there is an issue with the exif parser. I did a hot fix for it now, can you try? We will look into other exif library options later as other users were having issue with the parser as well.

**Comment by kaitu** [comment]
Excellent, it's working now. 
Thanks for the quick fix!

**Comment by ybkuang** [comment]
``
