### ISSUE TITLE
Extrapolating sequence photos positions

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_tools#193]
I've shot many photos in tunnels recently and I wonder whether it's possible to extrapolate positions of these photos using this tools set. It can be done with OSRM's match API - https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match

**Comment by fgouget** [comment]
If you have a GPX file adding the following options to the process step should do what you want: 
    --advanced --geotag_source "gpx" --geotag_source_path path/to/yourgpxfile.gpx

You may want to add --interpolate_directions too.

**Comment by ptpt** [comment]
This is not supported unfortunately.
