### ISSUE TITLE
piexif crashes if exif corrupted

### ISSUE THREAD

**Issue by jernejaMislej** [mapillary/mapillary_tools#201]
###About

[https://pypi.python.org/pypi/piexif](url) crashes if the exif bytes per tag are not representing the right format

###Notes

- Solution candidates 
 A.) Keep only the tags we need and make sure that they are written in the right format(we might loose valuable information and for a subset of tags we will need to know their corresponding required format and all the possible wrong value formats that can occur)
 B.) Apply some sort of exif repair that will go over each tag and convert it to the right format(might require a lot of work to cover all the possible tags, their corresponding required format and all the possible wrong value formats that can occur)

- piexif has strict conditions when dumping the exif data into bytes to be written to the image.
If an image has no exif, we don't have a problem, as we make sure that the exif tags we write have the value in the right format.
But if we modify an existing exif, that has certain tag values in the wrong format, tags which we don't overwrite with our own methods, we will end up trying to dump incorrect format values into bytes and piexif will crash.

**Comment by jernejaMislej** [comment]
https://github.com/hMatoba/Piexif/blob/master/piexif/_exif.py

here are all the formats, accessible through piexif.TAGS['Image'], where one could loop through all the tags, read the type and force the value in that type.

**Comment by jernejaMislej** [comment]
might help to just ask the piexif guy if he has any suggestions, he must have experienced this issue already

**Comment by ybkuang** [comment]
yes. Lets open an issue and ask there.

**Comment by jernejaMislej** [comment]
the author has responded really quickly and started doing something on the dev branch, refactoring the _dump script and adding an option to ignore the wrong format, i ll have a closer look and test what he did tomorrow and pause any quick fixes on our side, since the author might fix it before

**Comment by jernejaMislej** [comment]
the issue is fixed to the point that the exif can be loaded and written back, I will need to add additional tests to test all the exif edit tests on corrupt exif. 

The author has added an option to the _dump to ignore the wrong format tags. In some images the resulting exif is correct(the wrong format tag is removed), but in some the wrong format tag is still there, the piexif will not crash, but the resulting exif is not valid, for example, where there was a rational format value for a tag that is supposed to be byte, the resulting exif still had a rational format value there, except that it was 0(so it went from (x,precision) to (0, precision)).
I had pointed that out to the author ~2 days ago and he is not responding so fast to fix this.

We might need to reconsider a few general issues with the exif, since it is very odd that we even get such examples in our db in the first place. 
exif is defined by the tags and their format, from which one can know the bytes offset in the header and how much bytes to take to read a certain tag, from this point of view, I don't know how is it even possible to interpret a rational value where a single byte is supposed to be, without taking extra bytes for that tag and readjusting the offset for the next, but that means there either has to be loads of ifs somewhere(piexif guy does have a crazy amount of ifs) or there could be some bits indicating the format of the tag, but i can't find that in the exif specs, there it just says the offset and format and with that all is defined.

i need to check the exifedit again to see if all the values are really in the right format, for example we could be casting some values as float(32) and piexif won't complain, but they should actually be long(64) according to exif

might also be good to consider reviewing the images in the db(however is that possible for over 200 m) to get an overview of how many corrupt exif we have, everything is based on the data stored there, we should really have a correct and standard exif in all of them

**Comment by jernejaMislej** [comment]
@ybkuang piexif guy says he is not releasing the fix, since the bug is still there, so either we fix it ourselves, or fork and release it ourselves the way it is

**Comment by ybkuang** [comment]
@jernejaMislej Thanks!

I've forked the repo https://github.com/mapillary/Piexif. Installing with pip install is trivial even if we don't release it with `pip install git+https://github.com/mapillary/Piexif`

So the remaining things before our release of the piexif replace:
1. Investigate and make a fix for the issue of tag with wrong format as you describe 
2. ensure that the data types for values we insert in `exifedit` are valid 

Validating the exif for the images already in the db will be good. But as you said, it is a bigger operation. We could do it at the time when we want to reprocess all the images again.

**Comment by jernejaMislej** [comment]
list of keys, where piexif crashes for loading only:

```
jh4YcX81qIkDpDkNLPjFcg.jpg
FELDVmozaCkcNGuJZ2RHmQ.jpg
Rg64c90kOnPBZIbA9x_gEg.jpg
3DeWeYMBpZhJvqQIk--Ulw.jpg
7k42OeOsVv-Ksb7t5AhqTA.jpg
CqaesA5M4NGDvNqdG0bwOw.jpg
9L4V9TQjek5xTCESdJI7UQ.jpg
0HQfncIhmSsmmhQGZQanPQ.jpg
Tq49y9wlxixXgYHI_jH9Qw.jpg
Ae2-MlOiIzPK8AgKw6I5-g.jpg
GisIdm9UIhEH1_1m5tc3Eg.jpg
weBpgbZ74vEXGmPd9OeVJw.jpg
m5a5PYK1MtaVbMA4a_91Ww.jpg
JqZDNXjeKlh9wYjSoELB-w.jpg
2xGoQKiZTq7wW-FOWy85SQ.jpg
8Xd7n82jZ8Lw8LsdUoAaVg.jpg
zdoL645-BkwR2Foiy4knJA.jpg
K6TZslGXzLl5dK5XVIQ-Rg.jpg
r3TpEWHclyztegdR9fYYAg.jpg
GlFp0Bo7syk2gRY3C-VSBQ.jpg
p4dpZI1WHa614lMqFlYkqw.jpg
qJP6zZoYVNYMEW1TSsHPBQ.jpg
xU1jjvex5dqy9FvkNrwQ2w.jpg
rmPqRAMA1DS-K1oVE7aMCg.jpg
PTm9QGNX25cpnzC7SruQpQ.jpg
96tAIPDqT27AvD3D-dbfmw.jpg
e8cOMYgLK_cjoTk_zzS7yg.jpg
9DNZtz3BSUXQf5mnpWjWoA.jpg
gwn_jJm8yLrhP8IpPYwuOQ.jpg
CXeKGbswfBrsPyTZhpbwsA.jpg
PruQqseJ8yyjokNjtYmnwQ.jpg
DVRdc5saAkq15NERXgYDTA.jpg
bnBMT-d5tcHP9oPw0Se4IQ.jpg
IHmCl1k9o3CY5Ax_yJleOg.jpg
Adk64R3WAaqSiPOU22MzvA.jpg
K_hnmzPqSjO2Vbda-xac3Q.jpg
RbASjFD0Ygv-OSMwdExWFQ.jpg
AeQb6vSTcl0VxlnOJZH0uw.jpg
P-en0JNpYddIq8aiR-aIsw.jpg
ibO__WOzdK_E6Fg5O2CvGg.jpg
rUJ7_M4lsQMiEjnzgSKu6w.jpg
o9LewjyOCxwvlwOcVhNthQ.jpg
1NxUBaunj5-z8eQKIK4E5Q.jpg
RFQ709jBc5W9LN2TfYYVsg.jpg
lxxzFy9sLUnCbPUDu5mGUg.jpg
1vzO1xk8XF8nzmG7uwGJTg.jpg
tcJmUEEiPvSmuQr10zAP_Q.jpg
0TX1nETBEqatazdN588KTA.jpg
oUaVzz90bTnuZl_SoHOx3g.jpg
FqFygJUH-pH8-rubSdEzVQ.jpg
VLEUdQjot9oIFXqEXgGZGw.jpg
4nEcgkT2DRys0DI82LEz3w.jpg
LJNIcfUSy6y0LraqDuAkrw.jpg
qtqg809Gq_ka4MTDKnXsxw.jpg
v_a5ZkLCEze_hDafX2DpzQ.jpg
Zk6gasoVj8HOmZbMbjH15Q.jpg
zQBQKgnwIAcunKzWwX9S2A.jpg
GpFx6oO0z2U8doDDkCV92w.jpg
F2jKT2QuLJy7hKNbYJRPOA.jpg
ZK13sJ0sxJJnS0C2D9063g.jpg
gqSuebulLncc4W2RaIJlAw.jpg
9Bcjc7mA8KNHHq8RA35gxg.jpg
sQnOLsaZq5Qp6pMUlmBPQA.jpg
lOBajhiLostD1kyzxwaAAA.jpg
S_nDNub6jK15qRcjtJPHnA.jpg
17WFgoYGKwlVlOrY9kYiyw.jpg
Ya6kBV4_TkhhZ52siasLrw.jpg
HLGQIk1i_tDgZ2VkpvRrtQ.jpg
UiD7mNp5y7hsN3X43PzPBA.jpg
_hcufZE-0-8QRmvgCqIFtQ.jpg
biI7pRNxkdYKB2xOQXyb6Q.jpg
7ShuHFKrEIhWZTjfd4Y7yg.jpg
h16RTNnwEDdrB28m7JShBA.jpg
aDWkxpUB0461DpT2NfMoAw.jpg
TuuuQH88zGtHKHZuh-ZTrQ.jpg
Rbhrs7UfAR1PwCLjB3HBsQ.jpg
Q1-vTVstiO9SLfbWrX5j0A.jpg
eQCIEP7PNrL4gpKHKGQ6bg.jpg
tXuVTPXR1o2jAvuUU9gOiw.jpg
mQeyLRqOoIxzWDJQxvLMUA.jpg
YNM9O1SRM1VrbVpwmolEvg.jpg
kp2a0DgylqJBGWqW4kHXCw.jpg
3IQ7cNod2Ln2H7dvW78eTg.jpg
35U4Dqsw6z-JQpIm8WIysg.jpg
P9tI9KZseMLo-HfDtHsGcw.jpg
PbMCOj8wu7EgOOh4wkcknA.jpg
ALTMrSp5DFN1-U-2JQw5Cg.jpg
H_mDZYvaATYuLSL5nQiItQ.jpg
jG4tmtHdGszxoxX_3qztjw.jpg
O3kmI8tQVojYOKNGzjsTcQ.jpg
```
i will check a few in more detail and open an issue at piexif if neccessary

**Comment by jernejaMislej** [comment]
@ybkuang exiftool can read these, but can't edit/write, due to errors
pexif can read and write, so i was able to take the image description away and will make an issue at piexif
just a summary of this issue:
out of ~9k images from our db, 90 werent able to load with piexif, where ~half was due to ValueError, with error message `Exif might be wrong. Got incorrect value type to decode. tag: 1 type: %d` tag was always 1, type was different, tag 1 is the `InteropIndex`, that is why exiftool can't edit, it says `Error: [minor] Bad InteropIFD directory `
other half failing is due to issues with  `InteropIndex` as well, but the error is not thrown, since it fails somewhere before when trying to unpack , with error message `error('unpack requires a string argument of length %d',))` where %d was either 4 or 2

i checked the make and model and got this:
```
      1  Garmin	 VIRB
      6  Garmin	 VIRBX
      5  Garmin	 VIRBXE
      1  RICOH	 RICOH THETA S
     31  SONY	 HDR-AS200V
     45  SONY	 HDR-AS300
      1  XIAOYI	 YDXJ 1
```
sony is messing something up and seems common, create dates are from `2017:06` to `2017:12`

**Comment by jernejaMislej** [comment]
i have opened another issue for the load fail, the author said that he will not try to load broken EXIF, but to me it seems that the definition of a valid EXIF can be so different , his seems to be very strict, which is the reason for other issues as well. Although considering that `exiftool` can not edit/write to those files where load fails neither, that could be acceptable, but he said if there is a bug in `piexif` with the load, he will fix it.
As for the checking the validity before dumping, it seems that he had removed the changes to dev, where he attempted to fix something.
I think the issues is that `piexif` will like all others, read/load the EXIF as it is, according to the basic structure, where each tag has bytes for `id`, so one can know which tag it is, then bytes for `type`, bytes for `count`, bytes for `offset` to the next tag and bytes for `value`, but when loading, after the `value` is read, the ` type` is not saved since a dictionary is constructed, where keys are tags and items are values. But then when it needs to dump, it will pack the bytes back, using the types saved internally, as they should be according to standard. Whatever value is there, its being casted into the corresponding type according to standard and not according to what was written in file. If the actual value is within the limits of that type, then there is no error, but the result is not necessarily all to standard, because the count will be set to how many values could be casted and not according to standard.
But if there is an overflow, then the packing into bytes will fail.
One option would be to remember the type when it was read from file and use it to compare to the one that should be there according to standard and if it isnt then the tag is removed.
We would just need to consider how much valuable information we could loose like this.
Otherwise, I think that it should be written with the type which was in the file, as casting should have a check if a value can actually be casted into a certain type.
The check for validity is already done, we just need to decide if we want to always write exif according to standard or as it was given to us.
