### ISSUE TITLE
Fix orientation option 

### ISSUE THREAD

**Issue by ybkuang** [mapillary/mapillary_tools#202]
### About
Orientation option in `upload_tags.py` and `upload_with_preprocessing.py` only works when the original orientation tag is `1`

### Tasks
- [ ] Add logic to adapt the orientation tag relative to the original orientation value

**Comment by jernejaMislej** [comment]
closing this since it is regarding scripts that are no longer used.
if the problem still occurs in the new tools version, lets open a new issue
