### ISSUE TITLE
--upload_subfolders starting uploading as one giant sequence

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_tools#206]
had a folder with 10+ subfolders (from `sequence_split.py`) and ran 
`python upload_with_authentication.py /Users/username/Desktop/pics/ --upload_subfolders`
and it started uploading all 6000+ images as one sequence

Python 2.7.13, OSX 10.12.6

**Comment by ybkuang** [comment]
@danbjoseph yes. upload_with_authentication.py with `upload_subfolders` will treat all images as one sequence. `upload_with_preprocessing.py` is a better option for doing both splitting and uploading in one step. Sorry about the inconvenience.
