### ISSUE TITLE
ImportError: No module named exifread

### ISSUE THREAD

**Issue by DaveF63** [mapillary/mapillary_tools#209]
Hi 
A while since I've last used python. Using Windows
I downloaded & extracted the python folder from mapillary_tools-master.zip 
From a shell command line I ran & got the following error:
Any ideas?

```
"C:\Program Files\Python27\python" "I:\Action Camera\python\upload.py" "I:\Action Camera\PHOTO\Test"
Traceback (most recent call last):
  File "I:\Action Camera\Mapillary python\upload.py", line 6, in <module>
    from lib.uploader import upload_file_list
  File "I:\Action Camera\Mapillary python\lib\uploader.py", line 1, in <module>
    from lib.exif import EXIF
  File "I:\Action Camera\Mapillary python\lib\exif.py", line 5, in <module>
    import exifread
ImportError: No module named exifread
```

**Comment by ybkuang** [comment]
@DaveF63 thanks for reporting. It is related to the library dependency. We will update the instructions for the setup on Windows this week which you can follow to set up the library properly.

**Comment by ybkuang** [comment]
@DaveF63 Here is a short description on the setup  
- Install `PIP` by following the instructions [here](https://pip.pypa.io/en/stable/installing/)
- Install Dependencies:
  ```pip install -r requirements.txt```

**Comment by ybkuang** [comment]
@DaveF63 does the installation work out for you?

**Comment by DaveF63** [comment]
Busy with other things
