### ISSUE TITLE
upload_with_authentication.py fails

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_tools#21]
$ python upload_with_authentication.py 100_VIRB/3/
Traceback (most recent call last):
  File "upload_with_authentication.py", line 143, in <module>
    uploaders = [UploadThread(q, params) for i in range(NUMBER_THREADS)]
TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by ligfietser** [comment]
Since I have upgraded Exifread to version 2.0.0 I get the same error
"Missing required EXIF tag: GPS GPSLongitude"
Before with version 1.4.2. it worked fine, any ideas how to solve this?

**Comment by wimh** [comment]
I created issue #33 for the exifread 2.0.0 problem. The current workaround is downgrading exifread like this:

    pip install exifread==1.4.2

I will update #33 when I have more information

**Comment by ligfietser** [comment]
Thanks Wim, for me pip install exifread==1.4.2 did not work, but I managed to downgrade it with
python -m pip install exifread==1.4.2

**Comment by ybkuang** [comment]
@ligfietser The issue with exifread should be fixed now.
