### ISSUE TITLE
ffprobe not found

### ISSUE THREAD

**Issue by schadow1** [mapillary/mapillary_tools#216]
I get this error whenever i run geotag_video.py

> c:\Python27\mapillary_tools\python>geotag_video.py "D:\videoencode\0022[1]_Stitch_XHC.MP4" --image_path "D:\videoencode\image" --sample_interval 2.59 --gps_trace "C:\Temp\Photos\LR.gpx" --offset_angle 90
Video starts at: 2018-02-01 02:49:47
GPS trace starts at: 2018-02-01 02:49:47
Traceback (most recent call last):
  File "C:\Python27\mapillary_tools\python\geotag_video.py", line 113, in <module>
    video_duration = get_video_duration(video_file)
  File "C:\Python27\mapillary_tools\python\geotag_video.py", line 34, in get_video_duration
    return float(FFProbe(video_file).video[0].duration)
  File "C:\Python27\mapillary_tools\python\lib\ffprobe.py", line 28, in __init__
    raise IOError('ffprobe not found.')
**IOError: ffprobe not found**.

**Comment by ybkuang** [comment]
@schadow1 you will need to install ffmpeg for this. We are working on adding that to the doc. Before that can you try this? 
 - Browse to and download the latest release :
    http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/
 -  Unzip and extract all files.
 - Follow instructions to add to path and system environmental variables.

**Comment by schadow1** [comment]
@ybkuang 

Thanks. Got passed that error after installing ffmpeg. But now with this new error:

>   File "C:\Python27\mapillary_tools\python\lib\ffprobe.py", line 77, in __init__
    (key,val)=a.strip().split('=')
ValueError: need more than 1 value to unpack

**Comment by tobecwb** [comment]
got ffprobe not found too, but I have ffprobe installed, and in PATH...
in terminal, If I type `ffprobe` in any directory, ffprobe work ok
with geotag_video.py, I always got `ffprobe not found` error.

**Comment by jernejaMislej** [comment]
hi @schadow1 and @tobecwb , sorry for not getting back to you on this.
are you still having issues with `ffprobe` installation?

**Comment by jernejaMislej** [comment]
please open a new issue if anymore problems with the installation of ffprobe, closing this for now
