### ISSUE TITLE
Uploader does not respect number of threads; leading to crashes hitting system limits

### ISSUE THREAD

**Issue by daniel-j-h** [mapillary/mapillary_tools#221]
When using the Python scripts to upload images the uploader creates an increasing number of threads sitting around leading to crashes like the following:

```python
Traceback (most recent call last):
  File "upload_with_preprocessing.py", line 317, in <module>
    upload_file_list(file_list, params)
  File "/tmp/mapillary_tools/python/lib/uploader.py", line 322, in upload_file_list
    uploader.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

Here we default to four threads per upload: https://github.com/mapillary/mapillary_tools/blob/24c14ab8fb5d8881a3e8ad513fcac9a4f8712e00/python/lib/uploader.py#L24

Using this default value the following image shows what I can see after a couple of seconds of using the `upload_with_preprocessing.py` script:

![htop](https://user-images.githubusercontent.com/527241/36258509-3643ff8e-125b-11e8-91ab-e7442184e3cb.png)

I could track it down to `lib.uploader` thread creation and queueing implementation: callsite is here:

https://github.com/mapillary/mapillary_tools/blob/24c14ab8fb5d8881a3e8ad513fcac9a4f8712e00/python/upload_with_preprocessing.py#L317

Here is the upload thread uploading from its queue:

https://github.com/mapillary/mapillary_tools/blob/24c14ab8fb5d8881a3e8ad513fcac9a4f8712e00/python/lib/uploader.py#L32-L49

and here we create the threads set them to daemon mode and start them:

https://github.com/mapillary/mapillary_tools/blob/24c14ab8fb5d8881a3e8ad513fcac9a4f8712e00/python/lib/uploader.py#L308-L332

My initial assumption was joining the daemon threads was the problem. But even when removing the daemon flag (why do we need daemon threads here?) I can still see the number of threads increasing and increasing as time goes by.

cc @ybkuang

**Comment by ybkuang** [comment]
@daniel-j-h can you share your screen printouts as well? Beside, potential complications with threads, this could happen also there are many sequences in the folder. I will look into the thread handling.

**Comment by daniel-j-h** [comment]
What do you mean with screen printouts? The uploading logs? There's nothing suspicious in there, just regular uploading logs.

And yes the `upload-with_preprocessing.py` script is creating a lot of sub-directories. My use-case uploading many smaller sequences.

**Comment by ybkuang** [comment]
@daniel-j-h With the printouts, I just want to see how many sequences (sub-directories) are there. N sequences will create 4N threads in this case. Need to work on a fix for that.

**Comment by daniel-j-h** [comment]
Oh there are definitely in the tens of thousands of sub-directories or more ;)

**Comment by ybkuang** [comment]
OK. That makes sense then. The script will split images to sequences (sub-directories) if the consecutive images are `x` meters away from each other (default x=600). Just to double check, are there many captures with large distances in-between for your images? I want to understand why the script is `creating` so many sub-directories. 

And yes, I will work on a fix for this scenario in the mean time.

**Comment by daniel-j-h** [comment]
Yes there are a lot of small sequences, the script creating all these sub-directories is correct and its output expected for the use-case. What I'm currently doing as a workaround is splitting the images into smaller batches and uploading these smaller batches.

**Comment by ybkuang** [comment]
@daniel-j-h I have now a fix but would like to test it further. Before the fix is merged, can you try the following steps:
```
python upload_with_preprocessing.py  [path_to_images] [other-params] --skip_upload
python upload.py [path_to_images] --upload_subfolders
```
The first line will pre-process the images but skip uploading. The second line will upload all the images in a folder including the sub-folders.

**Comment by daniel-j-h** [comment]
Thanks! Yes splitting pre-processing from uploading seems to do the right thing here.
