### ISSUE TITLE
 upload_with_authentication.py skips images on faill

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_tools#23]
Due to a wonky connection the upload fails from time to time. The upload script then skips the current image completely. Since the problem is not with that particular image but with the connection skipping these images isn't the best way to go.

    URL error: <urlopen error [Errno 32] Broken pipe> on VIRB0738.JPG
    URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on VIRB0738.JPG

or

    HTTP error: HTTP Error 400: Bad Request on VIRB0709.JPG

So it would be a good idea to either try again two or three times or move these images to the end of the stack to prevent loss.

**Comment by liskin** [comment]
Just noticed this issue. You may want to try my branch: https://github.com/liskin/mapillary_tools/commits/master

**Comment by richlv** [comment]
thanks - have you tried submitting a pull request for retries ?

**Comment by liskin** [comment]
No, I didn't think another pullreq/issue without any comments from the mapillary team would help anything. I just mentioned it in a somewhat relevant thread elsewhere.

**Comment by richlv** [comment]
failed images are still skipped. there does not seem to be any way to upload them to a started sequence. anybody from mapillary interested in this ? otherwise i'm just wasting your bandwidth and storage by uploading and then removing images again and again...

**Comment by jesolem** [comment]
@liskin What feedback are you looking for? Didn't see question, sorry. We'd love PRs for retry. 

@richlv We're currently low on mental bandwidth here with a bunch of releases about to go out, will get to this as soon as we can.

**Comment by liskin** [comment]
@jesolem https://github.com/mapillary/mapillary_issues/issues/118#issuecomment-76613261
(and do note that I had to fix another issue, so just look here and grab whatever you want: https://github.com/liskin/mapillary_tools/commits/master)

**Comment by liskin** [comment]
(And yeah, I'm still trying to get rid of that bloody x9RQKYP_86gEmdcHq8wepQ sequence. I submitted at least 5 requests for hiding the whole sequence and every time only a little part of it was hidden.)

**Comment by richlv** [comment]
@jesolem , thanks for the response. do the changes by @liskin seem reasonable ? maybe they can be merged as a short term solution :)

**Comment by richlv** [comment]
well, had 3 gb of images. 578 uploaded just fine, 67 failed. as far as i know, that's a screwed up upload. the only option is to remove the whole upload and try again, hoping that this time it will be better... this time the errors were like this :
URL error: <urlopen error [Errno 111] Connection refused> on IMG_1596.JPG

**Comment by jesolem** [comment]
@liskin Finally had time to take a look, sorry for the delay. Commented on your branch and would love to accept a PR if you want to submit it.

**Comment by richlv** [comment]
@liskin heya, i would definitely appreciate a PR to retry forever on any error ;)
just now, had another sequence fail with :
```
error: [Errno 104] Connection reset by peer
```
so that's more bandwidth wasted.

**Comment by liskin** [comment]
Okay, see #58. I haven't tested the last commit though and I know very little Python to assume it must work, please test.

**Comment by jesolem** [comment]
#58 is merged. Thanks @liskin
