### ISSUE TITLE
Upload with sub-second imagery out of order

### ISSUE THREAD

**Issue by ethan-nelson** [mapillary/mapillary_tools#231]
### Basic information
* Version: `mapillary_tools commit 9ac0557109f14d479277cab8baae11bafd92c7b3` 
* System: `Linux Ubuntu 15.10 wily`, `python 2.7.10`
* Capture Device: `Action Camera` 

### Steps to reproduce behavior

 1. Take time lapse photo imagery at 0.5 sec resolution on GoPro
 2. Use `python/interpolate_direction.py` on photos to add heading info (this may not affect this issue but I've already done it)
 3. Use `python/upload_with_authentication.py` on photos

### Expected behavior

Sequence would upload sorted by time _and_ file name sequentially.

### Actual behavior

Order is possibly based on time stamps only because photos within a second are sometimes mixed up in order. 

Here is a hypothetical example. Say three photos are taken:

Photo # | Filename | Real Time | GoPro EXIF Time |
---|---|---|---
1 | G122.JPG | 2018-01-01 02:04:04.24Z | 2018-01-01 02:04:04Z
2 | G123.JPG | 2018-01-01 02:04:04.74Z | 2018-01-01 02:04:04Z
3 | G124.JPG | 2018-01-01 02:04:05.24Z | 2018-01-01 02:04:05Z

The sequence may make the photos actually be in order 2,1,3 or 1,2,3.

### Corresponding data

https://www.mapillary.com/app/user/fta?pKey=6JdUfQOzS5WnyenXS2_lTQ: [Photo 7](https://www.mapillary.com/app/user/fta?lat=33.9599565999722&lng=-118.3909093999722&z=17&pKey=mWC5C0dzrweu6jQlzljsdw&focus=photo) is the first one that jumps out of place with others in the sequence.

Similarly, https://www.mapillary.com/app/user/fta?pKey=oiNi7JulEVMrrekRXOog-Q

### Additional info

Maybe this _isn't_ a big deal but I thought I'd file it to see if you had any suggestions. I have about 110 GB of processed photos to upload with 250 GB still to process, so I would like to iron out any issues before I start uploading _en masse_.

**Comment by jernejaMislej** [comment]
hi, thank you very much for informing us about this. 
yes files will be uploaded ordered by time only and in case of identical timestamps, subsecond timestamps are estimated for a list of files which is currently not ordered,  so I will have to double check nothing is broken, to add the sorted().
I apologize for the inconvenience, i will let you know asp
thank you for the patience, hopefully you can soon upload your images without worrying about the quality

**Comment by jernejaMislej** [comment]
hi, sorry for getting back late. 
the script you are using is a bit obsolete and actually does not have the timestamp interpolation in case of identical timestamps, please use `upload_with_preprocessing.py` instead. It can also interpolate directions if passing the `--interpolate_directions` arg, so you dont have to run two scripts.
It will sort the timestamps and files in a zip, so it should be ok in your case as well
Let me know if that is not ok or if you have any more issues

**Comment by ethan-nelson** [comment]
Thank you for tracking that down! I will be sure to run the script with timestamp interpolation. Cheers!
