### ISSUE TITLE
geotag_from_gpx.py unlisted module required

### ISSUE THREAD

**Issue by jaku103** [mapillary/mapillary_tools#232]
When attempting to set GPS cordinantes on images, the script sayed the dateutil module was not loaded. This module is not listed as required, after installing python-dateutil==2.7.3 everything worked fine.

**Comment by jernejaMislej** [comment]
thank you for informing us about this, we will take care of it

**Comment by jernejaMislej** [comment]
i have updated the requirements, please let us know if there is anything else you notice
