### ISSUE TITLE
process_and_upload script missing

### ISSUE THREAD

**Issue by tastrax** [mapillary/mapillary_tools#240]
Trying to follow instructions for new scripts and noted no 'process_and_upload' script as per the instructions on https://github.com/mapillary/mapillary_tools under 'usage'

**Comment by tastrax** [comment]
![image](https://user-images.githubusercontent.com/8775395/41026294-85d2d3d2-69b7-11e8-9627-8dc9a35c0b4c.png)

**Comment by ToeBee** [comment]
`process_and_upload` is not a separate script, it is a command line argument to pass into the `mapillary_tools` script. Like:
`mapillary_tools process_and_upload --import_path /path/to/files --user_name myuser .....`

**Comment by tastrax** [comment]
many thanks - partially sorted now
