### ISSUE TITLE
Status tools for big uploaders?

### ISSUE THREAD

**Issue by cookry** [mapillary/mapillary_tools#243]
@bob3bob3 commented on [Tue Jun 05 2018](https://github.com/mapillary/mapillary_issues/issues/2926)

I am part way through uploading about 2 years of drive images. (still using the older tools) At about the 200K point with maybe 800K to go.

I'd like to get an idea of the probable processing time for large runs. I am of course getting a lot of email alerts, but they keep coming days after the upload. I'd like to get an overall idea of where they are up to. "Pending images" doesn't seem to give me real numbers.

One of my concerns are what appear to be missing sequences (gaps) in the map. How do I know if they are really "stuck" or "missing" beyond just waiting?

Web interface, Debian 8 platform.

Tnx

---

@cookry commented on [Thu Jun 14 2018](https://github.com/mapillary/mapillary_issues/issues/2926#issuecomment-397505575)

@bob3bob3 have you tried our new Command Line Tools? These are tailored to streamline your upload workflow and provide a status on the upload status: https://blog.mapillary.com/update/2018/05/31/updated-upload-tools.html

---

@bob3bob3 commented on [Fri Jun 15 2018](https://github.com/mapillary/mapillary_issues/issues/2926#issuecomment-397518133)

@cookry yes I have. I have to be careful though to put as much as possible into a virtual environment as the process is run from a remote production machine that I only physically visit every 2-3 months to exchange USB drives. (containing run code as well as data) The older tools were strong on that, but the new ones seem to be more sudo oriented.

I am assuming that the pip commands for Piexif and mapillary_tools will run under virtual but have yet to try. README.md is a bit vague on this. I'll try it all soon.

---

@cookry commented on [Fri Jun 15 2018](https://github.com/mapillary/mapillary_issues/issues/2926#issuecomment-397759171)

@bob3bob3 I am moving this to the mapillary_tools repo where we can better address.

**Comment by jernejaMislej** [comment]
hi, pip and everything else should work the same in virtual environment as long as you have all the dependencies installed.
Be careful with mixing uploads done with old scripts and new tools as the logging logic is not compatible, ie if you have uploaded images with the old scripts and run the new tools for the same images, they will be uploaded again.

**Comment by bob3bob3** [comment]
Yes have now tried the virtual environment, works well.

I still see gaps in the map GUI for my older tool uploads. The one case I checked is missing a complete directory sequence, all of which were moved to the success directory. There was also nothing untoward in PROCESSING_LOG.json & UPLOAD_LOG.txt. (It did die a few times needing restarts)

Before I just try and upload again, is there a way to check if any of my uploads are "stuck" on the server. I don't see anything in https://legacy.mapillary.com/map/upload/im as is suggested in the README.

If I were to upload again do the new tools require process_and_upload or just upload tool?

**Comment by jernejaMislej** [comment]
@bob3bob3 what exactly did you do so far? it is not completely clear to me, if I understand correctly you uploaded part of a large import using the old tools, but find missing images on the map, where according to your local logs, they should be uploaded?
if so , please let us know your Mapillary username and if possible date/time when the images were supposed to be uploaded(the creation date/time of success directory should be ok for now) and we will try to check this

and you are also considering to use the new tools to finish uploading? if so you need to be very careful as the logging logic is not compatible, ie images would get uploaded again, so you would need to make sure those are not included, ie are not under the specified import path

**Comment by bob3bob3** [comment]
Yes that is correct. There are perhaps 20-40 track gaps that are visible on the web interface. The old tools broke the upload into 289 sub directories. The PROCESSING_LOG.json is dated 2018-05-29 23:51 (Australian Eastern Time UTC-10) which would represent the start of the job. The UPLOAD_LOG.txt file is dated 2018-05-31 22:02 which would represent the end of the job. The upload process did fail around 10 times but these logs were always clean and all files moved to success.

One of those (I assume complete sequence) failures success directory is dated 2018-05-30 09:04

Mapillary username is bob3bob3

I am about to start using the new tools to upload the balance of all my backlog. At some stage I will want to resolve the missing gaps so I will use the new tools for them, but only if I can ascertain that the aren't stuck somewhere on the Mapillary server. Unfortunately this is a visual process of comparing the Mapillary map with my track of the day and picking a file timestamp range that matches.

**Comment by jernejaMislej** [comment]
@ybkuang @peterneubauer can you please check if we can find any information regarding the failed uploads for the user and date provided in the last comment. The upload was done using the old tools and all files were moved to the `success` folder, so it is not clear locally why the images do not appear uploaded.

**Comment by peterneubauer** [comment]
So, the upload tools are putting the images into an AWS S3 bucket, and they wait there until our harvesters can ingest them, at which point you see them in the pending images etc. These last days, that harvester has been overloaded, so the images were sitting unusually long in S3. We are working to make this scale better, but the images should be coming through now?

**Comment by bob3bob3** [comment]
To complicate things I have uploaded 400-500K of images in the last week using the new tools, which are appearing okay. The gaps or missing (using the old tools) from late May though are still absent.

**Comment by jernejaMislej** [comment]
Hi sorry for the late reply, I m on vacation until 10th August with limited access to internet. @ybkuang will try to address the issues while I m gone

**Comment by bob3bob3** [comment]
@cookry Please close this issue. I wont attempt to fix as the gaps will be filled by future travels. Thanks.

**Comment by cookry** [comment]
@bob3bob3 thanks for your image contributions! We have continual updates planned for Mapillary Tools and your feedback helps us to identify desired features. Continue to follow our progress in the release notes here: https://github.com/mapillary/mapillary_tools/blob/master/CHANGELOG.MD
