### ISSUE TITLE
url error - is a resolution needed?

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_tools#249]
with the previous version of the scripts, i would sometimes have to run the upload a second time. because sometimes the script would finish and some images would remain unmoved to either success of failure.

when running...
```
mapillary_tools process_and_upload --import_path "/Users/danbjoseph/Desktop/DCIM" --user_name "danbjoseph" --advanced --cutoff_distance 50 --cutoff_time 60 --flag_duplicates --duplicate_distance 0.5 --verbose --rerun
```
i got a handful of errors like the following, but otherwise it seemed to have gone fine. is there anything else i need to do? 
```
URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on DSC08793.JPG
URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on DSC08787.JPG
URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on DSC08208.JPG
URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on DSC08793.JPG
URL error: <urlopen error [Errno 8] nodename nor servname provided, or not known> on DSC08787.JPG
```

same error message was encountered in #23 
in the past i __*think*__ this was the error message that resulted in a skipped image?

**Comment by andrewharvey** [comment]
It looks like running the same script again should clean up / retry any failed uploads.

**Comment by danbjoseph** [comment]
i ran the below to followup
`mapillary_tools upload --import_path "/Users/danbjoseph/Desktop/DCIM" --verbose`
and got this output
```      
Uploading 6 images with valid mapillary tags (Skipping 13798)
Uploading with 4 threads
Done uploading 6 images.=====================================] 100.0% ... 0 images left.
```
so i guess that's that
