### ISSUE TITLE
upload_with_authentication.py just uploads all files in sub folders into the same sequence

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_tools#25]
I expected that I'd be able to run time_split.py, then run upload_with_authentication.py and it uploads each split folder as a separate sequence correctly, however it seem that I need to run it once for each sequence, which is horribly annoying, as e.g. I have 23 sequences to upload from the last 2 days accross several folders (otherwise end up with duplicate file names from the camera - Garmin VIRB).

```
/Volumes/Drobo/Pictures/Virb/2015-01-01/102_VIRB:
0	1	2	3

/Volumes/Drobo/Pictures/Virb/2015-01-01/103_VIRB:

/Volumes/Drobo/Pictures/Virb/2015-01-01/104_VIRB:
4	5	6	7	8

/Volumes/Drobo/Pictures/Virb/2015-01-01/105_VIRB:

/Volumes/Drobo/Pictures/Virb/2015-01-01/106_VIRB:
10	11	9

/Volumes/Drobo/Pictures/Virb/2015-01-01/107_VIRB:
12	13	14	15

/Volumes/Drobo/Pictures/Virb/2015-01-01/108_VIRB:
16

/Volumes/Drobo/Pictures/Virb/2015-01-01/109_VIRB:
17

/Volumes/Drobo/Pictures/Virb/2015-01-01/110_VIRB:
18	19

/Volumes/Drobo/Pictures/Virb/2015-01-01/111_VIRB:
20

/Volumes/Drobo/Pictures/Virb/2015-01-01/112_VIRB:
21	22
```

**Comment by jesolem** [comment]
You need to upload so that one session = one sequence. Otherwise there is no way for us to know what photos should go together as a sequence. 

In the apps we store sequence information in EXIF so these photos can be uploaded any way you like. With Virb photos you need to send them one sequence at a time. 

Not much we can do about that

**Comment by smsm1** [comment]
I was thinking that it would be possible to upload a folder at a time as sequence. I'll probably create a bash script or make modifications to effectively do this to save the manual uploads, as I'll likely have lots of folders, as I'll sometimes do a day or two upload at a time.
