### ISSUE TITLE
allow --upload-threads --max-attempts as arguments

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#252]
### Basic information
* Release version: `master`
* System: `Linux`

The README says you can set the environment variables like this:

```
NUMBER_THREADS=2
MAX_ATTEMPTS=100
```

Could these be arguments to the executable? Personally I find arguments much easier to deal with.

**Comment by jernejaMislej** [comment]
I will consider adding those as arguments to the script in one of the next releases, I think it would be user friendly

**Comment by andrewharvey** [comment]
Thanks. By the way I did notice that my upload speed significantly increased when I set NUMBER_THREADS above the default, so perhaps it's a good idea to increase the default?

I was going to say maybe because of the high ping times between me and `s3-eu-west-1.amazonaws.com` (300ms) but then I realised you're using cloudfront as the upload URL which is only 13ms, so not sure why.

**Comment by jernejaMislej** [comment]
hi i implemented this for the v0.2.0 release, if you want to try it you can install the branch v0.2.0
let me know if anything is not ok, otherwise i ll close this

**Comment by jernejaMislej** [comment]
hi this functionality is now released, please install the latest version
