### ISSUE TITLE
Remove Duplicates

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#254]
The old tools had a remove_duplicates.py script https://github.com/mapillary/mapillary_tools/tree/a73f65e684486f17ada7a7dd3138df55c696d7ed/python to remove duplicates while sitting at traffic lights? Is this supported in the new tools? Does it happen automatically? Is there an argument to toggle it?

**Comment by jernejaMislej** [comment]
yes , `--advanced --flag_duplicates`
to see more info and additional related parameters, check `process --help --advanced`

**Comment by andrewharvey** [comment]
Thanks! I'll try to put together a PR which improves the README in this regard.
