### ISSUE TITLE
Upload Error : upload_file() got multiple values for keyword argument 'url'

### ISSUE THREAD

**Issue by CorentinLemaitre** [mapillary/mapillary_tools#258]
### Basic information
* System: `Windows` 
* Capture Device: `Gear 360 2016`

### Steps to reproduce behavior

 0. Opn the windows consol and go to the directory where the photos are stored. 
 1. Process with this parameter : C:\python27\python.exe C:\python27\Scripts\mapillary_tools process --advanced --import_path "" --user_name c-mobilite --flag_duplicates --interpolate_directions
 2. Import with this one : C:\python27\python.exe C:\python27\Scripts\mapillary_tools upload --import_path ""
 3. Get this message : 
"TypeError: upload_file() got multiple values for keyword argument 'url'

### Expected behavior
Get the picture uploaded

### Actual behavior
Error on the upload process. I don't know if it is done partially or not at all.

### Corresponding data
![image](https://user-images.githubusercontent.com/20289907/42768605-48b55d34-8920-11e8-8df4-63fe41d150c1.png)

**Comment by ybkuang** [comment]
@jernejaMislej can you take a quick look at this?

**Comment by jernejaMislej** [comment]
ofcoursy , all done, sorry about this @CorentinLemaitre cc @ybkuang 
please install --upgrade mapillary_tools
