### ISSUE TITLE
time_split.py loses files with duplicate file names

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_tools#26]
The time_split.py file will loose files where there are 2 files in sub folders with the same file name. This is an issue with for example the Garmin VIRB elite which places 1000 photos in a folder, then restarts the numbering of the photo files in a new folder. Ideally it should start a new folder, or rename the files that it's moving if there is a name clash.

**Comment by smsm1** [comment]
This also means that when the upload is done, the files can be uploaded in the wrong order, thus a big line back to the start of the track, e.g. http://www.mapillary.com/map/im/H3WBxigLyOQe9wsJx6Bj9w

**Comment by smsm1** [comment]
It looks as though the line back to the start of the track auto fixes itself after a short time of processing.

**Comment by jesolem** [comment]
Thanks @smsm1 , I use the Virb a lot and haven't noticed since I empty the camera directly after capture. I can see how this is annoying for long capture sessions. Will take a look.

**Comment by jesolem** [comment]
@smsm1 Is this still a priority or did you find a workaround?

**Comment by smsm1** [comment]
The work around that I'm using is a couple of extra scripts, plus a tweak to your python script as I've just documented at https://gist.github.com/smsm1/8c1ab74229d0ca7c5937

**Comment by jesolem** [comment]
OK. Pre-processing with adding a folder label/id to the filename would also work. 

Closing. Thanks @smsm1
