### ISSUE TITLE
--rerun not being recognised

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#261]
I'm trying to rerun the processing but even with the `--rerun` argument it's not being re-processed...

```
$ mapillary_tools process --rerun --import_path "~/photos/" --user_name "username" --advanced --interpolate_directions
Running user_process for 0 images, skipping 1794 images.
No images to run user process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Running import_meta_data_process for 0 images, skipping 1794 images.
No images to run import meta data process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Running geotag_process for 0 images, skipping 1794 images.
No images to run geotag process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Running sequence_process for 0 images, skipping 1794 images.
Running upload_params_process for 0 images, skipping 1794 images.
No images to run upload params process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Running mapillary_image_description for 0 images, skipping 1794 images.
No images to run process finalization
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Process done.
```

**Comment by andrewharvey** [comment]
I managed to workaround this by removing `.mapillary`

**Comment by jernejaMislej** [comment]
Hi sorry for the late reply I m on vacation until 10th August with limited access to internet. Removing .mapillary is very risky, are you sure the images were not uploaded already?

**Comment by andrewharvey** [comment]
I think they were, but since the automatic interpolation didn't work (https://github.com/mapillary/mapillary_tools/issues/253#issuecomment-404374965) I wanted to deleted the upload, and re-process and re-upload.

**Comment by jernejaMislej** [comment]
Ok, that makes more sense then. Currently the tools are made so that nothing more can be done once images are already uploaded, to prevent duplicate uploads.
The procedure in case one wishes to delete images and reupload does include deleting .mapillary, but we would like users to conntact support prior that, so we make sure everything gets deleted correctly, otherwise we might end up with a lot of duplicate uploads which is not good for quality.
You are welcome to suggest or contribute with a better solution.

**Comment by andrewharvey** [comment]
No worries, thanks for the explanation.

**Comment by andrewharvey** [comment]
Oops, I just realised that to fix this I could have gone into the sequence editor and chosen Normalise.
