### ISSUE TITLE
Uploaded 1600+ images but still 0 pending nor published

### ISSUE THREAD

**Issue by nicola-d** [mapillary/mapillary_tools#262]
Hi,

This morning I finished uploading more than 1600 images with the script but in my profile there are no new pending images and nothing is published. I'm not using the --manual_done switch so there should be no issues with the DONE file. My username is nicolad.

Thank you,

Nicola

### Basic information
* Release version: `0.1.0` 
* System:  `Linux (Raspbian)`
* Capture Device:  `Action Camera`

**Comment by ybkuang** [comment]
@nicola-d which script did you use and when did you upload? We had some issue with the harvester (the component of putting the uploaded images into processing) which is catching up. It could be related, but will be good to have more information.

**Comment by nicola-d** [comment]
I used "mapillary_tools upload --import_path ..." version 0.1.0. I started uploading images yesterday 17 July at around 15 CEST.

**Comment by nicola-d** [comment]
So, it is just a matter of time? Can I keep uploading images? Can the already uploaded images be deleted? This is because I'm running out of disk space and my connection is not fast.

**Comment by ybkuang** [comment]
@nicola-d The system is catching up. Can you check if you uploads are in now?

**Comment by nicola-d** [comment]
No, still no pending images (and nothing published)

**Comment by ybkuang** [comment]
@nicola-d We have now identified the issue. We are working on a fix now.

**Comment by nicola-d** [comment]
Looks like that most of my images are published and a few are pending but not lost! I'll try with another bunch of images as a test...

**Comment by Stefal** [comment]
I have the same problem. I uploaded a few sequences with the python script (v0.1.0) since 2 days and nothing is online. The first sequence uuid is: "b3e2d49c-4a7a-4c07-9c1b-315237afb839"

**Comment by Stefal** [comment]
The image processing is on its way since a few hours

**Comment by nicola-d** [comment]
Same problem again, a thousand images in a unknown status...

**Comment by ybkuang** [comment]
@nicola-d @Stefal Can you try using the latest version v0.1.2 for your future uploads? I will fix the old uploads now.

**Comment by Stefal** [comment]
I'm uploading a sequence right now (622 images left). I'll update to v0.1.2 for the next one

**Comment by nicola-d** [comment]
Look like it is also needed to remove the ~/.config/mapillary/config file and re-enter the credentials with the new v0.1.2 to make it work. 

From now on the images are listed as "pending" as soon as they are uploaded. So far so good then!

**Comment by nicola-d** [comment]
The old uploads (20 July) do not show up in the map even if they are marked as "published"...

The new version v0.1.2 is working good, thank you!

**Comment by nicola-d** [comment]
Seems like the issue is happening again with v0.1.2. Pending images counter not increasing.

**Comment by ybkuang** [comment]
@nicola-d I can see some sequences with 150 images each. How many images were you uploading in the folder?

**Comment by nicola-d** [comment]
I was uploading 1635 images, but because there were no "pending" I restarted the upload again (deleted all .mapillary folders).

**Comment by rwelty1889** [comment]
i'm having a seemingly similar problem using a relatively new version of mapillary_tools. the first images i uploaded from my backlog were published, but now uploads appear to be running but nothing is pending or published. this is a lot of images, i hope i don't need to start this over.

**Comment by ybkuang** [comment]
@rwelty1889 which version were you using? v0.1.0 has some minor issues which is fixed in v0.1.2.

**Comment by rwelty1889** [comment]
good question. not sure how to pull the version number, but i'm using the recent version that has the newer exifread version from about a week ago. should i use pip to upgrade? i've uploaded 10000 or so images using this version; the early ones were processed but now nothing is being processed.

**Comment by rwelty1889** [comment]
ok, it was 0.1.0 and i've upgraded to 0.1.2. do i need to reupload all that stuff? it's a lot and it takes a while.

**Comment by jernejaMislej** [comment]
Sorry for late replies, I m on vacation until 10th August, @ybkuang will try to address the issues in the mean time. If images were uploaded successfully with 0.1.0 , no need to upload again, we can resolve the issues with missing DONE file internally.

**Comment by jernejaMislej** [comment]
@rwelty1889 @nicola-d @Stefal are you still missing any images? Otherwise I will close this

**Comment by jernejaMislej** [comment]
ok @Stefal can you please share your mapillary `user_name` and we will sort it out

**Comment by nicola-d** [comment]
No more images missing from my side, thank you

**Comment by Stefal** [comment]
my user_name is: stephanep

The missing images were captured at this date : 2018-08-11
If you see images from 2018-08-12, I'm still uploading them.

**Comment by rwelty1889** [comment]
will need to double check when i get home; currently on vacation.

**Comment by rwelty1889** [comment]
one of my earliest uploads (maybe my earliest) after the python versioning problems got straightened out was of 6 go pro time-lapse sequences from May 25th; it looks from the creation date of the .mapillary file that i did this upload on July 19th. it appears that only one of the 6 sequences got processed. i can remove the .mapillary directories and upload again, but it may be a while as i have 11 days images from my recent trip to florida in the queue.

**Comment by jernejaMislej** [comment]
no need to reupload any images, just let us know your mapillary username and we ll check if any images have not yet made into the system and will take care of it

**Comment by rwelty1889** [comment]
my username is nfgusedautoparts

**Comment by jernejaMislej** [comment]
we made sure all the images have been pushed into the system, closing this
