### ISSUE TITLE
Distance mapped not increasing

### ISSUE THREAD

**Issue by nicola-d** [mapillary/mapillary_tools#265]
Hi,

it is quite some time that my "Distance mapped" counter is not increasing but I have uploaded a lot of images using the Python script.

When I was uploading using the Android app the "Distance mapped" was updating every time new images were published.

My username is nicolad.

Thank you and regards,

Nicola

### Basic information
* Release version: `0.1.2`
* System: `Linux`
* Capture Device: `Action Camera`

**Comment by jernejaMislej** [comment]
Hi sorry for the late reply, I m on vacation until 10th August with limited access to internet, @ybkuang will try to address the issues while i m gone.

**Comment by nicola-d** [comment]
The counter is working fine now. I close the issue. Thank you!
