### ISSUE TITLE
Can't run on Mac OS X - env: python\r: No such file or directory

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_tools#277]
### Basic information
* Release version: `0.1.3`
* System: `Mac OS X`

### Steps to reproduce behavior

 1. Install following instructions (I chose to install with `sudo` instead of using `virtualenv`)
 2. Run `mapillary_tools --version`

### Expected behavior

Running normally and displaying version

`Mapillary tools version : 0.1.3`

### Actual behavior

It doesn't run, with the following error:

`env: python\r: No such file or directory`

### Additional information

I noticed that running `python /usr/local/bin/mapillary_tools --version`, the program runs normally.

Also, my `python --version` output is `Python 2.7.15`.

**Comment by jernejaMislej** [comment]
hi, i think the interpreter program is not read due to `\r` at the end, can you try this
```
(sudo) sed $'s/\r//' -i $(which mapillary_tools)
```

**Comment by jernejaMislej** [comment]
hi, are you still having this issue? otherwise i will close this

**Comment by nighto** [comment]
@jernejaMislej no, it still happens.

**Comment by jernejaMislej** [comment]
@nighto ok, were you able to execute the command that removes all the space chars?
is the error message the same after executing that command?
there are other options to solve this, but all including editing the main executable on your side, see [here](https://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory)

**Comment by nighto** [comment]
@jernejaMislej it did not. Even though `which mapillary_tools` returns `/usr/local/bin/mapillary_tools`, running `sudo sed $'s/\r//' -i $(which mapillary_tools)` output `sed: -i: No such file or directory` and the python code on the console. Expanding the path manually (i.e. `sudo sed $'s/\r//' -i /usr/local/bin/mapillary_tools`) output the same error.

**Comment by nighto** [comment]
Tried the vim solution (`sudo vim /usr/local/bin/mapillary_tools`, `:set ff=unix`, `:wq`) and it worked :)

To close the issue it'd be interesting to add these instructions to the README.

Thanks for helping me debug it.

**Comment by jernejaMislej** [comment]
ok great, thanks, I will add it to the troubleshooting section in readme and close issue after that

**Comment by jernejaMislej** [comment]
done, it will be released with the next release, currently it is on branch v0.2.0
again thank you for contributing

**Comment by nighto** [comment]
Great, thank you @jernejaMislej
