### ISSUE TITLE
how to run authenticate? 

### ISSUE THREAD

**Issue by elpbatista** [mapillary/mapillary_tools#278]
### Basic information
* Release version: `0.0.0` | `0.0.1` | `...`
* System: `Windows` | `Linux` | `...`
* Capture Device: `iOS` | `Android` | `Action Camera` | `...`

### Steps to reproduce behavior

 1.
 2.
 3.

### Expected behavior

...

### Actual behavior

...

### Corresponding data

* sample images
* meta data

...

### Additional information

...

**Comment by jernejaMislej** [comment]
hi thank you for trying mapillary_tools and opening an issue, 
please be more specific what the issues is

**Comment by jernejaMislej** [comment]
Hi I will need more info here otherwise i ll close
