### ISSUE TITLE
Failed upload with upload_with_authentication.py conflicts with manual uploads

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_tools#28]
If an upload fails or is in progress and you go to http://www.mapillary.com/map/upload it'll suggest to push to Mapillary. There is no way to see which images will be pushed to Mapillary. Will the "Clear all images" button clear all the files uploaded and not pushed yet?
![mapillary___manual_upload_and_python_ _python_ _133x71_and_shaunmcdonald_ _bash_ _113x48_and_shaunmcdonald_ _bash_ _144x46](https://cloud.githubusercontent.com/assets/82719/5606074/dbe81af2-9413-11e4-8e62-ade4ac30be42.png)

**Comment by jesolem** [comment]
We added tabs in the web uploader so you can see and finalize each sequence separately. Sorry for the delay in answering. Thanks @smsm1
