### ISSUE TITLE
Mapillary failed to recognize the geo location info of the picture

### ISSUE THREAD

**Issue by aquawill** [mapillary/mapillary_tools#287]
### Basic information
* Upload interface: Mapillary official website.
* System: Windows
* Capture Device: Dashcam with custom conversion tool to extract the video frames and inject geo location info.

I've developed an small app which can convert the video files recorded by the dashcam to series of images, if the dashcam can collect gps trace, it will also parse the gps trace (NMEA/GPX) then write the geo location info to the corresponding image.
Today I'm trying Mapillary and found Mapillary can't recognize the geo tag of the image, however I uploaded to Google Photo and the location of the image can be shown correctly. Example: https://photos.app.goo.gl/yL6qe87EkavzVY1w6
Image set: https://photos.app.goo.gl/Qw639wskadqoH1Ev6
Would you please indicate which part of the image is missing? what should I do?
The second question is: can I bundle "upload to Mapillary" with my app so that the user can decide to automatically upload the result to Mapillary if preferred?

![2018-09-03_9-50-45](https://user-images.githubusercontent.com/20334897/45143345-a0539d80-b1ed-11e8-9621-a0dd95d7b857.png)
![a1111-1](https://user-images.githubusercontent.com/20334897/45143348-a0539d80-b1ed-11e8-9294-0dd292b5043c.jpg)
![a1111-2](https://user-images.githubusercontent.com/20334897/45143349-a0ec3400-b1ed-11e8-85c0-6f5b0f0ef52c.jpg)
![a1111-3](https://user-images.githubusercontent.com/20334897/45143350-a0ec3400-b1ed-11e8-8902-bd9b12f34935.jpg)
![a1111-51](https://user-images.githubusercontent.com/20334897/45143352-a184ca80-b1ed-11e8-96d8-53faf923d367.jpg)

**Comment by jernejaMislej** [comment]
hi, sorry for the late reply.
the error message says that images are missing required EXIF data, which is not limited to gps data.
In case of your images, they are missing the capture time. So you should insert that as well in the `Date/Time Original` EXIF tag
let me know if  that doesnt work out otherwise please close issue since the geo location is recognized
