### ISSUE TITLE
Erroneously uploaded thumbnails

### ISSUE THREAD

**Issue by blaueente** [mapillary/mapillary_tools#29]
I have created thumbnails for all the mapillary images, in the same directory, and then used upload.py mistakenly on the whole directory without deleting those thumbnails before. Apparently the thumbnails still had all the exif info.
The result is that some of the images are represented by those very low-res thumbnails instead of the original resolution images.
Re-uploading all (non-thumbnail) images did help to some extent, but some images are still thumbnails,
e.g. http://www.mapillary.com/map/im/DDmQdG7j3gQfOC_HkaO_cQ , but not the preceding or following picture, similarly http://www.mapillary.com/map/e/1NwogBL3zjruSd6o4nn1qg, or http://www.mapillary.com/map/e/u-sW2uJnYDl2PExXCWONOw
I do not have any idea to fix that from my side after the fact.

**Comment by chrismcnally** [comment]
I have used the Android app to edit one photo, by taping the edit button,
then if I scroll down to the bottom, there is a button to 'hide the
sequence'. Then you could upload again without the thumbnails.

**Comment by jesolem** [comment]
@blaueente Yes, easiest is to click 'edit' under one of the bad photos on the website and in the editor select 'hide the sequence'. Then upload without the thumbnails.

If there are only a few, you could hide them one by one too of course.

**Comment by blaueente** [comment]
Thanks for your recommendations. However, I have requested to hide the sequences, but after more than 24 hours they are still visible, so I guess it is no use to try uploading over 2 GB for a 3rd time.

**Comment by blaueente** [comment]
Finally, my hide requests were approved, and I have now re-uploaded all images.
