### ISSUE TITLE
Ignored tag: imagewidth and imagelength

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_tools#291]
### Basic information
* Release version: 0.2.0
* System: Windows 10
* Capture Device: GoPro 6

### Steps to reproduce behavior

 When processing the picture with the follwing command `python .\Scripts\mapillary_tools process --advanced --flag_duplicates --interpolate_directions --user_name <username> --import_path <path>`
  following error occurs: 
```
Warning, tag ImageLength ignored. The tag type is 3 which is not according to its standard type 4
Warning, tag ImageWidth ignored. The tag type is 3 which is not according to its standard type 4
```
Probably it's nothing really important, but it occurs for every image taken by my GoPro.

**Comment by jernejaMislej** [comment]
Hi, yes it’s no issue, it is a warning printed by our fork of the exif editing library piexif , since the tag type is not according to standard.
