### ISSUE TITLE
README.md error in sample_video example

### ISSUE THREAD

**Issue by cliffordsnow** [mapillary/mapillary_tools#292]
In the Video Sampling and Upload section of the readme, the instructions are ```
mapillary_tools sample_video --video_file "path/to/video_filename.mp4"``` 
It should be 
'''mapillary_tools sample_video --advanced --video_file "path/to/video_filename.mp4'```

mapillary_tools errors out if --advanced is left off. 

Please note, I'm just trying to figure out how to upload my video capture to mapillary so not to use the legacy video uploader.

**Comment by jernejaMislej** [comment]
hi thank you for pointing out, I added the missing argument. Let me know if there is anything else you are having issues with.
