### ISSUE TITLE
Web browser uploads ( sometimes ) failing today -- 2018/14/10

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_tools#293]
Web browser uploads are sometimes failing.  When the upload is done, sometimes the browser gives a message that a server error occured, try again.   Successive tries from that screen always fail.  Sometimes I can open a new browser, upload the same sequence, and it then goes fine.

**Comment by Kaldea** [comment]
Hey @AllenGraetz -- we're looking into this-- When I hear more I will let you know. Could you possibly send me an email at support@mapillary.com so I can reach you as soon as I get an update? Thanks!

**Comment by jernejaMislej** [comment]
hi, if you have any mapillary_tools issues let me know, otherwise i will close this, since it is not related to mapillary_tools
