### ISSUE TITLE
Authenticate using OSM credentials

### ISSUE THREAD

**Issue by lischenko** [mapillary/mapillary_tools#295]
### Basic information
* Release version: `0.2.0`
* System: MacOS
* Capture Device: GoPro

### Steps to reproduce behavior

 1. Run mapillary_tools process for the first time as a user that uses OAuth with OSM credentials 

### Expected behavior

Successful authentication

### Actual behavior

    Error, user authentication failed

### Corresponding data
N/A

### Additional information
I log into my Mapillary account with Openstreetmap account. Can I do the same with the mapillary_tools? How do I enter credentials; OSM ones are not being accepted, see below. It is entirely possible that I am missing something basic.

    $ mapillary_tools process --advanced --import_path "pic/" --user_name vlish --geotag_source "gpx" --geotag_source_path "20181021.gpx" --local_time
    unning user_process for 3399 images, skipping 0 images.
    Enter user credentials for user vlish :
    Enter email : lischenko@gmail.com
    Enter user password : 
    Error, user authentication failed for user vlish
    Make sure your user credentials are correct, user authentication is required for images to be uploaded to Mapillary.
    Sub process finished
    Running import_meta_data_process for 3399 images, skipping 0 images.
    Sub process finished
    Running geotag_process for 3399 images, skipping 0 images.
    Your local timezone is 2018-10-22 01:29:35 PDT. If not, the geotags will be wrong.
    Sub process finished
    Running sequence_process for 3399 images, skipping 0 images.
    Sub process finished
    Running upload_params_process for 3399 images, skipping 0 images.
    Enter user credentials for user vlish :
    Enter email : lischenko@gmail.com
    Enter user password : 
    Error, user authentication failed for user vlish

**Comment by lischenko** [comment]
Forgot to mention that the user exists: https://www.mapillary.com/app/user/vlish

**Comment by jernejaMislej** [comment]
hi @lischenko , thank you for reporting this.
my colleague @Kaldea will get back to you so we can first make sure the combination of username, email and password is correct

**Comment by lischenko** [comment]
I think I figured it out.

It seems that mapillary_tools can only "log in" with Mapillary password and not with OpenStreetMap, Facebook or Google (which is what you can do on the website and in the iOS app). As a customer, I have only ever logged in with OpenStreetMap account and never had (or knew) the Mapillary password.

So the workaround is to use a browser to log in to mapillary.com using whatever auth provider you have, and reset the password on Dashboard > Change password > Send reset mail

I can think of two way to improve it:

- Add an option to specify auth provider to mapillary_tool 
- At least modify README.md to make it clear that the tool assumes mapillary password auth, and providing instructions on resetting the password for those who don't have it.

**Comment by jernejaMislej** [comment]
hi, thank you for the feedback. Yes at the moment only mapillary credentials can be used in the tools , I will update the README to be clear on this. If we ever support other credentials we will inform you.
Let me know if you have any other issue with the tools.

**Comment by ptpt** [comment]
> At least modify README.md to make it clear that the tool assumes mapillary password auth
This is added in the README
