### ISSUE TITLE
Processing images with a time offset rewrites EXIF DateTimeOriginal

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_tools#297]
When using the `mapillary_tools` script to geotag images with a time offset, the `DateTimeOriginal` EXIF tag is overwritten with the offset applied. This makes it no longer **Original** and can mess up image ordering.

My GoPro Hero 5 has a flaky GPS antenna. So sometimes I have to geotag some portion of images in a sequence while other portions are already tagged and I only have to interpolate direction on those. Tonight I have been working on a sequence where I crossed a time zone so the Garmin and the camera were off by 1 hour (plus a couple of seconds). One image started out with a timestamp of:  
`Date/Time Original              : 2018:07:16 06:48:23`  
Then I ran the geotag script:  
`mapillary_tools process --advanced --user_name toebee --geotag_source gpx --local_time --geotag_source_path ../TdW_day2.gpx --offset_time -3596 --import_path 01/`
After the script ran, the timestamp now reads:  
`Date/Time Original              : 2018:07:16 07:48:19.000`

This is a problem because I have another image later in the sequence that is already geotagged with a timestamp of 07:48:19. So if I open up the mapillary tagged images and the camera tagged images in JOSM and try to step through the sequence, it starts alternating between images that were taken an hour apart from each other. 

Sometimes I also run the geotagging script several times to see and adjust the time offset. If I run it with an offset of -5 seconds the first time and then decide it should actually be -7 seconds instead, I have to use -2 instead of -7

I believe the upload script also keys off of the EXIF timestamp so it would cause ordering problems there too. For now I am splitting images into separate directories when I have to do some manual geotagging.

I'm guessing this was written intentionally as a feature but IMO as much of the original data as possible should be preserved when running the geotagging script.

### Basic information
* Release version: `0.2.0`
* System:  `Linux`
* Capture Device:  `Action Camera`

**Comment by jernejaMislej** [comment]
Hi, thank you for opening the issue and pointing this out.
I will have a look at how can this be improved and let you know as soon as there is any progress.

**Comment by jernejaMislej** [comment]
hi, I will fix this with the next release, in the mean time you can pass the arg `--keep_original` which will keep the original image intact and instead overwrite the EXIF of a copy

**Comment by jernejaMislej** [comment]
hi i changed the process flow so that it by default only edits Image Description tag, required to store mapillary data, while leaving the rest of tags with the original value.
If you want the rest of the tags to be overwritten with the values obtained in the process, you can pass the arg `--overwrite_EXIF_tags`. currently the change is on branch for next release v0.3.0 which is planned end of this week.
let me know if this is ok for you and if you have any more issues

**Comment by ToeBee** [comment]
Does this include the GPS tags? Generally I **do** want to set those if I am running the geotag script so that I can use them locally in JOSM or whatever else.

**Comment by jernejaMislej** [comment]
yes it includes those also. so you would want to keep the original values of certain tags, but overwrite others?

**Comment by jernejaMislej** [comment]
hi, i made an update in the branch for next release to have more options regarding overwriting the rest of EXIF tags.
so by default only Image Description will be overwritten, this is required so we get the mapillary data in,
if you pass `--overwrite_all_EXIF_tags`, it will overwrite all the rest of EXIF tags whose values are changed during `process` 
if you wish to overwrite only certain tags then you can pass one or more of these:
``` 
--overwrite_EXIF_time_tag
--overwrite_EXIF_gps_tag
--overwrite_EXIF_direction_tag
--overwrite_EXIF_orientation_tag
```

here is the help of all the args you might be interested in which would help control what gets overwritten and how to preserve original data, but still get results from `process`. Just a note that if you `--skip_EXIF_insert` no data will be inserted in the Image Description and images can not be uploaded, but you will get the data from `process` in the .mapillary directory in jsons.

```
  --skip_EXIF_insert    Skip inserting the extracted data into image EXIF.
  --keep_original       Do not overwrite original images, instead save the
                        processed images in a new directory called
                        "processed_images" located in .mapillary in the
                        import_path.
  --overwrite_all_EXIF_tags
                        Overwrite the rest of the EXIF tags, whose values are
                        changed during the processing. Default is False, which
                        will result in the processed values to be inserted
                        only in the EXIF Image Description tag.
  --overwrite_EXIF_time_tag
                        Overwrite the capture time EXIF tag with the value
                        obtained in process.
  --overwrite_EXIF_gps_tag
                        Overwrite the gps EXIF tag with the value obtained in
                        process.
  --overwrite_EXIF_direction_tag
                        Overwrite the camera direction EXIF tag with the value
                        obtained in process.
  --overwrite_EXIF_orientation_tag
                        Overwrite the orientation EXIF tag with the value
                        obtained in process.
```

**Comment by ToeBee** [comment]
Well that will certainly do it. I might have to write a small wrapper shell script to manage all the standard command line arguments I use but that isn't a problem :)
