### ISSUE TITLE
GoPro Video Processing: Geotagging failed

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_tools#299]
### Basic information
* Release version: `0.2.0`
* System: `Windows` 
* Capture Device: `GoPro`

### Steps to reproduce behavior
Processing a video captured with GoPro 5, 4K resolution, GPS enabled

1. Run sample command from README:
`python` mapillary_tools video_process --import_path D:\Images\Videos --video_file  D:\Images\Videos\GOPR0666.MP4 --video_sample_interval 0.2 --user_name canadarunner --advanced --geotag_source "gopro_video" --geotag_source_pathD:\Images\Videos\GOPR0666.MP4 --interpolate_directions`

### Actual behavior

After correct sampling of the videos to frames is done, follwing warning messages appear:

`Warning, sequence process failed for image D:\Images\Videos\.mapillary\sampled_video_frames\GOPR0666.MP\GOPR0666.MP_001350.jpg, therefore it will not be included in the upload params processing.`

`Warning, required geotag_process failed for image D:\Images\Videos\.mapillary\sampled_video_frames\GOPR0666.MP\GOPR0666.MP_002659.jpg`v

After running the same command again, the follwing warning was displayed, with in the beginning the advice to run, if problems occure, the command with the additional paramater `--local_time`

`Warning, time t not in scope of gpx file, interpolation of latitude and longitude failed for image D:\Images\Videos\.mapillary\sampled_video_frames\GOPR0666.MP\GOPR0666.MP_000522.jpg`v

And after rerunning the command with `--local_time`, following error occurs:

`Video sampling path set to D:\Images\Videos\.mapillary\sampled_video_frames\GOPR0666.MP
Warning, D:\Images\Videos\GOPR0666.MP4 has already been sampled into D:\Images\Videos\.mapillary\sampled_video_frames\GOPR0666.MP, please make sure all the previously sampled frames are deleted, otherwise the alignment might be incorrect
Running user_process for 0 images, skipping 2663 images.
No images to run user process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Sub process finished
Running import_meta_data_process for 0 images, skipping 2663 images.
No images to run import meta data process
If the images have already been processed and not yet uploaded, they can be processed again, by passing the argument --rerun
Sub process finished
Running geotag_process for 2663 images, skipping 0 images.
Traceback (most recent call last):
  File "mapillary_tools", line 60, in <module>
    command.run(args)
  File "D:\PyEnv\lib\site-packages\mapillary_tools\commands\video_process.py", line 131, in run
    **({k: v for k, v in vars_args.iteritems() if k in inspect.getargspec(process_geotag_properties).args}))
  File "D:\PyEnv\lib\site-packages\mapillary_tools\process_geotag_properties.py", line 103, in process_geotag_properties
    verbose)
  File "D:\PyEnv\lib\site-packages\mapillary_tools\processing.py", line 171, in geotag_from_gopro_video
    verbose)
  File "D:\PyEnv\lib\site-packages\mapillary_tools\processing.py", line 218, in geotag_from_gps_trace
    .format(now.strftime('%Y-%m-%d %H:%M:%S %Z')))
  File "D:\PyEnv\lib\site-packages\dateutil\tz\_common.py", line 22, in adjust_encoding
    name = name.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)`

*****

So what is the correct way to process the GoPro videos with embeded GPS in one go?

**Comment by jernejaMislej** [comment]
hi, 
you can try to rerun(`--rerun`) the `process` command only, since the video frames have been extracted and tagged with a capture time already, if you are having issues with the misalignment of the video and gps capture time, you can add `--use_gps_start_time`, since gps is extracted from the video, it should be correct

**Comment by SchmidL** [comment]
hi, I run the command again, with using `--use_gps_start_time` and it worked fine 👌🏻
so the working command is: 
`python mapillary_tools video_process --import_path D:\Images\Videos --video_file D:\Images\Videos\GOPR0666.MP4 --video_sample_interval 0.2 --user_name canadarunner --advanced --geotag_source "gopro_video" --geotag_source_pathD:\Images\Videos\GOPR0666.MP4 --interpolate_directions --use_gps_start_time`
