### ISSUE TITLE
App crashes android 8.1.0 build 011019

### ISSUE THREAD

**Issue by jepz1** [mapillary/mapillary_tools#300]
Sorry for not using the template, too tech for me.

The app for photographing worked great 2 times, now it freezes the system so I must restart the phone.

Any specifics, plz detail on how I can provide them.

Thanks for this wonderful project!

**Comment by jepz1** [comment]
Additional info, a few minutes the app takes its photo's, then the phone is frozen.

**Comment by Kaldea** [comment]
Hey @jepz1 -- This repo is dedicated for issues with mapillary_tools. Can you send an email of your issue to support@mapillary.com? Please include the phone make/model, app version & logs (if Android) and any screenshots or steps taken to recreate this. Thanks!

**Comment by jepz1** [comment]
Willdo, thanks.
