### ISSUE TITLE
Ability to provide input files on file level

### ISSUE THREAD

**Issue by angelday** [mapillary/mapillary_tools#304]
Currently tools accept flat folders only. (No recursive folders.)

We should allow standard filenames as input.

`*.jpg`
`filename1.jpg` `filename2.jpg` `filename3.jpg`

This would also allow for Unix standard filename sets, file name exclusion, file number ranges etc. Much more versatile than just limiting to one flat folder and also currently the Desktop Uploader is only usable if you drop a folder on top of it, individual files don't work.

**Comment by tohaklim** [comment]
Commenting only on the last point of yours: if you mean the web uploader (judging by your “drop” reference), that certainly supports individual files

**Comment by angelday** [comment]
Yes, the web version works as expected.

**Comment by angelday** [comment]
Closing, wrong repo.
