### ISSUE TITLE
Feature request - speed argument

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#309]
My particular work-flow is to "just drive whilst recording", rather than pick particular routes with defined start/stop points. As more contributors come on line it will be handy to have some method to rough cut parking areas, private places or similar prior to upload.

I suggest that a minimum capture speed with deceleration component (to catch street signs at corners) be included in the tools or at least speed be available as an EXIF field for later processing (For BlackVue). I currently use below 18kph until 8kph is reached, allowing a maximum of 8 seconds to get there. Duplicates_distance wont solve this.

**Comment by jernejaMislej** [comment]
@josealb is there any update here?

**Comment by josealb** [comment]
Hello @bob3bob3, what is the main reason you would need a minimum speed feature?
Duplicate distance has improved now since we don't take into account angle difference when processing BlackVue data, so you should see a lot less duplicate images there.

**Comment by josealb** [comment]
Ok @bob3bob3 that makes sense. I'm just not sure of how good a predictor the driving speed is of whether this is a private or non useful area. This could trigger with slow vehicles, traffic jams, etc.
But we could add this as an option for cases like yours when you know that would help.

**Comment by bob3bob3** [comment]
@josealb Agreed not directly, but it makes it easier to use driving method as a rough editor. Example if I keep my speed below (say) 15kph in a car park, I know data won't upload.

I briefly looked at the code and noted pynmea2 doesn't extract speed, possibly only relying on GPGGA (Only GPRMC contains speed). Might be easier to just calculate with a pass through the generated gpx file?

tnx

**Comment by josealb** [comment]
> Agreed not directly, but it makes it easier to use driving method as a rough editor. Example if I keep my speed below (say) 15kph in a car park, I know data won't upload.

sounds good

>  Might be easier to just calculate with a pass through the generated gpx file?

yes, we have this functionality already to check for uploads with speeds unplausibly high that may indicate geotagging errors

**Comment by bob3bob3** [comment]
old
