### ISSUE TITLE
BlackVue firmware warning DR900S 1.001 to 1.008 - breaks tools 0.3.1.

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#310]
Be aware that updating BlackVue firmware may change the mp4 output such that the default 0.3.1 (video_process) tools fails on geotag. The basic reason is that the (initial) GPRMC data use to come before the GPGGA, this has now reversed. The 0.4.0 branch seems to solve this.

**Comment by jernejaMislej** [comment]
@josealb can you update here, is this resolved and will be released in 0.4.0?

**Comment by josealb** [comment]
@jernejaMislej yes, this is solved in 0.4.0, the order doesn't matter now. 
thank you @bob3bob3 for the information about this being related to the firmware.

**Comment by jernejaMislej** [comment]
hi @bob3bob3 as this was resolved in latest release i m closing this issue, but do reopen or open a new issue if you get anymore of these problems
