### ISSUE TITLE
BlackVue mp4 to jpg extraction quality - Info only

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#311]
Only posted as information of interest.

The 4K size mp4 to jpg conversion via ffmpeg yields fairly low quality images when viewed 1:1.

- Using -qscale:v 1 -qmin 1 -qmax 1 yields a slightly better image approximately 50% larger

- Extracting key or index frames only is a very large improvement. Unfortunately the BlackVue only seems to create these at 1FPS. Use -vf "select=eq(pict_type\,I)" -vsync vfr -qscale:v 1 -qmin 1 -qmax 1

**Comment by jernejaMislej** [comment]
Hi, thank you for the information.

**Comment by bob3bob3** [comment]
Old...
