### ISSUE TITLE
Delay beetween any actions made by the script

### ISSUE THREAD

**Issue by CorentinLemaitre** [mapillary/mapillary_tools#321]
### Basic information
* Release version: 0.3.1
* System: `Windows`
* Capture Device: Compact Camera

### Steps to reproduce behavior

 1. 2000 Pictures with geolocation divided in 300 sequences.
 2. I use the Mapillary tools in command line. Version 0.3.1. I use to process and upload folder and subfolder.
 3. Between each step and each sequence upload i see 5 seconds of pause.

### Expected behavior
I would like that the script do not stop 5 seconds between each sequence. The script can stop just at the end of a process or at the end of a sub process. 
It is not really relevant for one sequence upload but it would be great if we could add an option to make no stop. 

### Actual behavior
I have an upload process for 2 or 3 seconds and then 5 seconds without change, another upload, and 5 seconds... It double the time to upload, event if it is not common use to have so small sequence.

**Comment by CorentinLemaitre** [comment]
Hello @josealb 
Usually i put my picture on a SSD folder. I go to it in windows explorer and then i type on the adress bar cmd to get a terminal with the good location for photo. 
Then i copy paste this command or similar (changing offset angle or other advanced parameters) : 
`
F:\mapillary_tools process_and_upload --advanced --import_path "/" --user_name "c_mobilite"  --interpolate_directions --offset_angle 0 
`

**Comment by josealb** [comment]
Understood @CorentinLemaitre I think this is just the software finishing some internal logging. It just doesn't show anything in the command line.
We have a plan to improve performance that will reduce the duration of these events.
