### ISSUE TITLE
HTTP error: HTTP Error 403: Forbidden on

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#328]
### Basic information
* Release version: `master`
* System: `Linux`
* Capture Device: `Action Camera`

### Steps to reproduce behavior

 1. > ./bin/mapillary_tools process_and_upload --advanced --import_path /tmp/2019_02_23_14_46_37_756_+1100/ --user_name "aharvey" --interpolate_directions

### Actual behavior

```
...
Process done.
Uploading 546 images with valid mapillary tags (Skipping 0)
Uploading 1. sequence with 8 threads
HTTP error: HTTP Error 403: Forbidden on 2019_02_23_14_46_56_931_+1100.jpg, will attempt upload again for 24 more times
HTTP error: HTTP Error 403: Forbidden on 2019_02_23_14_47_05_806_+1100.jpg, will attempt upload again for 24 more times
...
```

### Additional information

.config/mapillary/config is still present

**Comment by alexandrz** [comment]
Getting the same error on MacOS. Mapillary tools version : 0.4.2

**Comment by alexandrz** [comment]
Also, tried to re-authenticate, but ti didn't help.

**Comment by alexandrz** [comment]
Now it is uploading after re-running processing with `--interpolate_directions` option.

**Comment by josealb** [comment]
@andrewharvey we made some changes to the upload, it could be that your system still has the old upload key
Steps to fix that are:
1. Remove Mapillary credentials by deleting .config file. Default is `~/.config/mapillary/config`
2. Run process again on each folder re-authenticating when prompted
3. Upload reprocessed imagery.

Please let us know if that fixes the issue

**Comment by andrewharvey** [comment]
Thanks @josealb that fixed the issue.

**Comment by josealb** [comment]
Great to hear @andrewharvey thanks for the feedback
