### ISSUE TITLE
[process] --orientation is ignored if equal to 0

### ISSUE THREAD

**Issue by nheir** [mapillary/mapillary_tools#329]
Since --orientation is either 0,90,180 or 270, 
```python
if orientation:
    ...
```
should be something like
```python
if orientation is not None:
    ...
```
in

https://github.com/mapillary/mapillary_tools/blob/2c05db33fd3ea2d00b76821edb1368130327d2c5/mapillary_tools/process_import_meta_properties.py#L214-L215

**Comment by josealb** [comment]
@nheir good catch, thanks for letting us know. It's fixed now and pushed for the next release
