### ISSUE TITLE
upload_with_authentication.py does not work with exifread 2.0.0

### ISSUE THREAD

**Issue by wimh** [mapillary/mapillary_tools#33]
After upgrading exifread to version 2.0.0 upload_with_authentication.py does not work any more, for example:

    Uploading sequence 6cfdfb62-2ff3-4817-842e-c217d1b84b23.
    Missing required EXIF tag: GPS GPSLongitude
    Skipping: /home/wh/virb/20150120/1/VIRB0200.JPG
    ===
    Finalizing upload will submit all successful uploads and ignore all failed.

Possibly upload.py has the same error, but I did not test.

As a workaround, I downgraded exifread:

    pip install exifread==1.4.2

That fixed the problem. I did not spend time yet on examining the real cause.

**Comment by ybkuang** [comment]
@winh, the problem is that exifread changed its naming format for GPS in 2.0.0. I am on it.
