### ISSUE TITLE
authentication seems do be broken

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_tools#337]
I made the mistake to update to the current mapillary tools. Since then I receive a authentication error. I'm certain there is no type in the login credentials and since I can log in on the website I don't know why the script thinks the credentials are wron.

**Comment by kratico** [comment]
@bitnapper Could you provide the console output?

**Comment by bitnapper** [comment]
Shure:

Error, user authentication failed for user XXX

**Comment by bitnapper** [comment]
How to download the old script? The new one tells me that the images are already processed but they are not grouped in folders which was very helpful for revising them before uploading hundreds of photos of the same parking lot.

**Comment by kratico** [comment]
@bitnapper Could you try to re-authenticate with?
```
mapillary_tools --advanced authenticate --force_overwrite
```

By the way, which revision or commit hash are you using?

**Comment by eneerhut** [comment]
@bitnapper not sure if it's a related issue, but I often copy and paste upload commands to notes on macOS. This can lead to the quotation marks being formatted differently when I paste them into terminal.

When they're formatted weirdly I get the same authentication error, but when I correct them authentication is successful.

Notice the difference between the top and bottom quotation here:
![image](https://user-images.githubusercontent.com/11349863/56709736-3250ec00-6766-11e9-8282-c8ef64544b92.png)

**Comment by joostschouppe** [comment]
This forced authentication thing saved my day (see https://forum.mapillary.com/t/command-prompt-tools-exits-due-to-not-obtaining-organization-key/4714/2). Might be a good idea to add it in the extended help and the readme :)

**Comment by ptpt** [comment]
The issue should be gone as we upgrade our platform. Please make sure you reset your password if you haven't https://blog.mapillary.com/update/2021/05/28/password-update.html and upgrade your tools to 0.7.0
