### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_tools#34]
When trying to upload i get this:

Uploading sequence 8994b835-6ff5-4f7a-ad76-d8cbef4d574f.
Uploading: tt_img_00280.jpg
Uploading: tt_img_00275.jpg
Uploading: tt_img_00263.jpg
Uploading: tt_img_00281.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00281.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00281.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00275.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00280.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00281.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00263.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00281.jpg
Uploading: tt_img_00267.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00275.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00280.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00263.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00267.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00275.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00280.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00263.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00275.jpg
Uploading: tt_img_00259.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00280.jpg
Uploading: tt_img_00266.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00267.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00259.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00263.jpg
Uploading: tt_img_00268.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00267.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00266.jpg
HTTP error: HTTP Error 403: Forbidden on tt_img_00259.jpg
^C
BREAK: Stopping upload.

**Comment by geomapper69** [comment]
@Alessandro-Barbieri I assume you are uploading with: upload_with_authentication.py ?
Are you using the latest version updated 19 days ago ?
MAPILLARY_UPLOAD_URL = "https://s3-eu-west-1.amazonaws.com/mapillary.uploads.manual.images"

**Comment by Alessandro-Barbieri** [comment]
Yes i'm using upload_with_authentication.py
With latest (git pull) i get

Uploading sequence 793062b9-7195-4778-a7ab-0a26000a478a.
Uploading: 2014-10-02 10.29.27.jpg
Uploading: 2014-10-02 10.29.39.jpg
Uploading: 2014-10-02 10.29.04.jpg
Uploading: 2014-10-02 10.29.35.jpg
URL error: <urlopen error [Errno 104] Connection reset by peer> on 2014-10-02 10.29.35.jpg
HTTP error: HTTP Error 403: Forbidden on 2014-10-02 10.29.39.jpg
HTTP error: HTTP Error 403: Forbidden on 2014-10-02 10.29.35.jpg
^C
BREAK: Stopping upload.

**Comment by Alessandro-Barbieri** [comment]
missclick

**Comment by geomapper69** [comment]
The only thing I can think of is that it is not recognising your login details.
Double check environment variables MAPILLARY_USERNAME, MAPILLARY_PERMISSION_HASH and MAPILLARY_SIGNATURE_HASH.
The HASHes should not have any quotations ( ' )

**Comment by Alessandro-Barbieri** [comment]
From http://api.mapillary.com/v1/u/uploadhashes hashes should have = or == at the end?
I removed " and = character and still get the same error.

**Comment by geomapper69** [comment]
It should have = at end do not delete that.

**Comment by Alessandro-Barbieri** [comment]
I had to use 
'''bash
export MAPILLARY_PERMISSION_HASH=hash
'''
and not

'''bash
MAPILLARY_PERMISSION_HASH="hash"
'''
now works
