### ISSUE TITLE
Process GoPro footage - blackvue error

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_tools#343]
### Basic information
* Release version: `0.5.0` 
* System: `Windows`
* Capture Device: `GoPro Hero 7 Black`

### Steps to reproduce behavior
Running the following command from the README

### Expected behavior
`python mapillary_tools video_process --import_path "path to image folder" --video_import_path "path to video folder" --user_name canadarunner --advanced --geotag_source "gopro_videos" --geotag_source_path "path to video folder" --interpolate_directions --video_sample_interval 0.1 --overwrite_EXIF_gps_tag`

### Actual behavior
Error:
```
Traceback (most recent call last):
  File "./Scripts/mapillary_tools", line 76, in <module>
    command.run(args)
  File "C:\Users\schmidl\.conda\envs\mapillary\lib\site-packages\mapillary_tools\commands\video_process.py", line 144, in run
    vars_args = apply_camera_specific_config(vars_args)
  File "C:\Users\schmidl\.conda\envs\mapillary\lib\site-packages\mapillary_tools\apply_camera_specific_config.py", line 3, in apply_camera_specific_config
    if "device_make" in vars_args and vars_args['device_make'].lower()=='blackvue' or "geotag_source" in vars_args and vars_args["geotag_source"] == 'blackvue_videos':
AttributeError: 'NoneType' object has no attribute 'lower'
```

What do I wrong, because I'm not processing blackvue footage at all...

**Comment by jernejaMislej** [comment]
hi sorry for this, i pushed a fix, can you please update the tools and try again

**Comment by SchmidL** [comment]
hi, now it works! Thanks! 👍
