### ISSUE TITLE
Severe "spider-web" after GoPro upload

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_tools#347]
### Basic information
* Release version: `0.5.0`
* System: `Windows` 
* Capture Device: `GoPro Hero 7 black`

### Steps to reproduce behavior

 1. Process the all GoPro Video with the following command:
`
python mapillary_tools video_process --import_path D:\mapillary_image_extracted --video_import_path D:\mapillary_video --user_name <<username>> --advanced --geotag_source "gopro_videos" --geotag_source_path D:\mapillary_video --interpolate_directions --video_sample_interval 0.5 --use_gps_start_time --device_model "H7black" --device_make "GoPro" --overwrite_EXIF_gps_tag --duplicate_distance 0.1 --duplicate_angle 5
`
 2. Upload the images with: 
`python mapillary_tools upload --import_path D:\mapillary_image_extracted `
 3.

### Actual behavior

The uploaded images are shown as huge spider-web, with really non-sense connection and are splitted into small sequences as seen here: https://www.mapillary.com/app/?lat=47.69493996566962&lng=8.63057106860083&z=16.426163294765434

**Comment by ptpt** [comment]
The GPS anomaly from GoPro should be fixed since https://github.com/mapillary/mapillary_tools/releases/tag/v0.9.4
