### ISSUE TITLE
[Question] how to get the spatial bounds of the result of search api?

### ISSUE THREAD

**Issue by cocoaaa** [mapillary/mapillary_tools#353]
Hi, I'm trying to compute the bounding box of an image returned by Mapillary's api, in particular the `search_images` function. For instance:  `response = mmap.search_images(bbox=bbox, per_page=5)`.
The `response` has a `geometry`.`coord` property, but I couldn't find any other meta data (such as transformation matrix, spatial resolutions in x and y direction))which would be needed to compute the bounds of the searched image. Could you let me know if there is a way to get these meta data?  Thank you!

**Comment by ptpt** [comment]
The returned coordinates for an image are wgs84 (longitude, latitude).

To compute the bounds of the returned images, just find the maximum/minimum longitude and maximum/minimum latitude and then [min_longitude, min_latitude, max_lonitude, max_latitude] is your bounds.

Note that Mapillary API is updated to https://www.mapillary.com/developer/api-documentation
