### ISSUE TITLE
README should mention that apt package 'python-dev' is required

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_tools#354]
I tried to install mapillary_tools on Ubuntu 18.04.

When running `pip install --upgrade git+https://github.com/mapillary/mapillary_tools` I got a lot of errors of the following form:

```
    In file included from libImaging/Imaging.h:14:0,
                     from libImaging/PcxDecode.c:17:
    libImaging/ImPlatform.h:10:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
```

After running

```bash
sudo apt install python-dev
```

the errors disappeared.

I suggest to mention in the README that the apt package `python-dev` is required.

**Comment by ptpt** [comment]
This is related to the old version of Pillow. The latest version 0.6.0 on master should fix it.
