### ISSUE TITLE
organization_username option ignored by send_videos_for_processing command

### ISSUE THREAD

**Issue by govvin** [mapillary/mapillary_tools#357]
### Basic information
* Release version: `0.5.0`
* System: `Linux` 
* Capture Device: `DR900`

### Steps to reproduce behavior

 1. process and upload using mapillary_tools -- `mapillary_tools send_videos_for_processing --advanced --video_import_path "/media/user/Transcend/backup/Imagery Collection/folder/2019-10-25" --user_name "user" --organization_username "org"`

### Expected behavior
consistency with how other commands use --organization_username option, the value for this setting should reflect on the uploads

### Actual behavior
the value is actually ignored. A file called "DONE" which appears to be a config ignores the --organization_username option.

Copy is attached for reference.

### Corresponding data
[DONE.zip](https://github.com/mapillary/mapillary_tools/files/3914418/DONE.zip)

**Comment by vinber** [comment]
Hi, very interested on this issue.

And do you have some bugs like #367 when you use send_videos_for_processing as recommended ?

**Comment by ptpt** [comment]
Hey, please upgrade to 0.7.0 and use video_process instead as send_videos_for_processing is removed.
