### ISSUE TITLE
Upload failed with HTTP Error 403: Forbidden on <picturenumber>.jpg

### ISSUE THREAD

**Issue by julietkilo** [mapillary/mapillary_tools#358]
### Basic information
* Release version: Mapillary tools version : 0.5.0
* System: `Linux` Ubuntu Eoan
* Capture Device: `Action Camera` Gopro Hero7 Black 

### Steps to reproduce behavior

 1. Reset the existing config as mentioned in other issues:  rm -rf ~/.config/mapillary
 2. mapillary_tools video_process_and_upload --advanced --rerun --import_path ~/gopro/processed --video_import_path ~/gopro --geotag_source "gopro_videos" --geotag_source_path ~/gopro --interpolate_directions --video_sample_interval 0.5 --overwrite_EXIF_gps_tag --use_gps_start_time --user_name myusername

Also tried "video_process" instead of "video_process_and_upload" but the upload part fails with same error. The gps information inside EXIF tags of most of the processed pictures looks correct.
 
### Expected behavior
uploaded files

### Actual behavior

user@black:~$ mapillary_tools video_process_and_upload --advanced --rerun --import_path ~/gopro/processed --video_import_path ~/gopro --geotag_source "gopro_videos" --geotag_source_path ~/gopro --interpolate_directions --video_sample_interval 0.5 --overwrite_EXIF_gps_tag --use_gps_start_time --user_name myusername 
Extracting video frames:   0%|                                                                          | 0/1 [00:00<?, ?it/s]Video sampling path set to /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572
Running user_process for 1063 images, skipping 0 images.                                                                      
Enter user credentials for user myusername :
Enter email : my@email.com
Enter user password : 
Sub process ended                                                                                                             
Running import_meta_data_process for 1063 images, skipping 0 images.
Sub process ended                                                                                                             
Running geotag_process for 1063 images, skipping 0 images.
It is assumed that the image timestamps are in UTC. If not, try using the option --local_time.
Inserting gps data into image EXIF:   0%|                                                            | 0/1063 [00:00<?, ?it/s]time t not in scope of gpx file by 0.0 seconds, extrapolating...
Inserting gps data into image EXIF:  68%|████████████████████████████████▍               | 718/1063 [00:00<00:00, 2534.38it/s]time t not in scope of gpx file by 0.214 seconds, extrapolating...
time t not in scope of gpx file by 0.714 seconds, extrapolating...
Warning, time t not in scope of gpx file by 1.214 seconds, interpolation of latitude and longitude failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001060.jpg
Warning, time t not in scope of gpx file by 1.714 seconds, interpolation of latitude and longitude failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001061.jpg
Warning, time t not in scope of gpx file by 2.214 seconds, interpolation of latitude and longitude failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001062.jpg
Warning, time t not in scope of gpx file by 2.714 seconds, interpolation of latitude and longitude failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001063.jpg
Sub process ended                                                                                                             
Running sequence_process for 1063 images, skipping 0 images.
Loading geotag points:   0%|                                                                         | 0/1063 [00:00<?, ?it/s]Warning, geotag process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001060.jpg, therefore it will not be included in the sequence processing.
Warning, geotag process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001061.jpg, therefore it will not be included in the sequence processing.
Warning, geotag process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001062.jpg, therefore it will not be included in the sequence processing.
Warning, geotag process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001063.jpg, therefore it will not be included in the sequence processing.
Running sequence_process for 0 images, skipping 0 images.                                                                     
Warning: The distance in sequence including images                                                                            
/home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_000014.jpg
to
/home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001059.jpg
is too large for the time difference (very high apparent capture speed). Are you sure timestamps and locations are correct?
Sub process ended                                                                                                             
Running upload_params_process for 1063 images, skipping 0 images.
Processing image upload parameters:  83%|███████████████████████████████████████▉        | 884/1063 [00:00<00:00, 4359.43it/s]Warning, sequence process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001060.jpg, therefore it will not be included in the upload params processing.
Warning, sequence process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001061.jpg, therefore it will not be included in the upload params processing.
Warning, sequence process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001062.jpg, therefore it will not be included in the upload params processing.
Warning, sequence process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001063.jpg, therefore it will not be included in the upload params processing.
Sub process ended                                                                                                             
Running mapillary_image_description for 1063 images, skipping 0 images.
Inserting mapillary image description in image EXIF:  97%|█████████████████████████████▉ | 1028/1063 [00:01<00:00, 552.81it/s]Warning, required geotag_process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001060.jpg
Warning, required geotag_process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001061.jpg
Warning, required geotag_process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001062.jpg
Warning, required geotag_process failed for image /home/user/gopro/processed/mapillary_sampled_video_frames/GH010572/GH010572_001063.jpg
Sub process ended                                                                                                             
Process done.
Uploading 1047 images with valid mapillary tags (Skipping 16)
Uploading 1. sequence with 5 threads
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 49 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 48 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 47 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 46 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 45 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 44 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 43 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 42 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 41 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 40 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 39 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 38 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 37 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 36 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 35 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 34 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 33 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 32 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 31 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 30 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 29 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 28 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 27 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 26 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 25 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 24 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 23 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 22 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 21 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 20 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 19 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 18 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 17 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 16 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 15 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 14 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 13 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 12 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 11 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 10 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 9 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 8 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 7 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 6 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 5 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 4 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 3 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 2 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 1 more times
HTTP error: HTTP Error 403: Forbidden on GH010572_000001.jpg, will attempt upload again for 0 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 99 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 98 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 97 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 96 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 95 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 94 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 93 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 92 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 91 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 90 more times
HTTP error: HTTP Error 403: Forbidden on DONE, will attempt upload again for 89 more times
---interrupted by Strg+C---

**Comment by scaidermern** [comment]
Same problem for me.

Mapillary tools version : 0.5.0
System: Linux Debian testing

**Comment by scaidermern** [comment]
I tried the following:

- `rm -rf ~/.config/mapillary/`
- `rm -rf ~/my_photos/.mapillary/`
- `mapillary_tools authenticate --advanced --user_name me` (completed successfully)
- `mapillary_tools upload --import_parh ~/my_photos`

I still get `HTTP error: HTTP Error 403: Forbidden on foo.jpg` for each photo.

Is there anything else I can try?

**Comment by sorcrosc** [comment]
I want to tell my experience.
A few days ago I installed a new operating system from scratch and I was having this problem. There was nothing to do. The only thing that helped was to restore the key in ~/.config/mapillary/configs / from the old os.

**Comment by tohaklim** [comment]
Not sure if related, but the web uploader has been failing for some time now https://forum.mapillary.com/t/new-desktop-uploader/2466?page=3

**Comment by scaidermern** [comment]
> Not sure if related, but the web uploader has been failing for some time now https://forum.mapillary.com/t/new-desktop-uploader/2466?page=3

Thanks for the information. Looks like the web uploader has been fixed. The mapillary_tools upload is still failing for me, though.

**Comment by richlv** [comment]
Also having the same problem, but note that Mapillary might be ignoring this issue tracker: https://forum.mapillary.com/t/i-mapillary-closing-up/1756 .

**Comment by scaidermern** [comment]
> Also having the same problem, but note that Mapillary might be ignoring this issue tracker: https://forum.mapillary.com/t/i-mapillary-closing-up/1756 .

Good to know. I've created a forum thread for this issue: https://forum.mapillary.com/t/mapillary-tools-http-error-403-forbidden/3666

**Comment by scaidermern** [comment]
This issue is solved after updating to the newest version of mapillary_tools and performing the steps described in https://forum.mapillary.com/t/mapillary-tools-http-error-403-forbidden/3666/14.

**Comment by julietkilo** [comment]
Solved. Thanks to the mapillary team. The following steps works for me:

pip install --upgrade git+https://github.com/mapillary/mapillary_tools
mapillary_tools authenticate --advanced
mapillary_tools video_process_and_upload --advanced --rerun --import_path ~/gopro/processed --video_import_path ~/gopro --geotag_source "gopro_videos" --geotag_source_path ~/gopro --interpolate_directions --video_sample_interval 0.5 --overwrite_EXIF_gps_tag --use_gps_start_time --user_name m*****y
