### ISSUE TITLE
Unable to upload photos.

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_tools#361]
### Basic information
* Release version: `0.5.0`
* System: `MacOS`
* Capture Device: `Action Camera Sony`

### Steps to reproduce behavior

 1. Run: `mapillary_tools process_and_upload --import_path "/Mapillary/new photos" --user_name mapillary_user`

### Expected behavior

New photos are uploaded.

### Actual behavior

Getting errors:

```<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>2895E6234826BC31</RequestId><HostId>PAlslJetbH20D5ZcNFQ7LToeKerNndWOsCnZVs/YdP8qcwamIa0XG7X9W395ZMRgH0tmNXlSAZ0=</HostId></Error>
HTTP error: HTTP Error 403: Forbidden on DSC05165.JPG, will attempt upload again for 49 more times```

**Comment by alexandrz** [comment]
https://github.com/mapillary/mapillary_tools/issues/358#issuecomment-572540866

Following these steps resolved the issue.

**Comment by ptpt** [comment]
Thanks! Updating mapillary_tools will solve it.
