### ISSUE TITLE
Download images belonging to a single upload/recording session

### ISSUE THREAD

**Issue by srinathsibi** [mapillary/mapillary_tools#366]
### Basic information
* Release version: `0.5.0`
* System: `Linux` 
* Capture Device: `Apple` | `Android` | `Action Camera` 

### Steps to reproduce behavior

 1.mapillary_tools download --advanced --by_property key --import_path dev/null --output_folder "." --organization_keys "xxxxxxxxxxxxxxxx" --user_name "UserName" --start_time "2020-04-18" --end_time "2020-04-19"

### Issue

I would like to download images with time intervals as an added level of detail. What additional arguments would be needed for this?

**Comment by ptpt** [comment]
This command has been removed in 0.7.0. Closing.
