### ISSUE TITLE
Lag-Lapse due to mapillary servers

### ISSUE THREAD

**Issue by vinber** [mapillary/mapillary_tools#367]
### Basic information
* Release version: `0.5` 
* System: ``Linux` | 
* Capture Device: Blackvue dashcam DR900S-1CH

### Steps to reproduce behavior

https://forum.mapillary.com/t/lag-offset-with-blackvue-dr900s-1ch-dashcam-due-to-mapillary-server/3883/4

Recommended process : https://www.mapillary.com/app/?lat=44.7692010725&lng=-0.35790673833333336&z=17&feedItem=user-LG6IzKbs9VWeuSf14TZhaQ-activity-user-LG6IzKbs9VWeuSf14TZhaQ-publishing_done-image&tab=uploads&pKey=Zvrw98lptrBCTXRnX10xJe&focus=photo

locally -> video_process then upload with webapp : https://www.mapillary.com/app/?lat=44.7694075833125&lng=-0.35719925000012154&z=18.899924560393607&feedItem=user-LG6IzKbs9VWeuSf14TZhaQ-activity-user-LG6IzKbs9VWeuSf14TZhaQ-publishing_done-image&tab=uploads&pKey=3_c6X-QQSl6qoRuQaZwHpA&focus=photo

So lapse-lag is due to mapillary servers.

**Comment by ptpt** [comment]
This should be solve by the default cutoff_distance (600 meters).
