### ISSUE TITLE
Mapillary Tools on PyPi

### ISSUE THREAD

**Issue by DenisCarriere** [mapillary/mapillary_tools#37]
@jesolem @peterneubauer 

Instead of modifying the entire mapillary tools repo, I decided to create my own clean repo based from your Python tools, there is a lot of testing to be done before it's actually an official Mapillary API.

Once it's good enough as a release, you guys can fork it and pick it up from there.

http://deniscarriere.github.io/mapillary/

At the moment I only added the **Upload** feature, but I do plan on including @jesolem's GeoTag from GPX feature.

The end result would look something like this:

```bash
$ mapillary geotag --input "<File Path>" --gpx "path.gpx"
$ mapillary upload --input "<File Path>" --username "<Username>"
```

**Comment by jesolem** [comment]
Fantastic! Let us know how we can help.

**Comment by DenisCarriere** [comment]
Your welcome Jan, you guys have already done most of the hard work with
your Python tools, I'll continue to incorporate them in the API. If I have
some questions about your back end server I'll ask for sure.

**Comment by DenisCarriere** [comment]
@jesolem I've included your GeoTag feature in the Mapillary API

```bash
$ mapillary geotag "<File Path>" --gpx "<GPX File Path>"
```
Discussion on Twitter:
https://twitter.com/DenisCarriere/status/564506953385512960

**Comment by jesolem** [comment]
@DenisCarriere is there anything you want us to do here?

**Comment by DenisCarriere** [comment]
@jesolem Not really anything to action, but if you guys ever wanted to have the name "mapillary" on pypi, let me know and I can release it and you can take ownership of it. At the moment I'm not actively developing anything due to lack of time :)
Cheers,
- Denis

**Comment by jesolem** [comment]
OK. Thanks @DenisCarriere !
