### ISSUE TITLE
IOError: [Errno 13] Permission denied: 'path/to/gpx_file' [7944] Failed to execute script mapillary_tools

### ISSUE THREAD

**Issue by vitkomarovsky** [mapillary/mapillary_tools#371]
### Basic information
* Release version: `0.5.0` 
* System: `Windows 10 Pro 64-bit 1703`
* Capture Device: `Action Camera`

### Steps to reproduce behavior

 1. mapillary_tools process --advanced --import_path "path\to\images\mapillary_sampled_video_frames" --user_name "xxx" --geotag_source "gpx" --geotag_source_path "path/to/gpx_file" --overwrite_all_EXIF_tag

 2. mapillary_tools process --advanced --import_path "path\to\images\mapillary_sampled_video_frames" --user_name "xxx" --geotag_source "gpx" --geotag_source_path "path/to/gpx_file" --overwrite_all_EXIF_tag
 3.

### Expected behavior

...

### Actual behavior

Traceback (most recent call last):
  File "mapillary_tools", line 76, in <module>
  File "mapillary_tools\commands\process.py", line 145, in run
  File "mapillary_tools\process_geotag_properties.py", line 89, in process_geotag_properties
  File "mapillary_tools\processing.py", line 285, in geotag_from_gps_trace
  File "mapillary_tools\gps_parser.py", line 29, in get_lat_lon_time_from_gpx
IOError: [Errno 13] Permission denied: 'path/to/gpx_file'
[7944] Failed to execute script mapillary_tools

Traceback (most recent call last):
  File "mapillary_tools", line 76, in <module>
  File "mapillary_tools\commands\process.py", line 145, in run
  File "mapillary_tools\process_geotag_properties.py", line 89, in process_geotag_properties
  File "mapillary_tools\processing.py", line 285, in geotag_from_gps_trace
  File "mapillary_tools\gps_parser.py", line 29, in get_lat_lon_time_from_gpx
IOError: [Errno 13] Permission denied: 'path/to/gpx_file'
[1184] Failed to execute script mapillary_tools

### Corresponding data

* sample images
* meta data

...

### Additional information

Hello! I can’t extract GPS data from an external file with the gpx extension. In this case, the file is read without problems by GeoSetter. What's my mistake?

**Comment by vitkomarovsky** [comment]
> In your example the path separators switch between Unix and Windows/DOS convention?
> 
> Perhaps use a backslash to define the gpx path?

Thanks for the quick response. Maybe I don’t quite understand, but I did it like this

**Comment by vitkomarovsky** [comment]
Thanks for the quick response. Maybe I don’t quite understand, but I did it like this:

mapillary_tools process --advanced --import_path "path\to\images\mapillary_sampled_video_frames" --user_name "xxx" --geotag_source "gpx" --geotag_source_path "d:\path\to\gpx_file\" --overwrite_all_EXIF_tag

Here is the result:

Error, d:\path\to\gpx_file" --overwrite_all_EXIF_tag file source of gps/time properties does not exist. If geotagging from external log, rather than image EXIF, you need to provide full path to the log file.

In this case, the directory "d: \ path \ to \ gpx_file \" exists, there is a file with the extension gpx. What else can I apply?

**Comment by vitkomarovsky** [comment]
Thanks for the quick response! I tried to do something like this:

mapillary_tools process --advanced --import_path "path\to\images\mapillary_sampled_video_frames" --user_name "xxx" --geotag_source "gpx" --geotag_source_path "d:\path\to\gpx_file\" --overwrite_all_EXIF_tag

And I got this:

Error, d:\path\to\gpx_file" file source of gps/time properties does not exist. If geotagging from external log, rather than image EXIF, you need to provide full path to the log file.

What else can be done?

**Comment by bob3bob3** [comment]
I would suggest naming the gpx file specifically or adding a trailing slash. ie 

--geotag_source_path d: \path\to\gpx_file\file.gpx
or 
--geotag_source_path d: \path\to\gpx_file\

I remember having some trouble in the past with distinguishing between a directory of files vs just one file and ending up using a trailing slash (Unix). I think too that quotes are only needed if there are spaces 

--overwrite_all_EXIF_tag I think should also be plural, ie --overwrite_all_EXIF_tags

Sorry I cant be more specific. I have only every processed from BlackVue vids or jpegs with a full EXIF and never used a separate gpx file

**Comment by vitkomarovsky** [comment]
I understand you, thanks. Made a path with the name of the gpx file:

--geotag_source_path "d: \ path \ to \ gpx_file \ gps.gpx"

Here is the result:

Warning, required geotag_process failed for image D: \ path \ to \ images \ mapillary_sampled_video_frames \ front_20200606201859 \ front_20200606201859_000085.jpg

Well, he doesn’t want to. :(

**Comment by bob3bob3** [comment]
That message could be that the contents of the gpx file are not in the date/time range of that particular image. I get that with the BlackVue before the GPS has locked but is recording images. Only a small quantity of images are affected though.

 The tools I think can read the image capture time from a number of sources. The camera may be placing in the EXIF tag "Date and Time (Original)" so check that is valid and in UTC. The tools can read/use that.

**Comment by vitkomarovsky** [comment]
Your message opened a new thought to me: the date and time in the GPS file are recorded not in UTС, but in local time. Obviously, there is a problem. You are a smart person!
