### ISSUE TITLE
Only half of a mapillary map image are uploaded

### ISSUE THREAD

**Issue by Jakkajakka** [mapillary/mapillary_tools#380]
* System: `Windows 10` 
* image recorded GoPro 7 black

The windows https://tools.mapillary.com/binary/win/mapillary_tools.exe seems to upload the hole directory map 16.683 with in 17 subfolders. (max 999 in subfolder)
The issue is that only from every subfolder the half of the 999 image are show on mapillary map. 
It looks like the tool can only manage 500 images /folder....
See the log file.
[upload_overzicht.txt](https://github.com/mapillary/mapillary_tools/files/5251949/upload_overzicht.txt)

- Question when the exe is update how can we see with version is the latest.......
- in the release on the right zip file there is no .exe

**Comment by Jakkajakka** [comment]
Still no improvement. Do need to upload all again with the desktop uploader @ https://www.mapillary.com/desktop-uploader

**Comment by arocoun** [comment]
Is it possible that your device updates GPS coordinates at half the speed you're capturing images? In that case, half the images would overlap, and be weeded out as duplicates. 

I bring this up because I once took photos at 0.5 second intervals, and about 15% of them had duplicate GPS info.

**Comment by Jakkajakka** [comment]
That could be possible that this desktop-uloader needs different (more distance) gps info, I re-uploaded them true the web up loader and  they passed all the missing images ;) For the moment I use only the web uploader but takes more time you need still activate after preparing fase the upload button so it cannot run overnight.
