### ISSUE TITLE
How to configure credentials for a proxy ?

### ISSUE THREAD

**Issue by MaelREBOUX** [mapillary/mapillary_tools#381]
Hello

I'm working inside a LAN wich is using a big proxy to filter access to internet.
Every request going to the internet must be authentificated. If not we have 407 errors and co...

Today I use your Mapillary Tools v0.5.3 (the latest) and I did not find any possibility to fullfill something related to a proxy.
When running it I get a bad credentials response. As I cannot see more verbose logs but as I did not precise any proxy information I'm sure that it is proxy related. I'm custom to ths kind of desagrement...

Would it be possible in the future to have this proxy configuration feature ?
Or there is already a trick ?

### Basic information
* Release version: `0.5.3.`
* System: `Windows` (I know... no choice....)

### Steps to reproduce behavior

Mount an enterprise proxy...

**Comment by Penegal** [comment]
I'm also subject to this situation and would like to know how to give proxy credentials to mapillary_tools.

**Comment by ptpt** [comment]
Checkout https://requests.readthedocs.io/en/latest/user/advanced/#proxies

```shell
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
$ export ALL_PROXY="socks5://10.10.1.10:3434"
$ mapillary_tools process_and_upload path/to/images
```
