### ISSUE TITLE
New suggested instructions for Android / Linux installation.

### ISSUE THREAD

**Issue by arocoun** [mapillary/mapillary_tools#384]
Because Python 2 is no longer supported, your instructions in the README under Custom Installation may no longer work. Further, you provide no instructions for installing Mapillary tools on an Android device. The following link has the process I used to install mapillary_tools using Python 2, and may prove helpful in updating your README.

https://forum.mapillary.com/t/installing-mapillary-tools-on-an-android-device/4632

**Comment by ptpt** [comment]
Thanks @arocoun for the feedback. Python3 is in master now. README is updated. Please follow https://github.com/mapillary/mapillary_tools#installation
