### ISSUE TITLE
README suggestion: Instructions for installing on Android

### ISSUE THREAD

**Issue by arocoun** [mapillary/mapillary_tools#387]
I've rediscovered how to install mapillary_tools on an Android device, and have written the complete process [here, on the Mapillary forum](https://forum.mapillary.com/t/installing-mapillary-tools-on-an-android-device/4632/4), if y'all feel like referencing the thread in the README, or adding some installation instructions.

**Comment by eneerhut** [comment]
@arocoun thanks for this! Maybe best if you edit the readme and submit as a pull request that we can include.

**Comment by arocoun** [comment]
I've done as you suggested. Thanks for responding!

**Comment by ptpt** [comment]
Thanks for the PR. Closed in https://github.com/mapillary/mapillary_tools/pull/396
