### ISSUE TITLE
Where can I get version 060 of mapillary tools? 

### ISSUE THREAD

**Issue by renardua** [mapillary/mapillary_tools#390]
### Basic information
* Release version: 050
* System: macos
* Capture Device: gopro

### Steps to reproduce behavior

 1. python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools
 2.
 3.

### Expected behavior
version 060

### Actual behavior
version 050

### Additional information
Collecting git+https://github.com/mapillary/mapillary_tools
  Cloning https://github.com/mapillary/mapillary_tools to /private/var/folders/tr/p0kmq6dx03b0j229cf14c8hm0000gn/T/pip-req-build-gunnlywo
Collecting Piexif@ git+https://github.com/mapillary/Piexif
  Cloning https://github.com/mapillary/Piexif to /private/var/folders/tr/p0kmq6dx03b0j229cf14c8hm0000gn/T/pip-install-02_macbl/piexif_a5de5bba4e4c4f83833ebae668ae253b
Collecting exifread==2.1.2
  Using cached ExifRead-2.1.2.tar.gz (33 kB)
Collecting gpxpy==0.9.8
  Downloading gpxpy-0.9.8.tar.gz (20 kB)
Collecting Pillow
  Downloading Pillow-8.2.0-cp39-cp39-macosx_10_10_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 2.1 MB/s 
Collecting pymp4==1.1.0
  Using cached pymp4-1.1.0.tar.gz (7.1 kB)
Collecting construct==2.8.8
  Using cached construct-2.8.8.tar.gz (717 kB)
Collecting pynmea2==1.12.0
  Using cached pynmea2-1.12.0.tar.gz (26 kB)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 6.6 MB/s 
Collecting requests==2.20.0
  Using cached requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 8.3 MB/s 
Collecting chardet<3.1.0,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<2.8,>=2.5
  Using cached idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tqdm==2.2.4
  Using cached tqdm-2.2.4-py2.py3-none-any.whl (17 kB)
Collecting tzwhere
  Downloading tzwhere-3.0.3.tar.gz (23.7 MB)
     |████████████████████████████████| 23.7 MB 9.3 MB/s 
Collecting shapely
  Downloading Shapely-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 13.7 MB/s 
Collecting urllib3<1.25,>=1.21.1
  Using cached urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: mapillary-tools, exifread, gpxpy, Piexif, pymp4, construct, pynmea2, tzwhere
  Building wheel for mapillary-tools (setup.py) ... done
  Created wheel for mapillary-tools: filename=mapillary_tools-0.6.0-py3-none-any.whl size=96704 sha256=8483a452bb7b94fd2e1411acf9fc240b3c19c487bbcbb4ad9f4e756ee69ea5e5
  Stored in directory: /private/var/folders/tr/p0kmq6dx03b0j229cf14c8hm0000gn/T/pip-ephem-wheel-cache-uhtii7l8/wheels/ba/e7/23/55fd4d3ca2fce4c22847932f6d50418b7a16a2d5e94035e669
  Building wheel for exifread (setup.py) ... done
  Created wheel for exifread: filename=ExifRead-2.1.2-py3-none-any.whl size=34199 sha256=432f5937ac7b715264ef3151ae934396aca18cae4ce78cf153d2df5470e74c0a
  Stored in directory: /Users/su/Library/Caches/pip/wheels/ee/bd/42/56a743d37bdf6675d2c5be06c02eb7cdc7ff5a4d2a105e734f
  Building wheel for gpxpy (setup.py) ... done
  Created wheel for gpxpy: filename=gpxpy-0.9.8-py3-none-any.whl size=23813 sha256=4d4565a6c23d67ddf69ab25f0b8af00defd2730799486ff31910123d6bb62b2d
  Stored in directory: /Users/su/Library/Caches/pip/wheels/e5/64/b8/b05090738822d0ba06c0b6bebe3c5873b6df8bf1a173958914
  Building wheel for Piexif (setup.py) ... done
  Created wheel for Piexif: filename=piexif-1.0.13m-py3-none-any.whl size=18554 sha256=8fcb574bc997483ecc331ea444bdccff114bdf79706fb62667efc5ae362ed0b0
  Stored in directory: /private/var/folders/tr/p0kmq6dx03b0j229cf14c8hm0000gn/T/pip-ephem-wheel-cache-uhtii7l8/wheels/c9/df/a5/af6de121d83b30432d2ab1b6a196341f14bfe7e93a716dcab8
  Building wheel for pymp4 (setup.py) ... done
  Created wheel for pymp4: filename=pymp4-1.1.0-py2.py3-none-any.whl size=9087 sha256=d85f1f6d9e091b8d59bcf3ee0729b54ea778c4717f64378bc0fce5c3f38f5bb8
  Stored in directory: /Users/su/Library/Caches/pip/wheels/ce/13/6f/40f1a2761c528062f5960de159ed0e43db6e901b44c1ed5365
  Building wheel for construct (setup.py) ... done
  Created wheel for construct: filename=construct-2.8.8-py2.py3-none-any.whl size=69807 sha256=e57d9afc58af8aa088f24afc6deac8b3d4a2a93b367b27fde89b829949b3ed49
  Stored in directory: /Users/su/Library/Caches/pip/wheels/d4/dc/95/0fe7a1d8ff17d69542c479a2ac68c1650a5c8703dd37775057
  Building wheel for pynmea2 (setup.py) ... done
  Created wheel for pynmea2: filename=pynmea2-1.12.0-py3-none-any.whl size=22884 sha256=6b5ddebfde8a2ca6b3306710e1b006b70554cd7a4195094ce5c85b2f89211660
  Stored in directory: /Users/su/Library/Caches/pip/wheels/eb/3d/19/2cf3890a9655c34ef1fe7da38faea3f8465bc8df0dd614bf63
  Building wheel for tzwhere (setup.py) ... done
  Created wheel for tzwhere: filename=tzwhere-3.0.3-py3-none-any.whl size=23742583 sha256=b6b38b74068a78484b8402a3e6f6561f0192668ff723771eca71d12210d328aa
  Stored in directory: /Users/su/Library/Caches/pip/wheels/1c/5b/38/2c0772ba05aa51fefb242a15ed85fb649990712901b6c80458
Successfully built mapillary-tools exifread gpxpy Piexif pymp4 construct pynmea2 tzwhere
Installing collected packages: urllib3, six, shapely, idna, construct, chardet, certifi, tzwhere, tqdm, requests, pytz, python-dateutil, pynmea2, pymp4, Pillow, Piexif, gpxpy, exifread, mapillary-tools
Successfully installed Piexif-1.0.13m Pillow-8.2.0 certifi-2020.12.5 chardet-3.0.4 construct-2.8.8 exifread-2.1.2 gpxpy-0.9.8 idna-2.7 mapillary-tools-0.6.0 pymp4-1.1.0 pynmea2-1.12.0 python-dateutil-2.7.3 pytz-2021.1 requests-2.20.0 shapely-1.7.1 six-1.15.0 tqdm-2.2.4 tzwhere-3.0.3 urllib3-1.24.3
su:Mapillary su$ ./mapillary_tools --version

Mapillary tools version : 0.5.0

**Comment by ptpt** [comment]
@renardua the command `python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools` installs the tools on your system bin (e.g. `/usr/local/bin`) but you are running the tools on a local folder.

Try running `mapillary_tools` instead of `./mapillary_tools`. Hopefully you will see 0.6.0.

Also you can use `which mapillary_tools` to check where your tools is installed.

**Comment by ptpt** [comment]
0.7.0 is released, but upgrade with the instructions above ^^.
