### ISSUE TITLE
Better interpolate image directions: based on GPS data, not only at image locations

### ISSUE THREAD

**Issue by lionkmp** [mapillary/mapillary_tools#395]
### Basic information

* Release version: `0.6.0` 
* System:  `Linux`
* Capture Device:  `Action Camera` 

### Steps to reproduce behavior

 1. Record images with very slow interval (30 seconds or 1 minute) (For exampel because of hiking for very long time in no-mapillary-imagery areas and there is simply no battery to support more frequent pictures.)
 2. Interpolate the directions (Exif.GPSInfo.GPSImgDirection) using maillary_tools based on a GPX track

Using this command:

mapillary_tools process --advanced --interpolate_directions --overwrite_EXIF_direction_tag --geotag_source gpx --geotag_source_path CAMERA2_0_2020_01_23_15_41_13_824_+0100.gpx --overwrite_EXIF_gps_tag --rerun --offset_time 3600 --import_path . --user_name XX

### Expected behavior

Each image's direction should point on the direction where the GPX track is heading at that place.

### Actual behavior

Image direction seems to point to the location of the next image!

### Corresponding data

(Any Mapillary recording can be used as test data, just use a few of the images.)

### Additional information

I tested with multiple images in this test sequence, each of them pointed to the image after the turn, like this:

![mapillary_direction](https://user-images.githubusercontent.com/5088657/117930392-370d7c00-b2fe-11eb-8af4-632bfd7d52fe.png)

**Comment by ptpt** [comment]
With 0.8.0 and above, it should interpolate by GPX if you do NOT add `--interpolate_directions`:

```
mapillary_tools process --overwrite_EXIF_direction_tag --geotag_source gpx --geotag_source_path CAMERA2_0_2020_01_23_15_41_13_824_+0100.gpx --overwrite_EXIF_gps_tag --rerun --offset_time 3600 .
```
