### ISSUE TITLE
Error, user authentication failed for user <username>

### ISSUE THREAD

**Issue by donalhunt** [mapillary/mapillary_tools#403]
### Basic information
* Release version: `0.6.0`
* System: `Linux`
* Capture Device: `Dashcam (Viofo A129 Duo)`

### Steps to reproduce behaviour

`mapillary_tools process_and_upload --import_path "/path/to/images" --user_name "<username>"`

### Expected behaviour

Images are processed and uploaded.

### Actual behaviour

```
Running user_process for 415 images, skipping 0 images.
Enter user credentials for user <username>:
Enter email: myemail@address.com
Enter user password: 
Error, user authentication failed for user <username>
Make sure your user credentials are correct, user authentication is required for images to be uploaded to Mapillary.
```

### Corresponding data

N/A

### Additional information

I have changed my password today. I suspect there may be a non-zero chance that there is a lag between the password being changed and API / API token servers being aware of the change.

**Comment by donalhunt** [comment]
I also tried the `--advanced authenticate --force_overwrite` option but that is failing too. :(

`mapillary_tools --advanced authenticate --force_overwrite --user_name "<username>" --user_email "<email>" --user_password "<password>"`

**Comment by donalhunt** [comment]
interestingly, I cannot log into the android app either (but I can log into the website). :(

**Comment by ptpt** [comment]
@donalhunt it should be fixed in https://github.com/mapillary/mapillary_tools/pull/393

Could you install the latest and let me know any feedback.

**Comment by GPSMapper** [comment]
I confirm updating to 0.7.0 does the trick
pip install --upgrade git+https://github.com/mapillary/mapillary_tools

**Comment by GPSMapper** [comment]
> I cannot log into the android app either

You should install new  Mapillay app for Android
https://blog.mapillary.com/update/2021/06/09/platform-updates-june.html

**Comment by donalhunt** [comment]
Can confirm 0.7.0 resolves the authentication issue.
Thanks for the link to the new app too (my play store search returned the old one when I went to install it yesterday for some reason).
