### ISSUE TITLE
unable to install mapillary_tools on Linux

### ISSUE THREAD

**Issue by zorglubu** [mapillary/mapillary_tools#407]
Hello,

I am unable to install mapillary_tools on Linux Mint.
I should add that I really don't know python, and I am a bit lost. 

### Basic information
* Python 3.6.9
* System: Linux Mint 19.3 Tricia

### Steps to reproduce behavior
I run the command :
`python3 -m pip install git+https://github.com/mapillary/mapillary_tools`

I get a message "Successfully installed Piexif-1.1.3 certifi-2021.5.30 chardet-3.0.4 construct-2.8.8 exifread-2.1.2 gpxpy-0.9.8 idna-2.7 mapillary-tools-0.7.0 pymp4-1.1.0 pynmea2-1.12.0 python-dateutil-2.7.3 pytz-2021.1 requests-2.20.0 shapely-1.7.1 six-1.16.0 tqdm-2.2.4 tzwhere-3.0.3 urllib3-1.24.3"
but the script 'mapillary_tools' is unknown on my system.

Attached is what I get on screen during install.
[install_mapillary.txt](https://github.com/mapillary/mapillary_tools/files/6657554/install_mapillary.txt)

Thanks in advance for any assistance.

**Comment by ptpt** [comment]
Is it because mapillary_tools is not installed in your $PATH?

Could you run `python3 -m pip install -U git+https://github.com/mapillary/mapillary_tools` instead?

**Comment by zorglubu** [comment]
Thank you. It changed nothing.
I could add it in my $PATH if I knew where it has been installed. I am wondering if something is really installed, and "Where ?"

**Comment by ptpt** [comment]
Could you run the following to find where it is:
```
$ cd ~ # just make sure you are not in the mapillary_tools folder
$ python3 -m pip show mapillary_tools
```

You can add `-f` to list all files `python3 -m pip show -f mapillary_tools`
