### ISSUE TITLE
Geotag gets it wrong (for me)

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_tools#43]
Well, you asked for testers :) I'm trying to tag some photos from a cycle tour last weekend. The time on my camera looks correct (to within a minute), and my GPS (Garmin 600) shows the correct time. Yet the geotagging calculated by this tool is completely wrong.

With this set of photos, I've found with trial and error that an offset of 39500 looks about right for the last few photos in my collection (..14.JPG to ..22.JPG), but the computed lat/long for the last two (23 and 24) is too "early" (it should be maybe 30 minutes later).

Meanwhile, photos 0974 and 0975 both have a timestamp of 12:00pm on March 8th, yet are given dramatically locations. 0974 seems to have about the right location, but 0975 is from a place at least an hour earlier in the day.

Similarly, photo 0965 and 0967 both have the timestamp 17:36 on March 7th. 0967 is given a location which looks exactly right, but 0968 is from a place nearly 24 hours later!

I'm using Picasa to verify the locations geotagged in the photos. The command line I'm running looks like this:

`python geotag_from_gpx.py /pictures/2015-03-07-SGZ-geotagged/ South\ Gippsland\ Jazz\ Tour\ merged.gpx 39500`

I can't say for sure whether it's definitely the script that's not behaving right - maybe Picasa is showing the wrong data. (It's definitely doing some weird things, like not indicating that certain photos are geotagged, even though it shows the lat/long in the metadata).

```
-rwxrwxrwx 1 vagrant vagrant 3322880 Mar  7 02:28 P1030949.JPG
-rwxrwxrwx 1 vagrant vagrant 3310592 Mar  7 02:28 P1030950.JPG
-rwxrwxrwx 1 vagrant vagrant 3372544 Mar  7 02:28 P1030951.JPG
-rw-r--r-- 1 vagrant vagrant 3535619 Mar 14 10:08 P1030952.JPG
-rwxrwxrwx 1 vagrant vagrant 3307520 Mar  7 04:04 P1030953.JPG
-rw-r--r-- 1 vagrant vagrant 3252997 Mar 14 10:09 P1030954.JPG
-rw-r--r-- 1 vagrant vagrant 3402540 Mar 14 10:09 P1030956.JPG
-rwxrwxrwx 1 vagrant vagrant 3576320 Mar  7 05:16 P1030957.JPG
-rwxrwxrwx 1 vagrant vagrant 3346944 Mar  7 05:22 P1030958.JPG
-rw-r--r-- 1 vagrant vagrant 3250036 Mar 14 10:09 P1030959.JPG
-rw-r--r-- 1 vagrant vagrant 3452546 Mar 14 10:09 P1030960.JPG
-rw-r--r-- 1 vagrant vagrant 3335079 Mar 14 10:10 P1030961.JPG
-rwxrwxrwx 1 vagrant vagrant 3431936 Mar  7 06:17 P1030962.JPG
-rw-r--r-- 1 vagrant vagrant 3172363 Mar 14 10:10 P1030963.JPG
-rw-r--r-- 1 vagrant vagrant 3442613 Mar 14 10:10 P1030964.JPG
-rwxrwxrwx 1 vagrant vagrant 3470848 Mar  7 06:36 P1030965.JPG
-rwxrwxrwx 1 vagrant vagrant 3300352 Mar  7 06:36 P1030967.JPG
-rwxrwxrwx 1 vagrant vagrant 3585536 Mar  7 06:37 P1030968.JPG
-rwxrwxrwx 1 vagrant vagrant 3615232 Mar  7 06:56 P1030969.JPG
-rw-r--r-- 1 vagrant vagrant 3463210 Mar 14 10:11 P1030970.JPG
-rwxrwxrwx 1 vagrant vagrant 3552768 Mar  7 21:32 P1030971.JPG
-rwxrwxrwx 1 vagrant vagrant 3278336 Mar  7 21:33 P1030972.JPG
-rwxrwxrwx 1 vagrant vagrant 3338752 Mar  7 21:35 P1030973.JPG
-rwxrwxrwx 1 vagrant vagrant 3398656 Mar  8 01:00 P1030974.JPG
-rw-r--r-- 1 vagrant vagrant 3346223 Mar 14 10:12 P1030975.JPG
-rwxrwxrwx 1 vagrant vagrant 3305984 Mar  8 01:00 P1030976.JPG
-rwxrwxrwx 1 vagrant vagrant 3355136 Mar  8 01:01 P1030977.JPG
-rwxrwxrwx 1 vagrant vagrant 3387904 Mar  8 01:02 P1030978.JPG
-rwxrwxrwx 1 vagrant vagrant 3310592 Mar  8 01:08 P1030979.JPG
-rwxrwxrwx 1 vagrant vagrant 3298304 Mar  8 01:08 P1030980.JPG
-rwxrwxrwx 1 vagrant vagrant 3287552 Mar  8 01:08 P1030981.JPG
-rwxrwxrwx 1 vagrant vagrant 3369472 Mar  8 02:14 P1030982.JPG
-rw-r--r-- 1 vagrant vagrant 3297560 Mar 14 10:12 P1030983.JPG
-rw-r--r-- 1 vagrant vagrant 3412067 Mar 14 10:12 P1030984.JPG
-rw-r--r-- 1 vagrant vagrant 3356035 Mar 14 10:12 P1030985.JPG
-rw-r--r-- 1 vagrant vagrant 3441850 Mar 14 10:13 P1030986.JPG
-rw-r--r-- 1 vagrant vagrant 3326647 Mar 14 10:13 P1030987.JPG
-rwxrwxrwx 1 vagrant vagrant 3424256 Mar  8 05:05 P1030988.JPG
-rw-r--r-- 1 vagrant vagrant 3299158 Mar 14 10:13 P1030989.JPG
-rwxrwxrwx 1 vagrant vagrant 3280896 Mar  8 05:09 P1030990.JPG
-rwxrwxrwx 1 vagrant vagrant 3538944 Mar  8 05:11 P1030991.JPG
-rwxrwxrwx 1 vagrant vagrant 3293696 Mar  8 05:14 P1030992.JPG
-rwxrwxrwx 1 vagrant vagrant 3273728 Mar  8 05:15 P1030993.JPG
-rwxrwxrwx 1 vagrant vagrant 3545088 Mar  8 05:16 P1030994.JPG
-rwxrwxrwx 1 vagrant vagrant 3509248 Mar  8 05:18 P1030995.JPG
-rwxrwxrwx 1 vagrant vagrant 3593728 Mar  8 05:19 P1030996.JPG
-rwxrwxrwx 1 vagrant vagrant 3431424 Mar  9 01:58 P1030997.JPG
-rw-r--r-- 1 vagrant vagrant 3380586 Mar 14 10:13 P1030998.JPG
-rw-r--r-- 1 vagrant vagrant 3543991 Mar 14 10:14 P1030999.JPG
-rwxrwxrwx 1 vagrant vagrant 3460608 Mar  9 02:09 P1040001.JPG
-rw-r--r-- 1 vagrant vagrant 3577052 Mar 14 10:14 P1040002.JPG
-rw-r--r-- 1 vagrant vagrant 3390191 Mar 14 10:14 P1040004.JPG
-rw-r--r-- 1 vagrant vagrant 3466775 Mar 14 10:14 P1040005.JPG
-rw-r--r-- 1 vagrant vagrant 3377522 Mar 14 10:14 P1040006.JPG
-rwxrwxrwx 1 vagrant vagrant 3480576 Mar  9 04:06 P1040007.JPG
-rwxrwxrwx 1 vagrant vagrant 3316224 Mar  9 04:22 P1040008.JPG
-rwxrwxrwx 1 vagrant vagrant 3375104 Mar  9 05:06 P1040009.JPG
-rwxrwxrwx 1 vagrant vagrant 3575296 Mar  9 06:48 P1040010.JPG
-rw-r--r-- 1 vagrant vagrant 3337524 Mar 14 10:15 P1040011.JPG
-rwxrwxrwx 1 vagrant vagrant 3284992 Mar  9 07:13 P1040012.JPG
-rw-r--r-- 1 vagrant vagrant 3496411 Mar 14 10:15 P1040013.JPG
-rwxrwxrwx 1 vagrant vagrant 3307008 Mar  9 07:42 P1040014.JPG
-rw-r--r-- 1 vagrant vagrant 3427101 Mar 14 10:15 P1040015.JPG
-rwxrwxrwx 1 vagrant vagrant 3395584 Mar  9 07:43 P1040016.JPG
-rwxrwxrwx 1 vagrant vagrant 3441152 Mar  9 07:43 P1040017.JPG
-rwxrwxrwx 1 vagrant vagrant 3491328 Mar  9 07:52 P1040018.JPG
-rwxrwxrwx 1 vagrant vagrant 3387904 Mar  9 21:52 P1040019.JPG
-rwxrwxrwx 1 vagrant vagrant 3357184 Mar  9 21:57 P1040020.JPG
-rwxrwxrwx 1 vagrant vagrant 3439616 Mar  9 23:27 P1040021.JPG
-rw-r--r-- 1 vagrant vagrant 3414536 Mar 14 10:15 P1040022.JPG
-rw-r--r-- 1 vagrant vagrant 3283197 Mar 14 10:16 P1040023.JPG
-rwxrwxrwx 1 vagrant vagrant 3558912 Mar 10 06:45 P1040024.JPG
```

GPX file of day 2 (971 to 018.JPG): 
https://www.dropbox.com/s/kgdapat6r316jrw/2015-03-08%2008.44.41%20Day.gpx?dl=0

These two photos are at the same time and place (about -38.56252, 145.95753):

* https://www.dropbox.com/s/5wg2n4cfgsijqkn/P1030974.JPG?dl=0
* https://www.dropbox.com/s/c3o9re0p5zstovq/P1030975.JPG?dl=0

**Comment by stevage** [comment]
Ok, I think I'm fairly confident that it is this script misbehaving. I managed to geotag the photos with Garmin Basecamp, with no time offset, and they were all correct. 

(BaseCamp is itself stupidly buggy, in hilariously stupid ways. It loaded and processed photo 1, then photo 1 and 2, then photos 1, 2, and 3, etc, creating dozens of copies of each photo in the process.)

**Comment by stevage** [comment]
Also, if this helps, I notice that my guestimated offset of 39500 is very close to 11 hours, which is my current timezone. Also, some of the photos were modified after taking them (with Picasa), meaning they had a modified date different from their digitisation/creation date. Perhaps these two things are important?

(JetPhoto Studio also seemed to have no problem matching them with the GPX file. It's unfortunately also not very suitable as it wants to move my photos to a new "album")

**Comment by geomapper69** [comment]
The script has always worked ok for me.
I am in timezone GMT+4
I download my Garmin GPS into Basecamp, then export the GPX from there.
Photos have come from many different devices, all of them set to GMT+4.
PC should also be set in correct timezone.

**Comment by jesolem** [comment]
We should take a look. 

Time zones in these files is a pain. Some assume local time of your laptop, some UTC, plus issues with people forgetting to set clock on device...

As a note: we're adding UI in the new manual uploader to hopefully solve the time zone problem once and for all. Stay tuned.

**Comment by stevage** [comment]
Ah, ok, I finally get it - I'm running it inside an Ubuntu VM that doesn't have the timezone set. When I set it now (`dpkg-reconfigure tzdata`), it works correctly.

Also, with some more testing, I think maybe the cause of some of the weird behaviour I was seeing was to do with running it on files that were already geotagged. If I clear all the geotags first with Picasa, then it behaves correctly each time.

**Comment by stevage** [comment]
One thing that would have helped me would be some more verbose output, like:

"Your local time is: ... and your timezone is: ... If these don't look right, the geotags will be wrong."

**Comment by jesolem** [comment]
Added verbose warning. Closing this. Thanks @stevage
