### ISSUE TITLE
mapillary tools version 0.8.0 calculates incorrect number of duplicates

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_tools#443]
# Basic information
•	Release version: 0.8.0
•	System: Windows
•	Capture Device: Action Camera , Garmin VIRB XE

# Steps to reproduce behavior

1.	Capture TEST sequence

•	720 Images
•	Interval: 1 image/second
•	Travel by motorcar, no stops

2.	GPX file (Garmin GPSMAP 66s)

3.	mapillary_tools process

•	mapillary_tools process <<import_path>> --skip_subfolders --geotag_source_path <<gpx_file>> --geotag_source gpx --interpolate_directions --overwrite_all_EXIF_tags

•	--duplicate_distance is not specified, therefore [0.1 meters] (default)

4.	First Run

**Duplicated Images = 169** (out of 720 = 23%)

This is by far incorrect: 23% Duplicates.

I have compared sequences already uploaded to Mapillary by mapillary_tools version 0.7.4 having ±50 Duplicates out of ±10.000 images (2%-5% which is normal).
mapillary_tools version 0.8.0 calculated ±2000 Duplicates.

5.	Second Run

**Duplicated Images = 4**

Which is fair, although reviewing the Duplicated images shows no "real" Duplicates (by 0.1. meter).

--overwrite_all_EXIF_tags is required for first and second run to make second run "more successful".

6.	Remove <<gpx_file>>

mapillary_tools process <<import_path>> --skip_subfolders --interpolate_directions --overwrite_all_EXIF_tags

**Duplicated Images = 8**

# Expected behavior

Duplicated Images = 0 to 8

# Actual behavior

•	Duplicated Images = 169 (first run)
•	Duplicated Images = 4 (second run)
•	Duplicated Images = 8 (no gpx, third run)

# Additional information

Parameters "--summarize --save_as_json" are not available anymore (V 0.8.0).
Therefore interpreting "mapillary_image_description.json" is required to get the number of Duplicated Images.
So mapillary tools version 0.8.0 did not warn about the excessive number of duplicates.

Related to: #441

**Comment by ptpt** [comment]
> Test by 2x gpx + 2x no gpx
> Test by 5x no gpx (rerun unprocessed images)

It's probably because you `--overwrite_all_EXIF_tags` overwrites all EXIF which results in new GPS directions/locations that affects the duplications in the next run.

> Question: How can I find this Error Message? Can it be logged? Where? How?

All errors are written in the `mapillary_image_description.json` file

> Question: Upload will be in 5 sequences, but I see tens of different "MAPSequenceUUID". Oké, I just don't understand.

That means some of the 5 sequences are split into several sequences, due to long gaps in between. Check `--cutoff_distance` and `--cutoff_time`.

> "filename" is duplicated IF Duplicate:

The filename duplication is okay within one description object (which describe one image file).

**Comment by AnkEric** [comment]
> Does the duplication checks work for you after removing `--overwrite_all_EXIF_tags`?

Yes, it does fix.
However, this is (might be): “throwing the baby out with the bathwater”.

My Test 2012-10-12:
Drive by motorcar, city driving so max 50 km/h, no stops (except for one highway crossing and once making a u-turn): 720 images, 1 image/second.
So, my assumption, best guess: no or very few duplicates and only one sequence (no long gaps in between, --cutoff_distance  --cutoff_time). 
That’s what triggered my “testing”.

My - default - Mapillary working procedure: bicycle (1 image/second), or foot (1 image/2 seconds).

Garmin VIRB XE has a bad GPS as compared to Garmin GPSMAP 66.
Garmin VIRB track is suggesting I was “drunk driving”, or is lost completely in the forest, mountains (gorges) or near high buildings.
Garmin GPSMAP 66 shows “straight lines as straight lines”. One of OSM rules (best practice).

Therefore I use gpx track by GPSMAP 66: “--geotag_source gpx”.
This will FIX (relocate) GPS position (MAPLatitude, MAPLongitude) to a more correct position.
It’s my assumption this FIXED position should by uploaded to Mapillary. Only option to do so (also: my assumption) is by updating EXIF: --overwrite_EXIF_gps_tag.
Not --overwrite_EXIF_gps_tag would make GPX-track useless (waste of time and effort).
Perhaps (…) it’s better NOT to --overwrite_EXIF_time_tag (unless I have a time-zone issue during holidays).

### RUN (1): FIX GPS position.
BUT in the SAME run Mapillary_tools will decide on Duplicates based on INCORRECT - yet to be fixed - GPS position.
So: Mapillary_tools will find too many Duplicates in Run (1). Duplicates = 60 (8%).

### RUN (2): Find Duplicates (by corrected GPS position).
After RUN (1) + FIX GPS position + overwrite_EXIF_gps_tag, execute a Run (2) without “--geotag_source gpx”.
Now GPS position won’t be fixed, it’s already okay thanks to GPX in Run (1).
Now Duplicates are evaluated AGAIN and now based on CORRECTED GPS position.
Result: Duplicates = [0].
And I agree on “zero”.

So, my assumption, new insight:
Either Mapillary_tools should process gpx before deciding on Duplicates in the same processing run, or I should always pre-process in two runs…..

**Comment by ptpt** [comment]
> This will FIX (relocate) GPS position (MAPLatitude, MAPLongitude) to a more correct position.
It’s my assumption this FIXED position should by uploaded to Mapillary. Only option to do so (also: my assumption) is by updating EXIF: --overwrite_EXIF_gps_tag.

It does fix the GPS position in the image EXIF, but when it comes to uploading, the value in the image description file will be used instead of the EXIF one. Therefore `--overwrite_all_EXIF_tags` can be skipped if you don't need the EXIF values to be updated. See https://github.com/mapillary/mapillary_tools#image-description

You can convert the description file to GeoJSON and paste it in http://geojson.io/. The points shown there are the images successfully processed, and will be uploaded.
```
python3 -m mapillary_tools.geojson paht/to/mapillary_image_description.json
```
