### ISSUE TITLE
mapillary tools 0.8.0 offset time (GPX) and MAPCaptureTime Incorrect by Intentional COPY Images Error

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_tools#444]
### Basic information
* Release version: `0.8.0`
* System: `Windows`
* Capture Device: `Action Camera`

Related to: https://github.com/mapillary/mapillary_tools/issues/441

### Steps to reproduce behavior

 1. Process 720 Images, sequence date = 2021-10-12, having GPX 2021-10-12
 
- mapillary_tools process <<import_path>> --skip_subfolders --geotag_source_path <<gpx_file>> --geotag_source gpx --interpolate_directions --overwrite_all_EXIF_tags

- Duplicates Images = 169 (out 0f 720)
- Images_Failed = [0]

 2. Process 720 Images, sequence date = 2021-10-12
 
 - mapillary_tools process <<import_path>> --skip_subfolders --geotag_source_path <<gpx_file>> --geotag_source gpx --interpolate_directions --overwrite_all_EXIF_tags

- Duplicates Images = 4 (out 0f 720)
- Images_Failed = [0]

 3. To TEST offset time (vs. GPS), MAPCaptureTime:
 
- **COPY** 20 Images, sequence date = **2021-06-12** INTO Subfolder having Images, sequence date = **2021-10-12**

- **This is an intentional error, for testing purposes.**

 4.  Process 740 Images, sequence date = 2021-10-12 AND sequence date = 2021-06-12, having GPX 2021-10-12
 
 - mapillary_tools process <<import_path>> --skip_subfolders --geotag_source_path <<gpx_file>> --geotag_source gpx --interpolate_directions --overwrite_all_EXIF_tags

### Expected behavior

Since 20 Images (date 2021-06-12) are out of scope against GPX 2021-10-12 expected is:

- MapillaryOffsetTimeError for 20 images.
- Images_Failed = [20]
- Duplicates Images = [4]

### Actual behavior

- Images_Failed = [0]

So: no warning, no error for [20] misplaced Images.

- Duplicates Images = [0]

So: [4] Duplicates Images have been "resolved" by Error, as no Duplicate (anymore).

mapillary_image_description.json:

20 ERROR Images (out of scope by time):

- "filename": "**20210612**_110431_1.jpg" (DATE = 2021-06-12)
- "MAPCaptureTime": "**2021_10_12**_12_21_55_000", IS ERROR
- **MAPSequenceUUID:** "....", therefore Images will be uploaded, IS ERROR
- MAPLatitude, MAPLongitude: not verified

    {
        "MAPLatitude": 52.079640571027994,
        "MAPLongitude": 4.906940208747983,
        **"MAPCaptureTime": "2021_10_12_12_21_55_000"**,
        "MAPAltitude": 76.42,
        "MAPCompassHeading": {
            "TrueHeading": 239.77421635170356,
            "MagneticHeading": 239.77421635170356
        },
        **"MAPSequenceUUID": "c27a1fe8-f104-4591-9fe1-58ba1a23a3d4"**,
        "MAPOrientation": 1,
        "MAPDeviceMake": "Garmin",
        "MAPDeviceModel": "VIRBXE",
        "MAPMetaTags": {
            "strings": [
                {
                    "key": "mapillary_tools_version",
                    "value": "0.8.0"
                }
            ]
        },
        "MAPPhotoUUID": "73bf9643-dac1-4591-a4d7-44c88684b080",
        **"filename": "20210612_110431_1.jpg"**
    },

716 ERROR Images (out of scope by MAPCaptureTime "2022_02_11"):
- "filename": "**20211012**_110431_1.jpg" (DATE = 2021-10-12)
- "MAPCaptureTime": "**2022_02_11**_12_21_55_000", IS ERROR (year = 2022 !)
- **MAPSequenceUUID:** "....", therefore Images will be uploaded, which is oké IF (!) GPS position is correct
- MAPLatitude, MAPLongitude: not verified

    {
        "MAPLatitude": 92.8612379282713,
        "MAPLongitude": 33.01173100247979,
        **"MAPCaptureTime": "2022_02_11_16_01_29_000"**,
        "MAPAltitude": 75.67000000178814,
        "MAPCompassHeading": {
            "TrueHeading": 358.030700993111,
            "MagneticHeading": 358.030700993111
        },
        "MAPSequenceUUID": "d85b8cf2-910c-49cf-9c81-5c0ce44ad744",
        "MAPOrientation": 1,
        "MAPDeviceMake": "Garmin",
        "MAPDeviceModel": "VIRBXE",
        "MAPMetaTags": {
            "strings": [
                {
                    "key": "mapillary_tools_version",
                    "value": "0.8.0"
                }
            ]
        },
        "MAPPhotoUUID": "b891d4f8-49c5-464d-8ff5-cc1b85bc832b",
        **"filename": "20211012_142918_0.jpg"**
    },

**Comment by ptpt** [comment]
Hey @AnkEric could you check if the latest commits fix the issue?

```shell
python3 -m pip install --force-reinstall --upgrade git+https://github.com/mapillary/mapillary_tools
```
