### ISSUE TITLE
tools 0.8.0 upload images over and over again

### ISSUE THREAD

**Issue by teddy1173** [mapillary/mapillary_tools#450]
### Basic information
* Release version: `0.8.0` 
* System: `Linux` 
* Capture Device: `Action Camera` 

It seems that with 0.8.0 the tools don't know which pictures have already been uploaded, and starts all over again. I uploaded 2597 pictures yesterday, and I was astonished to find that one sequence shows double in the feed. I guess I uploaded this the day before...Today, I wanted to know if some pics are still to upload, and: it starts again from sequence 1 of 6.  
Command is:
```
ted@ted-Latitude-E5470:~$ mapillary_tools upload "Aayi/521MEDIA/"
```
Please check. I guess I'm just uploading the same first sequence the third time.

**Comment by Strubbl** [comment]
> The feature is disabled by default, because IMO the upload command should really just focus on assembling and uploading. However I see the point of adding the duplication check, as reuploading the same folder might happen quite often.

*disabled by default*: 
So if mapillary does not care about duplicated uploads, i am fine with that. Then i do not care, too.

**Comment by ptpt** [comment]
Hey all,

Upload duplication check is enabled by default now. You don't need this trick any more https://github.com/mapillary/mapillary_tools/issues/450#issuecomment-950131761

With this enabled, it should be safe to re-upload the same folder as it will skip the uploaded ones and continue. If not, please let me know.
