### ISSUE TITLE
urllib2 not installing, urllib3 and urllib5 fails to execute

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#46]
For some reason `urllib2` doesn't install (no longer available in pypi?), and when trying `urllib5` from pypi I get a `cannot find urllib2 error`, so I tried with `urllib3`, which doesn't seem to have that problem. But than it started to complain on all the syntax (exception handling missing or with different names, Request function seem to have changed name, etc).

I would like to see this solved as I have almost 4000 images waiting to upload and need to do this with `upload_with_authentication.py` or through manual upload site, which takes too long. I really need this automated.

**Comment by jesolem** [comment]
Is this using Python 3.x?

For Python 2.x urllib2 comes built in so you should not need pip
https://docs.python.org/2/library/urllib2.html

The urllib syntax changed from 2->3. Our scripts are all for Python 2.x.

**Comment by Skippern** [comment]
Yeah, I use python 3.4, any chance you can upgrade the scripts for py3? Or do I need to put my head around to pip all dependencies in py2.7?

Aun Johnsen

**Comment by jesolem** [comment]
@Skippern We can but not a short time fix on our end unfortunately. 

Suggestion: use virtualenv with a 2.7 distribution and then pip install there?

**Comment by Skippern** [comment]
Looking into it

Aun Johnsen

**Comment by Skippern** [comment]
@jesolem 

```
skippern$ python2.7 upload_with_authentication.py 
Traceback (most recent call last):
  File "upload_with_authentication.py", line 103, in <module>
    path = sys.argv[1]
IndexError: list index out of range
```

**Comment by jesolem** [comment]
You forgot the path to the images:
```Use from command line as: python upload_with_authentication.py path```

**Comment by Skippern** [comment]
@jesolem Its running now, will struggle my way through ~4000 images

**Comment by Skippern** [comment]
Is it possible to add a version check and warn about this if running with python3?

**Comment by jesolem** [comment]
Added checks for Python 2.x. Thanks @Skippern , sorry for slow response.
