### ISSUE TITLE
Failure video_process_and_upload on BlackVue mp4

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#467]
### Basic information
* Release version: `0.8.0`
* System: 'Linux`
* Capture Device: `BlackVue DR900S-1CH (Mapillary F/W)`

### Steps to reproduce behavior

Difficult to be specific here - no errmsgs, just partial/incomplete operation

- Debian Buster (latest patched state)
- Python 3.7 virtual environment - steps
python3 -m venv venv
source venv/bin/activate
python3 -m pip install wheel
python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools

Test run of 5 BlackVue videos 2FPS

INPUT=/home/bcameron/Thing/Mapillary/newtest/20211003/2/
MAPILLARY_USER=bob3bob3
mapillary_tools video_process_and_upload $INPUT \
   --user_name $MAPILLARY_USER \
   --geotag_source "blackvue_videos" \
   --geotag_source_path $INPUT \
   --interpolate_directions \
   --video_sample_interval 0.5 \
   --device_make "Blackvue" \
   --device_model "DR900S-1CH" \
   --overwrite_EXIF_gps_tag \
   --duplicate_distance 1.0

ffmpeg runs fine creating all images

mapillary_image_description.json shows only the 120 images from the first mp4

The EXIF fields were fully populated in only the first 117 images of the first mp4. The balance of 3 actually end up as a 2nd sequence.

I noted that there were perhaps 15 connections in TIME_WAIT during the upload time (netstat)

Repeating the command did not resolve, but did not upload anything. The web GUI however seems to be showing a duplicate "ingesting"

### Expected behavior

To complete operation w/o error

### Actual behavior

Partial upload

### Additional information

"key": "mapillary_tools_version",
"value": "0.8.0"

2021-10-26 07:53:31,158 - INFO   - {
    "total_images": 120,
    "processed_images": 120,
    "failed_images": 0,
    "duplicated_images": 0
}
2021-10-26 07:53:31,158 - INFO   - Check /home/bcameron/Thing/Mapillary/newtest/20211003/2/mapillary_sampled_video_frames/mapillary_image_description.json for details
2021-10-26 07:57:43,061 - INFO   - Upload summary (in megabytes/second): {
    "images": 120,
    "sequences": 2,
    "size": 89.2843,
    "uploaded_size": 89.2843,
    "speed": 0.3664,
    "time": 243.6932

**Comment by ptpt** [comment]
> Produced 122 images of which 117 had fully populated EXIF tags. mapillary_image_description.json showed 117 images of the same sequence (of which there was only one)

It's because 5 images failed and the errors were not written in the image description file. Fixed in https://github.com/mapillary/mapillary_tools/pull/470. Check the image description file why they are failed. Most likely the images are outside the gpx.
