### ISSUE TITLE
upload_video_with_synced_gpx.py

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#47]
Would it be possible to have video uploads where gpx file starts at first frame in the video? My `Garmin VIRB Edit` software allow me to trim videos so that I can make sure that GPX track starts at first frame, and last GPX track is at last frame, i.e. a synced video/gpx file. I would like it to work similar as `upload_with_authentication.py`

**Comment by jesolem** [comment]
Thanks @Skippern 
Something for us to look at in the future. You can use the video upload in the web uploader for now. 
With video we need to make sure that it is something we can decode and use on the server side.

**Comment by Skippern** [comment]
I am trying to upload with the web interface, but are struggling with 2 issues (which a .py probably won’t help much except for command line execution), that is lack of storage and unstable internet line. 20GB in the pipeline, just need to figure out how to import them to my computer, trim them, and upload them. Very slow process as I generally looses connection for a few seconds (freezing upload) between 30 and 70%, no matter file size :(
Aun Johnsen

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by Skippern** [comment]
Any progress on this? I am willing to beta test anything if that helps.

**Comment by jesolem** [comment]
Hi @Skippern , thanks for checking in. We should try to expose this as a script (we process the results after upload in Python anyway so it is doable). 

No progress yet, let's have @paulinus look at it soon.

**Comment by Skippern** [comment]
Still waiting for this, in the mean time I have uploaded a ton of video files manually over a painstakingly slow internet connection, and used very home-brew tools for converting the video files to image sequences. These home-brew tools works with lots of quirks :(

**Comment by jernejaMislej** [comment]
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). The new tools have one executable to run all the tools needed to upload images to Mapillary, including advanced tools and/or advanced arguments that handle videos. Please try to use the new tools, instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md) and let me know if you have any more issues, otherwise i will close this.
