### ISSUE TITLE
Failure BlackVue video sampling - Date Time EXIF tag

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#473]
### Summary
During either sample_video or video_process for a directory (multiple BlackVue mp4 files) the "Date and Time (original)" EXIF tag is only correct for the images sampled from the first video. Subsequent video samplings have the SAME tags written as the first video.

When (if) the process step enacts, the "MapillaryOutsideGPXTrackError" gets larger and larger by approximately 1 minute per video. ie the GPS info in the BlackVue video file is being compared to incorrect EXIF date data.

### Basic information
* Release version: 0.8.0 Sat 13 Nov 02:20 UTC 2021 (pip install date/time)
* System: Linux Debian Buster latest version/patch status - Python 3.7 virtual environment
* Capture Device: Mapillary supplied BlackVue DR900S-1CH with Mapillary F/W at 2FPS

### Steps to reproduce behavior
mkdir venv
python3 -m venv venv
source venv/bin/activate
python3 -m pip install wheel
python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools

(clearing mapillary_sampled_video_frames between tests)

INPUT=/home/bcameron/Thing/Mapillary/newtest/20211003/tao2/
mapillary_tools sample_video --video_sample_interval 0.5 $INPUT

INPUT=/home/bcameron/Thing/Mapillary/newtest/20211003/tao2/
mapillary_tools video_process \
--geotag_source "blackvue_videos" \
--geotag_source_path $INPUT \
--interpolate_directions \
--video_sample_interval 0.5 \
--device_make "Blackvue" \
--device_model "DR900S-1CH" \
--overwrite_EXIF_gps_tag \
--duplicate_distance 1.0 \
--skip_process_errors $INPUT

The videos used for testing had already been successfully uploaded direct to the Mapillary server. The first two are sequences 5FRQ09BGn6kpXra4xgjESD and sfz2gFyk3BI9dRYoZLvltU

Local video names

20211003_110550_NF.mp4
20211003_110651_NF.mp4
20211003_110752_NF.mp4
20211003_110853_NF.mp4
20211003_110954_NF.mp4

### Expected behavior

EXIF tag correct value

### Actual behavior

EXIF tag incorrect value and subsequent processing failure

**Comment by ptpt** [comment]
Could you add --verbose and --rerun and share the output:
```
mapillary_tools --verbose video_process --rerun
...
```

For each video, after sampling you will see information like this:
```
2021-11-14 07:07:19,875 - INFO   - Extracting video information: ffprobe -print_format json -loglevel quiet -show_streams -hide_banner testdata/blackvue/20210629_120535_NF.mp4
2021-11-14 07:07:20,021 - DEBUG  - Extracted video duration: 60.51                            
2021-11-14 07:07:20,026 - DEBUG  - Extracted video end time (creation time): 2021-06-29 01:06:36
```

**Comment by bob3bob3** [comment]
Verbose as requested. 

I started with empty output then did --rerun. Note that This argument deletes all the output structure first.

Commands (omitting --rerun as needed)

INPUT=/home/bcameron/Thing/Mapillary/newtest/20211003/tao2/
mapillary_tools --verbose video_process \
--geotag_source "blackvue_videos" \
--geotag_source_path $INPUT \
--interpolate_directions \
--video_sample_interval 0.5 \
--device_make "Blackvue" \
--device_model "DR900S-1CH" \
--overwrite_EXIF_gps_tag \
--duplicate_distance 1.0 \
--skip_process_errors \
--rerun $INPUT >>test1.log 2>&1

INPUT=/home/bcameron/Thing/Mapillary/newtest/20211003/tao2/
mapillary_tools --verbose sample_video --video_sample_interval 0.5 --rerun $INPUT >>test2.log 2>&1

For video_process;
- video_process-mapillary_image_description.json was unchanged first and rerun
- video_process-first.log & video_process-rerun.log generated

For sample_video
- sample_video-first.log & sample_video-rerun.log only differed by deletion of output structure

ffprobe only occurs once in the log - for the first video

[sample_video-first.log](https://github.com/mapillary/mapillary_tools/files/7534670/sample_video-first.log)
[sample_video-rerun.log](https://github.com/mapillary/mapillary_tools/files/7534671/sample_video-rerun.log)
[video_process-first.log](https://github.com/mapillary/mapillary_tools/files/7534672/video_process-first.log)
[video_process-mapillary_image_description.json.log](https://github.com/mapillary/mapillary_tools/files/7534673/video_process-mapillary_image_description.json.log)
[video_process-rerun.log](https://github.com/mapillary/mapillary_tools/files/7534674/video_process-rerun.log)
