### ISSUE TITLE
Enhancement suggestion BlackVue processing

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_tools#476]
Looking at the way the code works and the resultant image output, it appears that the BlackVue video stream is actually a couple of seconds later than the NMEA code embedded in the mp4. As a result the last few frames of the movie are not processed. In the case of 2FPS this most often results in 117 valid frames out of the 122. There are then "gaps" between sequences when viewing via the web GUI.

As most BlackVue use is using contiguous movies it is possible to extract and concatenate NMEA stream for the entire session. Converting this to a GPX is also handy as a OpenStreetMap trace. If one then replaces the video_process command;

--geotag_source "blackvue_videos" \
--geotag_source_path xxx \

with

--geotag_source "gpx" \
--geotag_source_path xxx.gpx \

The process completes with only missing frames for the last mp4. The BlackVue video start time calculation still seems to be correct.

From the coding standpoint it may be worth generating a gpx for all contiguous movies first, then processing against that. The *.gps files generated by the camera can also be parsed/concatenated, but they only seem to be accessible by WiFi/wget/curl.

**Comment by bob3bob3** [comment]
##WARNING##

Processing BlackVue mp4's using the gpx source (as above) resulted in a 4-5 second image/geoencde delay. ie the image was referenced to a later time.

**Comment by ptpt** [comment]
Have you tried `--interpolation_offset_time` to shift the video time (as well as interpolated GPS positions)? Does it solve the issue?

**Comment by bob3bob3** [comment]
Yes that works. A number of -5 seconds yields acceptable results. 

Note that this wasn't the issue as such, but that pre-concatenating the BlackVue NMEA streams (and using) may be a worthwhile (future) change to the tools.

**Comment by ptpt** [comment]
Hey @bob3bob3 I'm using this command to extract gpx from blackvue. Hope it's useful for you too:

```
python3 -m mapillary_tools.geotag.geotag_from_blackvue path/to/blackvue.mp4
```

**Comment by bob3bob3** [comment]
Thanks @ptpt !
