### ISSUE TITLE
what happens to --keep_original in release 0.8.0?

### ISSUE THREAD

**Issue by Strubbl** [mapillary/mapillary_tools#477]
### Basic information
* Release version: `0.8.0`
* System: `Windows` | `Linux` | `...`
* Capture Device: `iOS` | `Android` | `Action Camera` | `...`

### Steps to reproduce behavior

 1. use `--keep_original` as parameter as it was possible in release 0.7.6., e.g. `mapillary_tools process_and_upload --user_name "xyz" --keep_original ~/photos3`
 2. get error `mapillary_tool: error: unrecognized arguments: --keep_original`

### Expected behavior
No error. Keep original photos.

### Actual behavior
above mentioned error message

**Comment by bob3bob3** [comment]
Just a remark

Prior to 0.8.0 a "special" image file EXIF tag was written for use by the Mapillary server, This is no longer the case, now that information is held in a separate json file. The other EXIF tags have always been optional and can be suppressed by the relevant tagging command.

In short the original image file is no longer changed, thus --keep_original is not needed.

**Comment by Strubbl** [comment]
Also there is no progress shown anymore. How do i know what's the current status of the upload? I only see a lot of python stacktraces. If i restart the process, does it upload all photos again? Version 0.8.0 is kinda unusable in this regard.

**Comment by bob3bob3** [comment]
I use --verbose as the first argument after "mapillary_tools". It's all text, but very detailed and easy to figure where the upload is up to.

I only did limited testing with crash/restart. It recovered okay. There was a (fixed) bug a month plus ago that was duplicating uploads, so keep it updated, The actual version number isn't changing so;
python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools 
every time a merge to master is seen here.

**Comment by Strubbl** [comment]
i could upload duplicates :( now i have a lot of pictures duplicated. How can i clean this and delete the duplicate ones?

**Comment by bob3bob3** [comment]
The web GUI has had the ability to delete entire sequences function reinstated. It does take maybe 2 weeks to work though. Individual image deletion isn't available though.

**Comment by Strubbl** [comment]
Thanks for the hint, i have found the web gui option to delete the entire sequence.

**Comment by Strubbl** [comment]
> I use --verbose as the first argument after "mapillary_tools". It's all text, but very detailed and easy to figure where the upload is up to.

i tried that, but the strings are not very readable for me. i do not know where the status of the current uploaded sequence is nor do i know which sequence is uploaded.

 
> I only did limited testing with crash/restart. It recovered okay. There was a (fixed) bug a month plus ago that was duplicating uploads, so keep it updated, The actual version number isn't changing so; python3 -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools every time a merge to master is seen here.

The bug might still exist, since i have a lot of duplicated sequences 😭 and it is a lot to click to get only one sequence reported to be deleted

**Comment by bob3bob3** [comment]
The debug info - example;

2021-11-20 14:47:32,618 - DEBUG  - Sending upload_progress via IPC: {
'sequence_idx': 1, #### SEQUENCE CURRENTLY BEING UPLOADED ####
'total_sequence_count': 3, #### TOTAL NUMBER IF SEQUENCES TO UPLOAD IN THIS SESSION ####
'sequence_image_count': 122, 
'sequence_uuid': '3357f558-d303-4e68-80c2-cc9a70149b57', 

'entity_size': 211321085, #### TOTAL (SEQUENCE) FILESIZE BEING UPLOADED - 211MBytes ####

'md5sum': '7c3810a280e5da02dd57fd89d813d947', 
'upload_start_time': 1637379811.627383, 
'upload_total_time': 0, 

'offset': 185338980, #### WHERE IT IS UP TO NOW - 185MBytes ####

'retries': 0, 
'upload_last_restart_time': 1637379812.1937768, 
'upload_first_offset': 0, 
'chunk_size': 1732140}

0.8.0 doesn't upload on a per image basis. It "zips up" all the images in one sequence into one file in /tmp (Linux) then uploads

I redirect the tools output to a file, then "tail -f" it. During upload it updated every 3-4 seconds so the "offset" is quite visibly changing as it approaches the "entity size".

Support will also help delete things for you. There is a running thread in the forum at the moment that has been taking lists of sequences.

**Comment by Strubbl** [comment]
> 0.8.0 doesn't upload on a per image basis. It "zips up" all the images in one sequence into one file in /tmp (Linux) then uploads

Oh, i only have /tmp with 16 GB space (due to RAM limitation). And often i have a folder of pictures with way more than 16 GB, e.g. up until 60 GB uncrompressed size.
So what happens when /tmp is full?

> I redirect the tools output to a file, then "tail -f" it. During upload it updated every 3-4 seconds so the "offset" is quite visibly changing as it approaches the "entity size".

Not very nice to read if you have big numbers, e.g. your entity size 211321085. How many digits is this? 0.7.6 was way better readable. 

> Support will also help delete things for you. There is a running thread in the forum at the moment that has been taking lists of sequences.

If i have to list them manually, i can also click one more time to send the deletion request.

**Comment by bob3bob3** [comment]
This may help;
https://forum.mapillary.com/t/oserror-errno-28-no-space-left-on-device-when-uploading/5370/8

I'd guess that with 16GB space you wont have a problem. I think one sequence only has 500 images maximum so maybe only 500Mbytes-1GBytes used at a time? 

If not then setting the tmp location environment variable elsewhere can be done just prior to running the tools. There is also a dry-run option in the tools if you want to test things (checking space) first.

The numbers are in bytes. I have personally found that just eye-balling the changing number is enough to get a handle on where things are up to. The actual size or number of digits isn't as important. 

A wild guess. The API may be able to download a list of your uploads? Not some thing I have ever tried but maybe worth a look.

**Comment by ptpt** [comment]
Thanks for the report. The upload progress bar was accidentally removed. It should be back now. It will not show in verbose mode though (--verbose).

To upgrade
```
python3 -m pip install --force-reinstall --upgrade git+https://github.com/mapillary/mapillary_tools
```
As @bob3bob3 mentioned, extra space for storing a zip file of maximum 500 images is required. So 16GB /tmp will be fine. If it's still a concern, you can specify where to store the zip files https://github.com/mapillary/mapillary_tools#zip-images

You can turn on the duplication check on the client side. Check https://github.com/mapillary/mapillary_tools/issues/450#issuecomment-950131761
