### ISSUE TITLE
upload_with_authentication.py MOVE_FILES also moves "DONE" file

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#48]
enable MOVE_FILES in upload_with_authentication.py, upload something, tell it to upload DONE. it uploads it and then moves into the "success", then tries to remove it. probably 'DONE' should not be moved to "success" directory.

```
Traceback (most recent call last):
  File "/mapillary_tools/python/upload_with_authentication.py", line 173, in <module>
    upload_done_file(params)
  File "/mapillary_tools/python/upload_with_authentication.py", line 49, in upload_done_file
    os.remove("DONE")
OSError: [Errno 2] No such file or directory: 'DONE'
```

**Comment by jesolem** [comment]
Fixed to avoid error. Now only deletes if file is not moved. 

(Let's keep moving the DONE so you can check the success folder at a later stage. )
