### ISSUE TITLE
upload_with_authentication.py does not show success/failed counts

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#49]
upload.py seems to have some code to show how many files were uploaded successfully and how many failed, but upload_with_authentication.py does not - at the end it just prints :

Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.

**Comment by liskin** [comment]
Also, it happened to me that even though I said 'n', the upload was finalized anyway (not upload_with_authentication.py fault, someone must have done it manually). To this day I haven't got rid of that faulty sequence, cause 'Hide the whole sequence' on the website just plain doesn't work.

So, be extra careful. Don't upload from a wonky home connection, and even when uploading from a dedicated server, use my patched version of upload_with_authentication.py that retries a LOT: https://github.com/liskin/mapillary_tools/commits/master

**Comment by jesolem** [comment]
@richlv Looking at it now upload_with_authentication.py uses upload.py and has the same success/failed printouts.

**Comment by ybkuang** [comment]
Closing this and referring to #64
