### ISSUE TITLE
Do you may/want be responsible for this Greasemonkey script in this repository?

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_tools#5]
See [**GM_mapillary-osm-notes**](/alexandre-mbm/GM_mapillary-osm-notes). Do we may move it to it here?

Example: http://www.openstreetmap.org/note/194601

**Comment by jesolem** [comment]
Sorry for late response. Don't think it makes sense to move here. Thanks.

**Comment by alexandre-mbm** [comment]
OK. It did a while and I walked away from those intentions. The script is outdated and not functional. I realized the emergence of official tools. Sorry and thanks.
