### ISSUE TITLE
upload_with_authentication.py does not move failed files

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#50]
if some files fail to upload with upload_with_authentication.py, they are not moved in the "failed" directory even with "MOVE_FILES = True". successfully uploaded files are moved.

although a much better approach would be to retry them either infinitely or allow user to initiate retry - somewhat covered in issue #23

**Comment by jesolem** [comment]
Retry was added in #58 , so if that's the better solution we should be good. Thanks!

**Comment by richlv** [comment]
true, but both upload_with_authentication.py and upload.py still reference that directory (and also create it) - that should probably be removed :)

can we reopen this issue or should a new one be created ?

**Comment by jesolem** [comment]
You're right. Make a new one for the folders and I'll fix it.
