### ISSUE TITLE
improvement of readme.md

### ISSUE THREAD

**Issue by it4workflow** [mapillary/mapillary_tools#51]
i'm an ordinary mapper and using gopro hd 1080 in stills-mode. so i have to run some of the scripts of mapillary_tools. but some explanations of readme.md are unclear to me:
* `add_project.py` is only for mapillary business, isn't it? or how can i use it?
* `geotag_from_gpx.py` works fine, after install gpxpy-module
* `interpolate_direction.py` doesn't works, but have i to run it after `geotag_from_gpx.py` which already set bearing?
* `add_mapillary_tag_from_exif.py` what is it for and where get MAPILLARY_UPLOAD_TOKEN
* `upload_with_authentication.py` results in #34, because i also set `export MAPILLARY_PERMISSION_HASH="hash"` (with quotes) after reading http://blog.mapillary.com/technology/2014/07/21/upload-scripts.html

**Comment by jesolem** [comment]
> add_project.py is only for mapillary business, isn't it? or how can i use it?

It is for private projects, yes.

> geotag_from_gpx.py works fine, after install gpxpy-module

Added explanation to the readme.

> interpolate_direction.py doesn't works, but have i to run it after geotag_from_gpx.py which already set bearing?

You need as a minimum lat,lon which your GoPro images probably lack until you use geotag.

> add_mapillary_tag_from_exif.py what is it for and where get MAPILLARY_UPLOAD_TOKEN

Updated the description. In essence:

```
Script for uploading images taken with other cameras than the Mapillary iOS or Android apps.
Adds Mapillary data to EXIF tag to enable image to be handled in the same way as Mapillary
native images.
```
