### ISSUE TITLE
v0.8.2 "is damaged" and does not run on Apple M1 with Monterey 12.4

### ISSUE THREAD

**Issue by marcgemis** [mapillary/mapillary_tools#512]
I just downloaded mapillary_tools v0.8.2 on an Apple M1 running Monterey 12.4.
Each time I try to execute the program, I get a popup with “mapillary_tools” is damaged and can’t be opened. You should move it to the Bin." I have to choose between Cancel and Move to Bin.

Since this is a new machine, I have not run earlier versions of mapillary_tools on it.

**Comment by ptpt** [comment]
After downloading the binary, you need to run:
```
unzip  mapillary_tools-0.9.0-osx-x86_64.zip
cd  mapillary_tools-0.9.0-osx-x86_64
xattr -c mapillary_tools
```
then it should work

**Comment by DavidMetcalfe** [comment]
What happened to building from a local system to enable M1 support? This is still not fixed as of v0.9.1

**Comment by ptpt** [comment]
@DavidMetcalfe didn't it work after `xattr -c mapillary_tools` on your M1? What was the error? I own a M1 and it works.

**Comment by DavidMetcalfe** [comment]
@ptpt The `xattr -c` step works, but why isn't it incorporated into the tool as an automated step? Can it only be done manually by the user? If so, this step should be documented.

**Comment by ptpt** [comment]
Makes sense. I will check if it's possible to add this step to the CI.

**Comment by ptpt** [comment]
This can't be fixed in CI because when you download it the system adds some attributes to the executable. The solution is mentioned in README.
