### ISSUE TITLE
Upload each folder as sequence

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_tools#52]
Can't see here how it actually uploads, would like to put warning about upload.py in but do not see where it is actually used.

Furthermore, what is line 9: ```sys.cleansetdefaultencoding("utf-8")```? I can't find any documentation, a Google search only gives me that page. Did you mean ```sys.setdefaultencoding("utf-8")```, if so you will also need ```reload(sys)``` beforehand, unsure why but yeah.

EDIT - figured out why
```
This function is only available at Python start-up time, when Python scans the environment. It has to be called in a system-wide module, sitecustomize.py, After this module has been evaluated, the setdefaultencoding() function is removed from the sys module.
The only way to actually use it is with a reload hack that brings the attribute back.
```
TY StackOverflow 3828723

**Comment by jesolem** [comment]
This should not be there, something from @peterneubauer 's editor. Killed it.
