### ISSUE TITLE
Question about Duplicate Info

### ISSUE THREAD

**Issue by BrettFrahm** [mapillary/mapillary_tools#533]
Basic information
System: Windows
Capture Device: Go Pro Max

Question:
Is there information about which photos were duplicates in the .mapillary logs after you upload. I've been looking through the .json files and I can't find where it says which photos were duplicates and weren't uploaded. Only place I can find duplicate information is in the mapillary_import_summary.json where it says the number of duplicates.

**Comment by ptpt** [comment]
Yes, the [latest version](https://github.com/mapillary/mapillary_tools/releases/tag/v0.9.1) writes all processing metadata in a single JSON file "mapillary_image_description.json", including which images are duplicates.
