### ISSUE TITLE
upload_each_folder_as_sequence.py

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_tools#54]
Hey.. i used mapillary_tools/python/upload_each_folder_as_sequence.py and it would be great, if 
there could be made a second one, that upload's from several child folders into several sequences.

i used the split pythonfile and after that i want to upload this splitted files with a simple script and thought, that the mapillary_tools/python/upload_each_folder_as_sequence.py would do that, but it's only for a merged upload into a single sequence

hope i am in the correct folder, as i don't see any other way to suggest a change/new script for the mapillary_tools...

**Comment by peterneubauer** [comment]
So, what do run against a tree of folders, and have each subfolder be a separate sequence? Should not be hard to do.

**Comment by jernejaMislej** [comment]
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). 
Please use the new tools and get back to us in case of any trouble. Closing this issue as the script `upload_each_folder_as_sequence.py` is no longer available.
