### ISSUE TITLE
mapillary_tool: error: invalid choice: 'from multiprocessing.resource_tracker import main;main(3)'

### ISSUE THREAD

**Issue by DavidMetcalfe** [mapillary/mapillary_tools#547]
### Basic information
* Release version: `0.9.1`
* System: `Mac OS 13.0`
* Capture Device: `BlackVue`

### Steps to reproduce behavior

 1. Copy videos from MicroSD card in BlackVue camera to Mac HDD.
 2. Run `./mapillary_tools upload_blackvue ./ --user_name "davidmetcalfe"`
 3. Allow upload process to run through videos in folder.
 4. Observe error message after upload is completed.

### Expected behavior

No error messages after upload completes.

### Actual behavior

Error message after upload completes:

"2022-09-18 17:11:18,169 - INFO    -      112  BlackVue videos uploaded
2022-09-18 17:11:18,171 - INFO    -  10830.0M data in total
2022-09-18 17:11:18,172 - INFO    -  10830.0M data uploaded
2022-09-18 17:11:18,173 - INFO    -   5252.2s upload time
multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
(base) dmetcalfe@davids-mac-mini Mapillary % usage: mapillary_tool [-h] [--version] [--verbose]
                      {process,upload,upload_blackvue,upload_zip,sample_video,video_process,authenticate,process_and_upload,video_process_and_upload,zip} ...
mapillary_tool: error: invalid choice: 'from multiprocessing.resource_tracker import main;main(3)' (choose from 'process', 'upload', 'upload_blackvue', 'upload_zip', 'sample_video', 'video_process', 'authenticate', 'process_and_upload',(base) dme(b(base) dmetcalfe@davids-mac-mini Mapillary % ./mapil(base) dmetcalfe@davids-mac-mini Mapillary % ./mapillary(base) dmetcalfe@d(bas(b(b(b(b(b(bas(b(b(bas(b(b(b(b(b(b(b(b(bas(b(b(bas(b(b(b(bas(b(b(b(b(b(b(b(b(b(b(bas(bas(base) d(base) dmetcal(base) dmetcalfe(base) dmetcalfe@dav(base) dmetcalfe@david(base) dmetcalfe@david(base) dmetcalfe@dav(base) dmetcalfe@d(base) dmetcalfe(base) dmetcal(base) dme(base) dme(base) dme(base) d(base) d(base)(base) d(base)(base)(base)(base)(bas(bas(b(b(b(b(b(b(b..."

Screenshot: 
<img width="1112" alt="Screenshot 2022-09-19 at 11 40 03 AM" src="https://user-images.githubusercontent.com/80915/191111828-9c887254-9b6a-4f2d-876e-1792db1c15e3.png">

**Comment by DavidMetcalfe** [comment]
The same error has occurred on every upload I've performed on `v0.9.1` (3 batches now).

**Comment by ptpt** [comment]
It seems to be warnings from pyinstaller side https://github.com/pyinstaller/pyinstaller/issues/4865
