### ISSUE TITLE
allow to resume a sequece with upload_with_authentication.py

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#57]
upload_with_authentication.py currently does not allow to resume a sequence - attempting to do that just starts a new sequence.

this would be needed because it tends to skip images upon failure. even when that would be fixed, such a feature could be highly useful - let's say i'm uploading a sequence, and then i have to move to a different location with my laptop. currently that means restarting the upload of that sequence, in some cases resulting in gigabytes of data transferred again.

**Comment by Skippern** [comment]
I support this, if the script created a SEQUENCE file or something in the directory with the sequence hash ID it would be possible to append to the sequence if upload is interrupted for some reason

**Comment by jesolem** [comment]
Good idea @Skippern

**Comment by richlv** [comment]
too bad mapillary scripts don't use perl, i'm kinda trying to learn that one ;)
after having tu re-upload gigabytes of images recently, i tried to figure out how to reliably allow resuming, but stopped a bit short of an automatic solution. below "sequence_id = uuid.uuid4()", i added :
```
sfile = open('SEQUENCE','w')
sfile.write(str(sequence_id)+'\n')
sfile.close()
```
this seems to save the sequence id, which i could probably could manually insert in the script later (haven't needed that since then :) ). a more proper idea probably would be to automatically detect SEQUENCE file and grab the id from there

**Comment by jesolem** [comment]
@richlv Make a Perl script and we add it ;)

**Comment by richlv** [comment]
@jesolem - trying to learn, meaning i could attempt to modify something existing ;)
far from writing something like that from the scratch.

**Comment by richlv** [comment]
just for the record, the inability to properly resume uploads is creating more work for mapillary people, too... for example, i had hardcoded the uuid to upload a failed sequence, and forgot to change it later. uploaded some more sequences with the same uuid and had to ask to have them cut (and i'm not even sure that worked properly, so there might be slightly broken data now)

**Comment by jesolem** [comment]
@ybkuang is pushing out a bigger update to the scripts soon, will assign and maybe he has some ideas.

**Comment by ybkuang** [comment]
@richlv in the new version, we will have the option to keep the sequence uuids so that you can continue the upload without breaking the sequence. We will push that out soon.

**Comment by richlv** [comment]
thanks for the info. the best option would be to save sequence id by default in the upload directory, reuse it if the sequence file is found and never descend in subdirs (like "success") - i really hope that's the direction it is going in :)

**Comment by jernejaMislej** [comment]
We have replaced the EXIF editing library and released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). 
Logging has been improved and enables more overview of the process and upload outcome and supports retrying failed uploads without creating a new sequence.
Please use the new tools and get back to us in case of any trouble.

**Comment by richlv** [comment]
Hmm, I'm not aware of the patch being merged, resuming is likely not supported still - please reopen.

**Comment by jernejaMislej** [comment]
Hi, the script for which the issue was opened is not supported anymore, all its functionalities are now available through `mapillary_tools process_and_upload [args]` and resuming a sequence is supported
