### ISSUE TITLE
[Feature Request] Please support over 2FPS frequency shooting data.

### ISSUE THREAD

**Issue by mapconcierge** [mapillary/mapillary_tools#593]
I would like to see the camera support higher frequency shooting data than 1FPS.

Actually, Ricoh THETA X can take 8K video 2/10FPS frequency.
Latest mapillary_tools can process those data, but it means only 1FPS frequency.
https://github.com/mapillary/mapillary_tools/issues/536

My result.
https://www.mapillary.com/app/?lat=43.768171785529&lng=11.253255743011&z=17&pKey=536322358546361&focus=photo&x=0.5016456381446478&y=0.5228810357200745&zoom=0

**5 mins * 2FPS = 600 frames**

But after mapillary_tools process with 5min/2FPS data, then it result files exit only 150 jpg files. That's means 0.5 FPS(2 sec interval).

Below image files mean 5 mins 8K/2FPS Video data.
<img width="734" alt="スクリーンショット 2023-01-11 9 38 50" src="https://user-images.githubusercontent.com/416977/211691299-3a2ce25c-aca7-4559-90aa-0e5ed82f1ed5.png">

We are taking more frequent shots, and we believe those data will improve the quality of the Mapillary data even more.

**Comment by ptpt** [comment]
Hi @mapconcierge

For 2fps, try this option `--video_sample_interval=0.5`

```sh
$ mapillary_tools video_process --video_sample_interval=0.5 ./videos/

$ mapillary_tools video_process --help
...
  --video_sample_interval VIDEO_SAMPLE_INTERVAL
                        Time interval for sampled video frames in seconds. [default: 2.0]
...
```

**Comment by ptpt** [comment]
BTW @mapconcierge, starting from v0.9.5, mapillary_tools supports direct CAMM/GoPro/BlackVue uploading without local processing (videos -> images). Try:

```sh
# v0.9.5
$ mapillary_tools upload --file_types=camm ./videos/
```

The uploaded videos will be sampled by distance (5 meters) instead time interval (2 seconds). Would be great if you could give it a try, and let us know if it improves the capture density.

**Comment by mapconcierge** [comment]
Thanks!!! :-)

I will try!!!!!

**Comment by mapconcierge** [comment]
I've confirmed!! Many thanks!
https://github.com/furuhashilab/mapping/issues/71#issuecomment-1378809334
