### ISSUE TITLE
Version 0.10.0 requires GLIBC-2.35

### ISSUE THREAD

**Issue by jswk** [mapillary/mapillary_tools#595]
### Basic information
* Release version: `0.10.0`
* System: `Ubuntu 20.04`

### Steps to reproduce behavior

```shell
$ ./mapillary_tools-0.10.0-linux-x86_64 
[24431] Error loading Python lib '/tmp/_MEICOYshv/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEICOYshv/libpython3.11.so.1.0)
```

### Expected behavior

The tool should show the help, as for the 0.9.5 version:
```shell
$ ./mapillary_tools-0.9.5-linux-x86_64 
usage: mapillary_tool [-h] [--version] [--verbose]

[...]
```

### Additional information

Seems like it's some extra dependency coming from python 3.11.

Also, 0.9.5 already uses 3.11 to build, but it still works on Ubuntu 20.04.

**Comment by ptpt** [comment]
Could you check if the new linux builds works? https://github.com/mapillary/mapillary_tools/releases/tag/v0.10.1

**Comment by jswk** [comment]
@ptpt Unfortunately, I'm still getting the same error:
```
$ ./mapillary_tools-0.10.1-linux-x86_64 
[12434] Error loading Python lib '/tmp/_MEI2AMxji/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEI2AMxji/libpython3.11.so.1.0)
``

**Comment by ptpt** [comment]
It is likely that Github Action builds the binary in the latest ubuntu 22.04 in which GLIBC is not compatible with 20.04's https://github.com/mapillary/mapillary_tools/blob/main/.github/workflows/release.yml#L67

As for now, you can use pip install or build your own binary. I will close this one unless we see more requests.

cc @nickplesha
