### ISSUE TITLE
video_process has cryptic error message for video files without GPS data

### ISSUE THREAD

**Issue by Zaneo** [mapillary/mapillary_tools#599]
### Steps to reproduce behavior

 1. `mapillary_tools video_process MY_VIDEO_DIR --geotag_source "gpx" --geotag_source_path MY_EXTERNAL_GPS.gpx`

### Expected behavior

Data is processed

### Actual behavior

No image data is created instead a cryptic error message is generated.

### Corresponding data

A video file without GPS data. 

### Additional information

The issue seems to be that `video_sample_distance` is used even if the video does not contains any GPS data. This is the point of the video process command to add GPS data. Either the instructions should say that you need to disable distance based sampling or the program should give a less cryptic error message. 

`WARNING - No GPS data found from the video` 

Could be,

`WARNING - No GPS data found from the video, which is required by video_sample_distance`

**Comment by ptpt** [comment]
Let's track in https://github.com/mapillary/mapillary_tools/issues/596
