### ISSUE TITLE
upload_each_folder_as_sequence.py seems to freeze between folders

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#60]
upload_each_folder_as_sequence.py seems to freeze when completing a folder. There is no indication of what the script is doing, everything just hangs.

Mac OS X 10.10.4, python2.7, all dependencies up to date with pip

temporary solution is to run upload_with_authentication.py in loop

**Comment by jesolem** [comment]
Yeah, naming mistake on @peterneubauer 's behalf. It does not actually upload. He'll either add upload or explain better.

**Comment by ybkuang** [comment]
This has been fixed by @peterneubauer by renaming the script to add_mapillary_tag_from_exif.py
