### ISSUE TITLE
EXIF time problem when extracting photos from split videos

### ISSUE THREAD

**Issue by PierreSerpe** [mapillary/mapillary_tools#606]
### Basic information
* Release version: `mapillary_tools version 0.10.0` 
* System: `Windows WSL2 Linux` 
* Capture Device: `GoPro Hero 11`

### Steps to reproduce behavior

 1. Record a movie with GoPro Hero11 lasting long enough to have an automatic file split
 2. Use the following command to extract photos from the videos: _mapillary_tools video_process MY_VIDEO_DIR MY_SAMPLES --video_sample_distance 5_
 3. Check the EXIF time of the last photo extracted from the first and second video. Compare EXIF times of photos extracted from both videos.

### Expected behavior

The EXIF time of the first photo extracted from the second video should be equal to the EXIF time+~1sec of the last photo extracted from the first video.

### Actual behavior

The time of the last photos from both videos is the same.  As a result, the EXIF time of the photos extracted from the second video is already in use in the photos extracted from the first video. 
This becomes a problem when synchronising GPS position with a GPX file in geosetter.

### Corresponding data

* sample images
![GX010106_0_038257](https://user-images.githubusercontent.com/102526566/225140825-21fc21c7-d2fe-4ec7-92de-597b1708cb73.jpg)

![GX020106_0_013289](https://user-images.githubusercontent.com/102526566/225140642-234f11e1-b869-43fb-b13c-c305c9a6cc05.jpg)

...

### Additional information

... 

Exif time of the last photo exported from the first video is 8:27:21 :
![image](https://user-images.githubusercontent.com/102526566/225137930-81acf010-c5ee-4b27-8d46-0158885ab2a1.png)

Exif time of the last photo exported from the second video is 8:27:20 :
![image](https://user-images.githubusercontent.com/102526566/225138216-65186207-1065-4131-92a1-733d2ab94cd8.png)

**Comment by ptpt** [comment]
It's likely to be the split videos have the same video timestamp. See https://github.com/mapillary/mapillary_tools/issues/505

Can you check the tags -> creation_time of the video track, and see if they are the same?
```
ffprobe -show_streams -print_format json video1.mp4
ffprobe -show_streams -print_format json video2.mp4
```

**Comment by PierreSerpe** [comment]
Both video track have the same creation time indeed.

**Comment by ptpt** [comment]
The plan was to find all video segments in a folder (by name pattern) and calculate the video time shift. No need to combine videos (which is expensive).

Thanks for the feedback. Let's track the updates in #505
