### ISSUE TITLE
command line argument to force "DONE" at end of upload_with_authentication.py

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#61]
I would like upload_with_authentication.py to have an argument to force "DONE" after last file have been uploaded. I need this to be able to automate uploads (cron job style)

**Comment by richlv** [comment]
for the record, i have edited the script to upload automatically w/o asking for confirmation :)

**Comment by Skippern** [comment]
@richlv what's the hack to look for?

**Comment by richlv** [comment]
in upload_with_authentication.py , replace
proceed = raw_input("Finalize upload? [y/n]: ")
with
proceed = y
:)

**Comment by ybkuang** [comment]
It has been fixed. You now can use the option ```--auto_done```.

**Comment by danbjoseph** [comment]
if i failed to use `--auto_done` when testing an automated upload and the process quit without accepting a prompt, is there some action i can take to finalize the upload? will the server automatically close/finalize the sequence after some amount of time?

**Comment by ybkuang** [comment]
@peterneubauer can you help check this?

**Comment by peterneubauer** [comment]
@danbjoseph can you see your unfinished seqeunces under https://legacy.mapillary.com/map/upload/im ? Otherwise, what is the username to look for? I can do it on the server and add the DONE files.

**Comment by danbjoseph** [comment]
I see 3 sequences on that site. Just click `Push to Mapillary`?

**Comment by peterneubauer** [comment]
Yes, that should do the trick.
