### ISSUE TITLE
upload scripts create & reference "failed" directory but do not use it

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#63]
as discussed in issue #50, upload scripts reference and create a directory "failed" which is supposed to hold failed uploads, but do not seem to actually move files in there (the files just stay in the original directory).

with more retries added, it is sort of expected that uploads are retried and never fail, so the sequence is complete - although i'm slightly confused about the default of 10 retries and do not know what happens when all 10 fail :)

also, looking at upload.py, line 122, it might move files to "failed" if it got some http response code (not exception) besides 204.

somebody with more understanding of both python and what can go wrong when uploading should carefully check this :)

**Comment by liskin** [comment]
If all 10 fail (which could very well happen if your ISP or electricity has an outage) then the files are ignored just as they were before. I would not advise using less than 50 with a home internet connection and would generally like this to be solved better than that: being able to retry failed files without creating a new sequence would be brilliant. But I don't have time and motivation to do that myself. :-(

**Comment by jernejaMislej** [comment]
We have replaced the EXIF editing library and released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). 
Logging has been improved and enables more overview of the process and upload outcome and supports retrying failed uploads without creating a new sequence.
Please use the new tools and get back to us in case of any trouble.
