### ISSUE TITLE
show upload statistics

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#64]
currently the upload scripts just upload and do not show any stats. it would be useful to know :
- total images
- uploaded images
- % completed (or todo)
- time spent
- estimated time to complete

in the simplest case, this could just be printed to stdout repeatedly, or it could be some more fancy repainting.

i have shell scripts to show some of this information, but that's a bit hackish and would be much better to have built-in :)

**Comment by dalacost** [comment]
look this pull request https://github.com/mapillary/mapillary_tools/pull/82

**Comment by dalacost** [comment]
Elapsed and estimated time https://github.com/mapillary/mapillary_tools/pull/83

**Comment by ptpt** [comment]
This is added in 0.8
