### ISSUE TITLE
Only first track of 360 video processed

### ISSUE THREAD

**Issue by marxo** [mapillary/mapillary_tools#657]
### Basic information
* Release version: `0.10.6`
* System: `Linux`
* Capture Device: `GoPro MAX 360`

### Steps to reproduce behavior

 1.  `mapillary_tools video_process INPUT_DIR OUTPUT_DIR --video_sample_distance N` on a `.360` video

### Expected behavior

.360 videos have two "tracks" one for each camera, that form a 360 video when viewed as they get combined. No matter the resolution, when I try processing the video to extract images from it, it processes only the first track, thus resulting in an image that is not 360. Anyone experiencing a similar issue?

**Comment by malconsei** [comment]
@marxo we don't currently support sampling GoPro .360 videos in mapillary_tools. However, you can upload them _as videos_ (with command `process_and_upload`) and we will then process them server-side.
