### ISSUE TITLE
[BUG] Spherical panoramas with GoPro Max .360 files

### ISSUE THREAD

**Issue by wildphyru** [mapillary/mapillary_tools#661]
### Basic information
* Release version: `0.11.0b4`
* System: `Windows 10`
* Capture Device: `GoPro Max`

### Steps to reproduce behavior

 1. use Windows PowerShell with the following command line: mapillary_tools video_process D:/video D:/img --video_sample_distance 5

### Expected behavior
Output a spherical panoramic frame
![GS010207](https://github.com/mapillary/mapillary_tools/assets/35656220/20ce187c-fc98-4c9c-a872-b921b6a38fb6)

### Actual behavior
Output just half that
![GS010207_0_000000](https://github.com/mapillary/mapillary_tools/assets/35656220/568a2835-62f2-44f0-9026-5d1b81c20ad0)

### Corresponding data
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'GS010207.360':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2023-09-23T16:41:42.000000Z
    location        : -21.9574-047.9892/
    location-eng    : -21.9574-047.9892/
    firmware        : H19.03.02.00.00
  Duration: 00:00:54.89, start: 0.000000, bitrate: 60184 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 4096x1344 [SAR 1:1 DAR 64:21], 29941 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      encoder         : GoPro H.265 encoder
      timecode        : 16:40:42:15
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 16:40:42:15
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro TCD
      timecode        : 16:40:42:15
  Stream #0:3[0x4](eng): Data: bin_data (gpmd / 0x646D7067), 86 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro MET
  Stream #0:4[0x5](eng): Data: none (fdsc / 0x63736466), 12 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro SOS
  Stream #0:5[0x6](eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 4096x1344 [SAR 1:1 DAR 64:21], 29960 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      creation_time   : 2023-09-23T16:41:42.000000Z
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      encoder         : GoPro H.265 encoder
      timecode        : 16:40:42:15

### Additional information

I do suspect that the issue is that the stream #0:0 contains half the data and the stream #0:5 the other half but the code is using just the stream #0:0 with this line:

Extracting frames: ffmpeg -hide_banner -nostdin -i GS010207.360 -map 0:0 -filter_script:v /tempDir/ -vsync 0 -frames:0 53 -frame_pts 1 -qscale:0 2 outputDir\GS010207_0_%06d.jpg

The following warnings appears
Unsupported codec with id 0 for input stream 2
Unsupported codec with id 98314 for input stream 3
Unsupported codec with id 0 for input stream 4

-vsync is deprecated. Use -fps_mode
Passing a number to -vsync is deprecated, use a string argument as described in the manual.
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001e49df843c0] All samples in data stream index:id [4:5] have zero duration, stream set to be discarded by default. Override using AVStream->discard or -discard for ffmpeg command.

**Comment by ptpt** [comment]
Yes, there are two streams in GoPro Max videos. This is a known issue for the client side video processing https://github.com/mapillary/mapillary_tools#local-video-processing

Suggest upload these 360 videos directly and the server will process them correctly https://github.com/mapillary/mapillary_tools#process-and-upload
