### ISSUE TITLE
incorrect formatting in the upload_with_authentication.py output

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#67]
minor, but... in the output of upload_with_authentication.py, sometimes a line can be prefixed with an excess space :

```
Uploading: IMG_3260.JPG
 Uploading: IMG_3308.JPG
Uploading: IMG_3305.JPG
```

sometimes it can concatenate two lines and then add an extra newline :

```
Uploading: IMG_3266.JPG
 Success: IMG_3171.JPGSuccess: IMG_3213.JPG
Success: IMG_3088.JPG
Uploading: IMG_3133.JPG

Uploading: IMG_3270.JPG
```

**Comment by jesolem** [comment]
Because threading. If you think it is worth locking writing across threads and have an idea for how to do it, let me know ;) I'm not sure myself.

**Comment by jernejaMislej** [comment]
closing this as it is a minor issue we are not planning to address at the moment.
the issue does not affect the image import, but only the way information is printed out to the user
