### ISSUE TITLE
add_mapillary_tag_from_exif.py problem with pyexiv2 in macports named py-exiv2

### ISSUE THREAD

**Issue by lorenzoperone** [mapillary/mapillary_tools#69]
I'm trying the Python script add_mapillary_tag_from_exif.py in mac os 10.10.5 using python 2.7 through macports.
I've found the similar binding of pyexiv2 in macports but it's named py-exiv2, changing the library name in the script didn't had a good result, the script return:

_File "add_mapillary_tag_from_exif.py", line 12
    import py-exiv2
             ^
SyntaxError: invalid syntax_

Is there a workaround for running the script using macports?
Thanks.

**Comment by paulinus** [comment]
Hi @lorenzoperone,
py-exiv2 might be the name of the macport package.  If you have installed such package, you should still use pyexiv2 on the python script. Did you try the script without modifying that line?

**Comment by lorenzoperone** [comment]
Hi Paulinus,
if I use pyexiv2 in the script I have as result:

*lorenzo-macbook:python lorenzo$ MAPILLARY_USERNAME=lorenzo.perone@gmail.com MAPILLARY_EMAIL=lorenzo.perone@gmail.com MAPILLARY_PASSWORD=XXX python add_mapillary_tag_from_exif.py   /Volumes/WD_Elements/Foto/2015/20150829/
Traceback (most recent call last):
  File "add_mapillary_tag_from_exif.py", line 12, in <module>
    import pyexiv2
ImportError: No module named pyexiv2
lorenzo-macbook:python lorenzo$*

**in macport**

*lorenzo-macbook:python lorenzo$ sudo port info py-exiv2
py-exiv2 @0.3.2_2 (python, graphics)
Sub-ports:            py27-exiv2
Description:          pyexiv2 is a Python binding to exiv2, the C++ library for
                      manipulation of EXIF, IPTC and XMP image metadata.
Homepage:             http://tilloy.net/dev/pyexiv2/overview.html
Library Dependencies: py27-exiv2
Platforms:            darwin
License:              GPL-2
Maintainers:          devans@macports.org, openmaintainer@macports.org*

*lorenzo-macbook:python lorenzo$ sudo port contents py-exiv2
Port py-exiv2 contains:
  /opt/local/share/doc/py-exiv2/README*

*lorenzo-macbook:python lorenzo$ sudo port contents py27-exiv2
Port py27-exiv2 contains:
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/libexiv2python.so
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/__init__.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/exif.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/iptc.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/metadata.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/preview.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/utils.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyexiv2/xmp.py*

*lorenzo-macbook:python lorenzo$ sudo port -v installed py-exiv2
The following ports are currently installed:
  py-exiv2 @0.3.2_2 (active) platform='darwin 14' archs='noarch'*

*lorenzo-macbook:python lorenzo$ sudo port -v installed py27-exiv2
The following ports are currently installed:
  py27-exiv2 @0.3.2_2 (active) platform='darwin 14' archs='x86_64'*

I think that pyexiv2 is only a metapackage.
Thanks.

**Comment by paulinus** [comment]
It seems that you have pyexiv2 installed. It might be that python is not finding it. You can try setting the `PYTHONPATH` to tell python where to find it. Can you try running

    export PYTHONPATH=$PYTHONPATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

before the script?

**Comment by lorenzoperone** [comment]
Hi,
now I have a segmentation fault, it seems that the first problem was solved, I'll investigate on the new one...
Thanks.
l.

**Comment by lorenzoperone** [comment]
Hi,
I think it could depend by the fact I've installed some Python packages using macport and other like this (http://www.kyngchaos.com/software/python) from another port.
It could be possible?
In this case I think I'll not able to find a solution...
Thans.
l.

**Comment by paulinus** [comment]
Segmentation faults can indeed come from using different versions of python and python modules. If numpy or scipy are the problem, i would recommend installing them through pip, which works great now (it used not to be the case)

**Comment by lorenzoperone** [comment]
Hi Pau,
thanks, what is the best way to remove the Pyton modules that I’ve installed? The packages I’ve used don’t have any uninstall option…
Bye.
l.

**Comment by paulinus** [comment]
If the method you used to install them does not have an option to uninstall, you will need to delete the files manually. This can be difficult since you don't know where they are or if they are used somewhere else in the system. It is easy to break things, so be careful.
To find the location of a package you can enter the python console. Import the package and type `package_name.__file__`
For example, for the scipy package this gives me
```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__file__
'/Library/Python/2.7/site-packages/scipy/__init__.pyc'
>>> 
```
So i would delete (or move to a backup folder) the `/Library/Python/2.7/site-packages/scipy`. This will break things that use scipy so do it only if you are ok with the consequences.

**Comment by lorenzoperone** [comment]
Hi Pau,
I took a look about the versions of the Python modules installed on my Mac, looking the same packages in pip I’ve found the most recent version.
I think that the newest modules could not agree with the software I’ve on board.
I think could be better to do a sandbox using a virtual machine, have you any suggest about?
I could use windows or linux VM.
Thanks.
l.

**Comment by nighto** [comment]
Hi, I'm having some troubles to successfully run this in El Capitan. I'm getting the error `No module named pyexiv2`, even though it is installed by `brew`.

Googling around, I found [some instructions](http://stackoverflow.com/questions/16623902/pyexiv2-with-homebrew-python-2-7-4) saying that if you compile `boost` it should work, but it didn't.

Any other ideas?

**Comment by dexterslu** [comment]
ran into this issue earlier today. was able to resolve it by looking back at my brew install of pyexiv2, where it provides site-packages for sys.path.

**Comment by jernejaMislej** [comment]
We have replaced the EXIF editing library and released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). 
Installation of the tools and its dependencies has been simplified in order to avoid above issues.
Please use the new tools and get back to us in case of any trouble.
