### ISSUE TITLE
remove_duplicates.py complains of None or corrupt exif data.

### ISSUE THREAD

**Issue by didymops** [mapillary/mapillary_tools#70]
I'm running remove_duplicates on some images that I have geotagged with the geotag_from_gpx.py script. 

remove_duplicates.py looks for the gps_speed EXIF tag and if it's not found it throws the error. That tag isn't set in the geotagging script though. I would think that the gps_speed tag should be set in the geotagging script or the check for the presence of that tag should be removed from the remove_duplicates.py script. 
![image](https://cloud.githubusercontent.com/assets/14117435/9672854/2f5cc158-526c-11e5-8284-b71b91df2bea.png)

**Comment by jesolem** [comment]
@simonmikkelsen Did a PR for missing Orientation tag. This could probably be handled the same way.

**Comment by simonmikkelsen** [comment]
I will fix it, along with another bug. Thanks!

**Comment by simonmikkelsen** [comment]
I have made a PR with a fix that is tested on images with no GPS Speed tag. Until it is accepted the files can be found in https://github.com/simonmikkelsen/mapillary_tools/tree/master/python - Get a fresh copy of both remove_duplicates.py and lib_gps_exif.py as there are bugfixes in both.

**Comment by didymops** [comment]
Thanks! I just tested it out and it works as expected.
