### ISSUE TITLE
Standardize on one python exif library

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_tools#77]
Some scripts use pyexiv2 and some use exifread.

It would be better to only require one. Which is preferred?

**Comment by blaueente** [comment]
The former seems to be deprecated, quote from http://tilloy.net/dev/pyexiv2/ :

>Deprecation warning
>
>pyexiv2 is now deprecated in favour of GExiv2, a GObject-based wrapper around libexiv2. Thanks to >GObject Introspection support, GExiv2 supports Python 2 and 3.
>
>If your application uses pyexiv2, you might want to consider porting it over to GExiv2.

**Comment by ybkuang** [comment]
We are actively looking for a good library for exif parsing/editing. 
For parsing, we have pyexiv2, exifread and pexif (https://github.com/bennoleslie/pexif )
For editing, we are looking for options. pyexiv2 works well so far. We are also looking at pexif
(it is not super active neither, slightly newer than pyexiv2). 

pyexiv2 and pexif are both good as they enable both parsing/editing.  The edge for exifread is that it is more active. 

Your suggestions are very welcome here!

**Comment by pnorman** [comment]
From an end-user standpoint, I find pyexiv2 best as it's the most packaged across my different systems. It's main shortfall is a lack of python3 support

The lack of API documentation for GExiv2 worries me a bit. I suppose if it's the same as pyexiv2 then it's okay, but if that's the case, the script could just conditionally import whichever is found.

None of the exif libraries are under particularly active, but I'm not sure that's a flaw. The EXIF standard is stable, and there's nothing wrong with them being in maintenance mode.

**Comment by pnorman** [comment]
I just checked what I used in 2012, and it was pyexiv2

**Comment by pnorman** [comment]
pyexiv2 isn't packaged with pypi, which turns out to be a real disadavantage

**Comment by posikifi** [comment]
pyexiv2 seems to pretty difficult to install to my enviroment (Ubuntu 14.04). So is there any plans to move pure-Python library, like pexif or piexif (https://github.com/hMatoba/Piexif). After plans, I'd like to hear also timetable ;-)

**Comment by ybkuang** [comment]
@posikifi we have a branch with pexif here https://github.com/mapillary/mapillary_tools/tree/feature-no-pyexiv2. It needs more testing though. You can try it but please backup your photos beforehand.

**Comment by posikifi** [comment]
@ybkuang Ok, I will check that. Thank you!

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have replaced the EXIF editing library and released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). We are still using two libraries, for reading and writing EXIF, but might unify them in the future releases.

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
