### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by mvexel** [mapillary/mapillary_tools#8]
I am trying to upload a (large) sequence and getting intermittent 'connection reset by peer' errors. The full output is in [this gist](https://gist.github.com/mvexel/d90404177356be029ffe). After the last error, the script never returns and it looks like the sequence did not get uploaded.

**Comment by pyrog** [comment]
First attempt to use `upload_with_authentication.py` with 3673 pictures.
Run python script from Mac OS X, pictures are stored on a PC and shared across the network via Netbios.

Got **1129 success**, **39 URL error** `URL error: <urlopen error [Errno 32] Broken pipe> on xxx.jpg`
When the PC goes to sleep mode :angry:, the script got exceptions and stall (same as #27)
```
Exception in thread Thread-4:
…
error: [Errno 54] Connection reset by peer

Uploading: 20150527_192040.jpg
Exception in thread Thread-2:
…
IOError: [Errno 60] Operation timed out: '/Volumes/Users/yves/Pictures/Mapillary/20150527_192040.jpg'

Uploading: 20150527_192044.jpg
Exception in thread Thread-1:
…
IOError: [Errno 60] Operation timed out: '/Volumes/Users/yves/Pictures/Mapillary/20150527_192044.jpg'

Uploading: 20150527_192046.jpg
Exception in thread Thread-3:
…
IOError: [Errno 60] Operation timed out: '/Volumes/Users/yves/Pictures/Mapillary/20150527_192046.jpg'
```

[Manual upload](http://www.mapillary.com/map/upload/im) display:
![manual upload](https://cloud.githubusercontent.com/assets/2158081/7907464/cc6d6574-0839-11e5-80c6-7bd1d1b7a74e.png)

@jesolem Could I kill safely the script and restart it ?

**Note:** None of the successfully downloaded pictures were moved to the `success` folder unlike what you wrote in your post [Upload Scripts](http://blog.mapillary.com/technology/2014/07/21/upload-scripts.html)

**Comment by liskin** [comment]
This is fixed by https://github.com/liskin/mapillary_tools/commit/aab4807e616ddea2188efaaf3157e54f89e98208

**Comment by jesolem** [comment]
Fixed. By #58 from @liskin
