### ISSUE TITLE
time_split.py crashes with metadata files

### ISSUE THREAD

**Issue by tiagofassoni** [mapillary/mapillary_tools#84]
So, it turns out Apple likes to insert little files beginning with '._' for metadata, indexing or whatever. And Apple also loves to place those in my image folders.

So my SD Card has a lot of images in .jpg syntax, but also those little nasty files. And, since time_split.py verification for jpg is just if the file ends with .jpg, it tries to read the EXIF metadata of the Apple files. The EXIFRead returns 0 and I get an error saying datetime.strptime cannot be used in a number.

I'm thinking of ways to solve this. Two come to my mind:
1. Use some jpg reader module to check whether the file is a valid JPG. Caveat: will take some extra time to run.
2. Just add a check for jpg files beginning in '._' 

I'm using the second approach for now, and it works. If that's fine, I'm glad to make a pull request.

**Comment by jernejaMislej** [comment]
hi, please install the latest version of mapillary tools and open a new issue if any problems, I am closing this issue...
