### ISSUE TITLE
Sample images based on distance instead of time interval

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_tools#89]
I need a script like this one: https://github.com/AddisMap/BAME-tools , but I want a picture every n meters, not every n seconds.

**Comment by mxa** [comment]
Any news on picture from video extraction based on meters, not seconds? Five years later.

**Comment by mxa** [comment]
It would be really good if you could provide this basic feature again or at least bring back the legacy uploader which provided this functionality.

**Comment by ptpt** [comment]
@mxa it's in our plan

**Comment by ptpt** [comment]
Now it's sampled every 3 meters. Check out https://github.com/mapillary/mapillary_tools/releases/tag/v0.10.0
