### ISSUE TITLE
a default PERMISSION_HASH and SIGNATURE_HASH on lib/uploader.py??

### ISSUE THREAD

**Issue by dalacost** [mapillary/mapillary_tools#90]
Hi, 
why lib/uploader.py have a default value for PERMISSION_HASH  and SIGNATURE_HASH??

**Comment by dalacost** [comment]
https://github.com/mapillary/mapillary_tools/blob/master/python/lib/uploader.py line 29

**Comment by ybkuang** [comment]
Those are needed for uploading Mapillary images from the app to the right bucket. 

Closing this.
