### ISSUE TITLE
remove_duplicates.py IndexError: tuple index out of range

### ISSUE THREAD

**Issue by didymops** [mapillary/mapillary_tools#94]
I'm experiencing the following issue when running remove_duplicates.py on Windows 8 with Python 2.7. At this point I'm not sure if it's an issue in the code or something strange in my data. I've followed the same processing steps before without encountering the issue so that leads me to believe it is a code problem.

```
>remove_duplicates.py -d 2 "J:\2015-09-09\A\1"
Traceback (most recent call last):
  File "J:\Mobius Photos\mapillary_tools-master\python\remove_duplicates.py", li
ne 418, in <module>
    image_remover.do_magic()
  File "J:\Mobius Photos\mapillary_tools-master\python\remove_duplicates.py", li
ne 262, in do_magic
    capturetime, files = self._sort_file_list(files)
  File "J:\Mobius Photos\mapillary_tools-master\python\remove_duplicates.py", li
ne 251, in _sort_file_list
    capture_times = [self._read_capture_time(filepath) for filepath in file_list
]
  File "J:\Mobius Photos\mapillary_tools-master\python\remove_duplicates.py", li
ne 244, in _read_capture_time
    reader = PILExifReader(filepath)
  File "J:\Mobius Photos\mapillary_tools-master\python\lib_gps_exif.py", line 23
, in __init__
    self._exif = self.get_exif_data(image)
  File "J:\Mobius Photos\mapillary_tools-master\python\lib_gps_exif.py", line 51
, in get_exif_data
    gps_data[sub_decoded] = value[t]
IndexError: tuple index out of range
```

**Comment by ybkuang** [comment]
It looks like there is some irregularity for the GPSInfo in the exif for that particular image. Can you share the image that has this error?

**Comment by didymops** [comment]
Here's one of the images I am using. The only thing that I think could be different from what I have done previously would be to use two decimal places (e.g., 4.15) when setting the time offset with geotag_from_gpx.py. I'm not sure if that could be related. I have done one decimal place before successfully. Thanks!
![imag1001](https://cloud.githubusercontent.com/assets/14117435/10826869/27e7c182-7e42-11e5-846a-44117ad3c629.JPG)

**Comment by didymops** [comment]
I just tried these same pictures on another system and it works as it should. It must have been something wrong with the python installation on the previous machine I used.
