### ISSUE TITLE
upload.py doesn't work on current iOS app photos

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_tools#95]
I took a thousand photos with my iPhone, and now want to upload them from the computer (to avoid having to leave my phone with the screen on and without being able to use other apps for multiple hours).

However, `upload.py` complains that the photos are `Missing required EXIF tag EXIF DateTimeOriginal` and skips them all. (It also says the `*-thumbs.jpg` files are missing `GPS GPSLongitude`, but those are *supposed* to be skipped)

Did the iOS app stop adding the DateTimeOriginal tag? Or did the script simply break from an unrelated change and half-expect normal photos instead of Mapillary-app photos?

**Comment by nicolas17** [comment]
(Note I have never tried the script before, so I don't know if it ever worked with iOS app photos)

**Comment by nicolas17** [comment]
After some 'git bisect', I tracked this down to 6ef24c13ac047587a242389727c3b1d7c5b1bab9. Looks like EXIF verification was added at a low level used by all the upload scripts, but it shouldn't do the same checking for upload.py, which needs a different set of EXIF tags to be present.

**Comment by ybkuang** [comment]
@nicolas17 Thanks for reporting this. We will work on a fix.

**Comment by ybkuang** [comment]
@nicolas17 We did a small fix for this. (It is expected behavior that the *-thumbs.jpg are skipped upon missing exif.)

**Comment by nicolas17** [comment]
It seemed to be working with this fix, but after uploading a few hundred photos I realized it's also uploading the `-thumbs.jpg` files!

```
Uploading 276 images with valid mapillary tags (Skipping 270)
[------------------------------------------------------------] 0.7% ... 542 images left.
```

I also see the `-thumbs.jpg` files being moved into the `success` subdirectory.

**Comment by ybkuang** [comment]
@nicolas17 Sorry, made a mistake here. It should be ok now if you check out the latest changes.

**Comment by nicolas17** [comment]
Yep that fixes it for good :grinning:
