### ISSUE TITLE
phone_holder.scad manifest

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_tools#96]
Sorry that's a bit nitpicky, but a small inconsistency is that when the phone size is set, the labels assume the phone in landscape orientation [width, height]. When the holder is defined, it looks at it in portrait orientation [side, bottom].

ph_width     = 147;
ph_height    = 74;
ph_thick     = 10;
wall			 = 2;
camera_hole_to_top_edge = 10;
camera_hole_to_side_edge = 10;
camera_hole_diameter = 20;
side_edge_to_screen = 10;
bottom_edge_to_screen = 10;
lift_holes_diameter= 15;
edge_cylinder_diameter=5;

**Comment by peterneubauer** [comment]
Uhm just give us a pull request, happy to put that in!
