### ISSUE TITLE
skip_subfolders in upload_with_authentication.py does not seem to work properly

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#97]
spotted the new skip_subfolders option, tried to use it. i might be misunderstanding something, but it looks like it does not work as expected - even if there are images in the current directory, it claims that there are no images at all to be uploaded

**Comment by jesolem** [comment]
Subfolders have confused me earlier too (before the skip option). -> @ybkuang to investigate

**Comment by ybkuang** [comment]
@richlv So it works without `--skip_subfolders` for the same directory?

**Comment by richlv** [comment]
yes, without specifying that option it works properly. specifying it does not upload anything at all, including images in the current directory (not in subfolders/directories).

that's based on my tests in november, did not do git pull & retest currently.

**Comment by ybkuang** [comment]
@richlv have you tried the latest version? will be good to if it is working for you.

**Comment by richlv** [comment]
sorry for abandoning this - changed my mapillary tools/workflow, can't find the time to test.
if the option works as expected for you, feel free to close this issue :)

**Comment by ybkuang** [comment]
Closing this for now @richlv You may reopen if you find further issues.
